# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sr510Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sr510Dialog(object):
    def setupUi(self, Sr510Dialog):
        Sr510Dialog.setObjectName("Sr510Dialog")
        Sr510Dialog.resize(727, 954)
        self.gridLayout = QtWidgets.QGridLayout(Sr510Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Sr510Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity = QtWidgets.QLineEdit(Sr510Dialog)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity.setFont(font)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity.setReadOnly(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity.setClearButtonEnabled(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity.setObjectName("lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity")
        self.gridLayout.addWidget(self.lineedit_base_Sr510CurrentConfigParameters_passive_Sensitivity, 3, 0, 1, 1)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant = QtWidgets.QLineEdit(Sr510Dialog)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant.setEnabled(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant.setReadOnly(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant.setObjectName("lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant")
        self.gridLayout.addWidget(self.lineedit_base_Sr510CurrentConfigParameters_passive_TimeConstant, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(Sr510Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(Sr510Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(Sr510Dialog)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Sr510Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 1, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue = QtWidgets.QComboBox(Sr510Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.setSizePolicy(sizePolicy)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.setObjectName("combobox_base_NewSr510State_passive_Sr510NewSensitivityValue")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue, 8, 0, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue = QtWidgets.QComboBox(Sr510Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.setSizePolicy(sizePolicy)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.setObjectName("combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Sr510Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Sr510Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 1, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier = QtWidgets.QComboBox(Sr510Dialog)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.setObjectName("combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier, 10, 0, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier = QtWidgets.QComboBox(Sr510Dialog)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.setObjectName("combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Sr510Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Sr510Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 1, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits = QtWidgets.QComboBox(Sr510Dialog)
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.setObjectName("combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits, 12, 0, 1, 1)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits = QtWidgets.QComboBox(Sr510Dialog)
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.setObjectName("combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.addItem("")
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits, 12, 1, 1, 1)
        self.button_base_NewSr510State_getter_Sr510NewConfigButton = QtWidgets.QPushButton(Sr510Dialog)
        self.button_base_NewSr510State_getter_Sr510NewConfigButton.setObjectName("button_base_NewSr510State_getter_Sr510NewConfigButton")
        self.gridLayout.addWidget(self.button_base_NewSr510State_getter_Sr510NewConfigButton, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(Sr510Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 14, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(Sr510Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 15, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(Sr510Dialog)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 16, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(Sr510Dialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 16, 1, 1, 1)
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate = QtWidgets.QComboBox(Sr510Dialog)
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setSizePolicy(sizePolicy)
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setEditable(False)
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setObjectName("combobox_base_NewSr510Measurement_passive_Sr510SampleRate")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate, 17, 0, 1, 1)
        self.lineedit_base_NewSr510Measurement_passive_Sr510SampleTime = QtWidgets.QLineEdit(Sr510Dialog)
        self.lineedit_base_NewSr510Measurement_passive_Sr510SampleTime.setObjectName("lineedit_base_NewSr510Measurement_passive_Sr510SampleTime")
        self.gridLayout.addWidget(self.lineedit_base_NewSr510Measurement_passive_Sr510SampleTime, 17, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(Sr510Dialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 18, 0, 1, 1)
        self.lineedit_base_NewSr510Measurement_passive_Sr510StoragePath = QtWidgets.QLineEdit(Sr510Dialog)
        self.lineedit_base_NewSr510Measurement_passive_Sr510StoragePath.setObjectName("lineedit_base_NewSr510Measurement_passive_Sr510StoragePath")
        self.gridLayout.addWidget(self.lineedit_base_NewSr510Measurement_passive_Sr510StoragePath, 19, 0, 1, 2)
        self.button_base_NewSr510Measurement_getter_Sr510StartMeasurementButton = QtWidgets.QPushButton(Sr510Dialog)
        self.button_base_NewSr510Measurement_getter_Sr510StartMeasurementButton.setObjectName("button_base_NewSr510Measurement_getter_Sr510StartMeasurementButton")
        self.gridLayout.addWidget(self.button_base_NewSr510Measurement_getter_Sr510StartMeasurementButton, 20, 0, 1, 2)

        self.retranslateUi(Sr510Dialog)
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Sr510Dialog)

    def retranslateUi(self, Sr510Dialog):
        _translate = QtCore.QCoreApplication.translate
        Sr510Dialog.setWindowTitle(_translate("Sr510Dialog", "Sr510"))
        self.label.setText(_translate("Sr510Dialog", "SR510 Lock-In:"))
        self.label_2.setText(_translate("Sr510Dialog", "Current Parameters:"))
        self.label_7.setText(_translate("Sr510Dialog", "Sensitivity:"))
        self.label_9.setText(_translate("Sr510Dialog", "Time-Constant:"))
        self.label_10.setText(_translate("Sr510Dialog", "New Parameters:"))
        self.label_11.setText(_translate("Sr510Dialog", "Sensitivity:"))
        self.label_12.setText(_translate("Sr510Dialog", "Time-Constant:"))
        self.label_25.setText(_translate("Sr510Dialog", "Value:"))
        self.label_4.setText(_translate("Sr510Dialog", "Value:"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.setItemText(0, _translate("Sr510Dialog", "1"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.setItemText(1, _translate("Sr510Dialog", "2"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityValue.setItemText(2, _translate("Sr510Dialog", "5"))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.setItemText(0, _translate("Sr510Dialog", "1"))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantValue.setItemText(1, _translate("Sr510Dialog", "3"))
        self.label_3.setText(_translate("Sr510Dialog", "Multiplier:"))
        self.label_5.setText(_translate("Sr510Dialog", "Multiplier:"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.setItemText(0, _translate("Sr510Dialog", "x1"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.setItemText(1, _translate("Sr510Dialog", "x10"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityMultiplier.setItemText(2, _translate("Sr510Dialog", "x100"))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.setItemText(0, _translate("Sr510Dialog", "x1"))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.setItemText(1, _translate("Sr510Dialog", "x10"))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantMultiplier.setItemText(2, _translate("Sr510Dialog", "x100"))
        self.label_8.setText(_translate("Sr510Dialog", "Units:"))
        self.label_6.setText(_translate("Sr510Dialog", "Units:"))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.setItemText(0, _translate("Sr510Dialog", "mV."))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.setItemText(1, _translate("Sr510Dialog", "uV."))
        self.combobox_base_NewSr510State_passive_Sr510NewSensitivityUnits.setItemText(2, _translate("Sr510Dialog", "nV."))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.setItemText(0, _translate("Sr510Dialog", "s."))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.setItemText(1, _translate("Sr510Dialog", "ms."))
        self.combobox_base_NewSr510State_passive_Sr510NewTimeConstantUnits.setItemText(2, _translate("Sr510Dialog", "us."))
        self.button_base_NewSr510State_getter_Sr510NewConfigButton.setText(_translate("Sr510Dialog", "Set New Parameters"))
        self.label_13.setText(_translate("Sr510Dialog", "Measurement:"))
        self.label_26.setText(_translate("Sr510Dialog", "Sample Rate (Hz.):"))
        self.label_27.setText(_translate("Sr510Dialog", "Sample Time (s.):"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setCurrentText(_translate("Sr510Dialog", "1"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(0, _translate("Sr510Dialog", "0.0625"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(1, _translate("Sr510Dialog", "0.125"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(2, _translate("Sr510Dialog", "0.250"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(3, _translate("Sr510Dialog", "0.5"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(4, _translate("Sr510Dialog", "1"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(5, _translate("Sr510Dialog", "2"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(6, _translate("Sr510Dialog", "4"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(7, _translate("Sr510Dialog", "8"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(8, _translate("Sr510Dialog", "16"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(9, _translate("Sr510Dialog", "32"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(10, _translate("Sr510Dialog", "64"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(11, _translate("Sr510Dialog", "128"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(12, _translate("Sr510Dialog", "256"))
        self.combobox_base_NewSr510Measurement_passive_Sr510SampleRate.setItemText(13, _translate("Sr510Dialog", "512"))
        self.label_28.setText(_translate("Sr510Dialog", "Measurement Storage Path:"))
        self.button_base_NewSr510Measurement_getter_Sr510StartMeasurementButton.setText(_translate("Sr510Dialog", "Start Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sr510Dialog = QtWidgets.QWidget()
    ui = Ui_Sr510Dialog()
    ui.setupUi(Sr510Dialog)
    Sr510Dialog.show()
    sys.exit(app.exec_())

