# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automationWindowDialog2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 510)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.automation_window = QtWidgets.QStackedWidget(Form)
        self.automation_window.setObjectName("automation_window")
        self.SeriesConstructionAndControlWindow = QtWidgets.QWidget()
        self.SeriesConstructionAndControlWindow.setObjectName("SeriesConstructionAndControlWindow")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.SeriesConstructionAndControlWindow)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.auto_data_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.auto_data_label.setFont(font)
        self.auto_data_label.setObjectName("auto_data_label")
        self.gridLayout_12.addWidget(self.auto_data_label, 4, 0, 1, 2)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.auto_series_sequence_name_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        self.auto_series_sequence_name_label.setObjectName("auto_series_sequence_name_label")
        self.gridLayout_9.addWidget(self.auto_series_sequence_name_label, 0, 0, 1, 1)
        self.auto_series_savedsequences_list = QtWidgets.QListWidget(self.SeriesConstructionAndControlWindow)
        self.auto_series_savedsequences_list.setObjectName("auto_series_savedsequences_list")
        self.gridLayout_9.addWidget(self.auto_series_savedsequences_list, 4, 0, 1, 1)
        self.auto_series_sequence_save_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_series_sequence_save_button.setObjectName("auto_series_sequence_save_button")
        self.gridLayout_9.addWidget(self.auto_series_sequence_save_button, 2, 0, 1, 1)
        self.auto_series_sequence_name_ledit = QtWidgets.QLineEdit(self.SeriesConstructionAndControlWindow)
        self.auto_series_sequence_name_ledit.setObjectName("auto_series_sequence_name_ledit")
        self.gridLayout_9.addWidget(self.auto_series_sequence_name_ledit, 1, 0, 1, 1)
        self.auto_series_savedsequences_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        self.auto_series_savedsequences_label.setObjectName("auto_series_savedsequences_label")
        self.gridLayout_9.addWidget(self.auto_series_savedsequences_label, 3, 0, 1, 1)
        self.auto_series_addsequencestoseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_series_addsequencestoseries_button.setObjectName("auto_series_addsequencestoseries_button")
        self.gridLayout_9.addWidget(self.auto_series_addsequencestoseries_button, 5, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.auto_series_removesequencefromseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_series_removesequencefromseries_button.setObjectName("auto_series_removesequencefromseries_button")
        self.gridLayout_10.addWidget(self.auto_series_removesequencefromseries_button, 2, 0, 1, 1)
        self.auto_series_series_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        self.auto_series_series_label.setObjectName("auto_series_series_label")
        self.gridLayout_10.addWidget(self.auto_series_series_label, 0, 0, 1, 1)
        self.auto_series_series_list = QtWidgets.QListWidget(self.SeriesConstructionAndControlWindow)
        self.auto_series_series_list.setObjectName("auto_series_series_list")
        self.gridLayout_10.addWidget(self.auto_series_series_list, 1, 0, 1, 1)
        self.auto_series_removeallsequencesfromseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_series_removeallsequencesfromseries_button.setObjectName("auto_series_removeallsequencesfromseries_button")
        self.gridLayout_10.addWidget(self.auto_series_removeallsequencesfromseries_button, 3, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 3, 1, 1, 1)
        self.auto_control_pauseseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_control_pauseseries_button.setObjectName("auto_control_pauseseries_button")
        self.gridLayout_12.addWidget(self.auto_control_pauseseries_button, 10, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.SeriesConstructionAndControlWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_12.addWidget(self.line_3, 2, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.SeriesConstructionAndControlWindow)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_12.addWidget(self.line_4, 5, 0, 1, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.data_configuration_metadata_lockin_sensitivity_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_configuration_metadata_lockin_sensitivity_cbox.sizePolicy().hasHeightForWidth())
        self.data_configuration_metadata_lockin_sensitivity_cbox.setSizePolicy(sizePolicy)
        self.data_configuration_metadata_lockin_sensitivity_cbox.setChecked(True)
        self.data_configuration_metadata_lockin_sensitivity_cbox.setObjectName("data_configuration_metadata_lockin_sensitivity_cbox")
        self.gridLayout_11.addWidget(self.data_configuration_metadata_lockin_sensitivity_cbox, 5, 2, 1, 1)
        self.auto_data_metadata_osf_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_data_metadata_osf_cbox.sizePolicy().hasHeightForWidth())
        self.auto_data_metadata_osf_cbox.setSizePolicy(sizePolicy)
        self.auto_data_metadata_osf_cbox.setChecked(True)
        self.auto_data_metadata_osf_cbox.setObjectName("auto_data_metadata_osf_cbox")
        self.gridLayout_11.addWidget(self.auto_data_metadata_osf_cbox, 3, 1, 1, 1)
        self.data_configuration_metadata_grating_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_configuration_metadata_grating_cbox.sizePolicy().hasHeightForWidth())
        self.data_configuration_metadata_grating_cbox.setSizePolicy(sizePolicy)
        self.data_configuration_metadata_grating_cbox.setChecked(True)
        self.data_configuration_metadata_grating_cbox.setObjectName("data_configuration_metadata_grating_cbox")
        self.gridLayout_11.addWidget(self.data_configuration_metadata_grating_cbox, 1, 2, 2, 1)
        self.auto_data_metadata_lockinfs_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_data_metadata_lockinfs_cbox.sizePolicy().hasHeightForWidth())
        self.auto_data_metadata_lockinfs_cbox.setSizePolicy(sizePolicy)
        self.auto_data_metadata_lockinfs_cbox.setChecked(True)
        self.auto_data_metadata_lockinfs_cbox.setObjectName("auto_data_metadata_lockinfs_cbox")
        self.gridLayout_11.addWidget(self.auto_data_metadata_lockinfs_cbox, 4, 1, 1, 1)
        self.auto_data_metadata_wavelength_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_data_metadata_wavelength_cbox.sizePolicy().hasHeightForWidth())
        self.auto_data_metadata_wavelength_cbox.setSizePolicy(sizePolicy)
        self.auto_data_metadata_wavelength_cbox.setChecked(True)
        self.auto_data_metadata_wavelength_cbox.setObjectName("auto_data_metadata_wavelength_cbox")
        self.gridLayout_11.addWidget(self.auto_data_metadata_wavelength_cbox, 1, 1, 2, 1)
        self.auto_data_storagepath_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        self.auto_data_storagepath_label.setObjectName("auto_data_storagepath_label")
        self.gridLayout_11.addWidget(self.auto_data_storagepath_label, 6, 1, 1, 2)
        self.auto_data_metadata_lockintimeconstant_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_data_metadata_lockintimeconstant_cbox.sizePolicy().hasHeightForWidth())
        self.auto_data_metadata_lockintimeconstant_cbox.setSizePolicy(sizePolicy)
        self.auto_data_metadata_lockintimeconstant_cbox.setChecked(True)
        self.auto_data_metadata_lockintimeconstant_cbox.setObjectName("auto_data_metadata_lockintimeconstant_cbox")
        self.gridLayout_11.addWidget(self.auto_data_metadata_lockintimeconstant_cbox, 5, 1, 1, 1)
        self.data_configuration_metadata_shutter_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_configuration_metadata_shutter_cbox.sizePolicy().hasHeightForWidth())
        self.data_configuration_metadata_shutter_cbox.setSizePolicy(sizePolicy)
        self.data_configuration_metadata_shutter_cbox.setChecked(True)
        self.data_configuration_metadata_shutter_cbox.setObjectName("data_configuration_metadata_shutter_cbox")
        self.gridLayout_11.addWidget(self.data_configuration_metadata_shutter_cbox, 3, 2, 1, 1)
        self.data_configuration_metadata_lockints_cbox = QtWidgets.QCheckBox(self.SeriesConstructionAndControlWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_configuration_metadata_lockints_cbox.sizePolicy().hasHeightForWidth())
        self.data_configuration_metadata_lockints_cbox.setSizePolicy(sizePolicy)
        self.data_configuration_metadata_lockints_cbox.setChecked(True)
        self.data_configuration_metadata_lockints_cbox.setObjectName("data_configuration_metadata_lockints_cbox")
        self.gridLayout_11.addWidget(self.data_configuration_metadata_lockints_cbox, 4, 2, 1, 1)
        self.auto_data_metadatatoinclude_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        self.auto_data_metadatatoinclude_label.setObjectName("auto_data_metadatatoinclude_label")
        self.gridLayout_11.addWidget(self.auto_data_metadatatoinclude_label, 0, 1, 1, 2)
        self.auto_data_storagepath_ledit = QtWidgets.QLineEdit(self.SeriesConstructionAndControlWindow)
        self.auto_data_storagepath_ledit.setObjectName("auto_data_storagepath_ledit")
        self.gridLayout_11.addWidget(self.auto_data_storagepath_ledit, 7, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_11, 6, 0, 1, 2)
        self.auto_control_runseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_control_runseries_button.setObjectName("auto_control_runseries_button")
        self.gridLayout_12.addWidget(self.auto_control_runseries_button, 9, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.SeriesConstructionAndControlWindow)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_12.addWidget(self.line_5, 8, 0, 1, 2)
        self.auto_control_abortseries_button = QtWidgets.QPushButton(self.SeriesConstructionAndControlWindow)
        self.auto_control_abortseries_button.setObjectName("auto_control_abortseries_button")
        self.gridLayout_12.addWidget(self.auto_control_abortseries_button, 11, 0, 1, 2)
        self.auto_control_label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.auto_control_label.setFont(font)
        self.auto_control_label.setObjectName("auto_control_label")
        self.gridLayout_12.addWidget(self.auto_control_label, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.SeriesConstructionAndControlWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 1, 0, 1, 1)
        self.auto_window_select_combobox_0 = QtWidgets.QComboBox(self.SeriesConstructionAndControlWindow)
        self.auto_window_select_combobox_0.setObjectName("auto_window_select_combobox_0")
        self.auto_window_select_combobox_0.addItem("")
        self.auto_window_select_combobox_0.addItem("")
        self.gridLayout_12.addWidget(self.auto_window_select_combobox_0, 1, 1, 1, 1)
        self.automation_window.addWidget(self.SeriesConstructionAndControlWindow)
        self.SequenceParametersWindow = QtWidgets.QWidget()
        self.SequenceParametersWindow.setObjectName("SequenceParametersWindow")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SequenceParametersWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequence_lockin_timeconstant_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_lockin_timeconstant_ledit.setObjectName("sequence_lockin_timeconstant_ledit")
        self.gridLayout_2.addWidget(self.sequence_lockin_timeconstant_ledit, 15, 1, 1, 1)
        self.sequence_monochromator_stepsize_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_stepsize_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_stepsize_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_stepsize_label.setObjectName("sequence_monochromator_stepsize_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_stepsize_label, 5, 0, 1, 1)
        self.sequence_monochromator_endwave_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_endwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_endwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_endwave_label.setObjectName("sequence_monochromator_endwave_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_endwave_label, 4, 0, 1, 1)
        self.sequence_monochromator_osf2osf3_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf2osf3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf2osf3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf2osf3_label.setObjectName("sequence_monochromator_osf2osf3_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_osf2osf3_label, 10, 0, 1, 1)
        self.sequence_lockin_timeconstant_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        self.sequence_lockin_timeconstant_label.setObjectName("sequence_lockin_timeconstant_label")
        self.gridLayout_2.addWidget(self.sequence_lockin_timeconstant_label, 15, 0, 1, 1)
        self.sequence_lockin_samplefreq_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_lockin_samplefreq_ledit.setObjectName("sequence_lockin_samplefreq_ledit")
        self.gridLayout_2.addWidget(self.sequence_lockin_samplefreq_ledit, 13, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.SequenceParametersWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        self.sequence_monochromator_osf2osf3_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_osf2osf3_ledit.setObjectName("sequence_monochromator_osf2osf3_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_osf2osf3_ledit, 10, 1, 1, 1)
        self.sequence_monochromator_g2g3_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_g2g3_ledit.setObjectName("sequence_monochromator_g2g3_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_g2g3_ledit, 7, 1, 1, 1)
        self.sequence_lockin_sensitivity_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        self.sequence_lockin_sensitivity_label.setObjectName("sequence_lockin_sensitivity_label")
        self.gridLayout_2.addWidget(self.sequence_lockin_sensitivity_label, 16, 0, 1, 1)
        self.sequence_monochromator_startwave_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_startwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_startwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_startwave_label.setObjectName("sequence_monochromator_startwave_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_startwave_label, 3, 0, 1, 1)
        self.sequence_monochromator_noosfosf1_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_noosfosf1_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_noosfosf1_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_noosfosf1_label.setObjectName("sequence_monochromator_noosfosf1_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_noosfosf1_label, 8, 0, 1, 1)
        self.sequence_monochromator_noosfosf1_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_noosfosf1_ledit.setObjectName("sequence_monochromator_noosfosf1_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_noosfosf1_ledit, 8, 1, 1, 1)
        self.sequence_monochromator_endwave_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_endwave_ledit.setObjectName("sequence_monochromator_endwave_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_endwave_ledit, 4, 1, 1, 1)
        self.sequence_monochromator_g2g3_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g2g3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g2g3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g2g3_label.setObjectName("sequence_monochromator_g2g3_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_g2g3_label, 7, 0, 1, 1)
        self.sequence_lockin_sampletime_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_lockin_sampletime_ledit.setObjectName("sequence_lockin_sampletime_ledit")
        self.gridLayout_2.addWidget(self.sequence_lockin_sampletime_ledit, 14, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.SequenceParametersWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 12, 0, 1, 2)
        self.sequence_monochromator_g1g2_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g1g2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g1g2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g1g2_label.setObjectName("sequence_monochromator_g1g2_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_g1g2_label, 6, 0, 1, 1)
        self.sequence_lockin_sampletime_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        self.sequence_lockin_sampletime_label.setObjectName("sequence_lockin_sampletime_label")
        self.gridLayout_2.addWidget(self.sequence_lockin_sampletime_label, 14, 0, 1, 1)
        self.sequence_monochromator_g1g2_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_g1g2_ledit.setObjectName("sequence_monochromator_g1g2_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_g1g2_ledit, 6, 1, 1, 1)
        self.sequence_monochromator_startwave_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_startwave_ledit.setObjectName("sequence_monochromator_startwave_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_startwave_ledit, 3, 1, 1, 1)
        self.sequence_monochromator_osf1osf2_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf1osf2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf1osf2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf1osf2_label.setObjectName("sequence_monochromator_osf1osf2_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_osf1osf2_label, 9, 0, 1, 1)
        self.sequence_lockin_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_lockin_label.sizePolicy().hasHeightForWidth())
        self.sequence_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_lockin_label.setFont(font)
        self.sequence_lockin_label.setObjectName("sequence_lockin_label")
        self.gridLayout_2.addWidget(self.sequence_lockin_label, 11, 0, 1, 1)
        self.sequence_monochromator_osf1osf2_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_osf1osf2_ledit.setObjectName("sequence_monochromator_osf1osf2_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_osf1osf2_ledit, 9, 1, 1, 1)
        self.sequence_lockin_sensitivity_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_lockin_sensitivity_ledit.setObjectName("sequence_lockin_sensitivity_ledit")
        self.gridLayout_2.addWidget(self.sequence_lockin_sensitivity_ledit, 16, 1, 1, 1)
        self.sequence_lockin_samplefreq_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        self.sequence_lockin_samplefreq_label.setObjectName("sequence_lockin_samplefreq_label")
        self.gridLayout_2.addWidget(self.sequence_lockin_samplefreq_label, 13, 0, 1, 1)
        self.sequence_monochromator_stepsize_ledit = QtWidgets.QLineEdit(self.SequenceParametersWindow)
        self.sequence_monochromator_stepsize_ledit.setObjectName("sequence_monochromator_stepsize_ledit")
        self.gridLayout_2.addWidget(self.sequence_monochromator_stepsize_ledit, 5, 1, 1, 1)
        self.auto_window_select_combobox_1 = QtWidgets.QComboBox(self.SequenceParametersWindow)
        self.auto_window_select_combobox_1.setObjectName("auto_window_select_combobox_1")
        self.auto_window_select_combobox_1.addItem("")
        self.auto_window_select_combobox_1.addItem("")
        self.gridLayout_2.addWidget(self.auto_window_select_combobox_1, 0, 1, 1, 1)
        self.sequence_monochromator_label = QtWidgets.QLabel(self.SequenceParametersWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_monochromator_label.setFont(font)
        self.sequence_monochromator_label.setObjectName("sequence_monochromator_label")
        self.gridLayout_2.addWidget(self.sequence_monochromator_label, 0, 0, 1, 1)
        self.automation_window.addWidget(self.SequenceParametersWindow)
        self.gridLayout.addWidget(self.automation_window, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.automation_window.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.auto_data_label.setText(_translate("Form", "Data Configuration:"))
        self.auto_series_sequence_name_label.setText(_translate("Form", "Sequence Name:"))
        self.auto_series_sequence_save_button.setText(_translate("Form", "Save New Sequence"))
        self.auto_series_savedsequences_label.setText(_translate("Form", "Saved Sequences:"))
        self.auto_series_addsequencestoseries_button.setText(_translate("Form", "Add Sequence To Series"))
        self.auto_series_removesequencefromseries_button.setText(_translate("Form", "Remove Sequence From Series"))
        self.auto_series_series_label.setText(_translate("Form", "Series:"))
        self.auto_series_removeallsequencesfromseries_button.setText(_translate("Form", "Remove All Sequences From Series"))
        self.auto_control_pauseseries_button.setText(_translate("Form", "Pause Series"))
        self.data_configuration_metadata_lockin_sensitivity_cbox.setText(_translate("Form", "Lock-in Sensitivity"))
        self.auto_data_metadata_osf_cbox.setText(_translate("Form", "Order Sort Filter"))
        self.data_configuration_metadata_grating_cbox.setText(_translate("Form", "Grating"))
        self.auto_data_metadata_lockinfs_cbox.setText(_translate("Form", "Lock-in Sample Frequency"))
        self.auto_data_metadata_wavelength_cbox.setText(_translate("Form", "Wavelength"))
        self.auto_data_storagepath_label.setText(_translate("Form", "Storage Path:"))
        self.auto_data_metadata_lockintimeconstant_cbox.setText(_translate("Form", "Lock-in Time Constant"))
        self.data_configuration_metadata_shutter_cbox.setText(_translate("Form", "Shutter"))
        self.data_configuration_metadata_lockints_cbox.setText(_translate("Form", "Lock-in Sample Time"))
        self.auto_data_metadatatoinclude_label.setText(_translate("Form", "Metadata to Include:"))
        self.auto_control_runseries_button.setText(_translate("Form", "Run Series"))
        self.auto_control_abortseries_button.setText(_translate("Form", "Abort Series"))
        self.auto_control_label.setText(_translate("Form", "Control:"))
        self.label.setText(_translate("Form", "Series Construction:"))
        self.auto_window_select_combobox_0.setItemText(0, _translate("Form", "Series Construction and Control Window"))
        self.auto_window_select_combobox_0.setItemText(1, _translate("Form", "Sequence Parameters Window"))
        self.sequence_monochromator_stepsize_label.setText(_translate("Form", "Step Size (um.): "))
        self.sequence_monochromator_endwave_label.setText(_translate("Form", "End Wavelength (um.): "))
        self.sequence_monochromator_osf2osf3_label.setText(_translate("Form", "OSF2 to OSF3 Transition Wavelength (um.):"))
        self.sequence_lockin_timeconstant_label.setText(_translate("Form", "Time Constant (s.):"))
        self.sequence_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity String:"))
        self.sequence_monochromator_startwave_label.setText(_translate("Form", "Start Wavelength (um.):"))
        self.sequence_monochromator_noosfosf1_label.setText(_translate("Form", "No OSF to OSF1 Transition Wavelength (um.):"))
        self.sequence_monochromator_g2g3_label.setText(_translate("Form", "G2 to G3 Transition Wavelength (um.):"))
        self.sequence_monochromator_g1g2_label.setText(_translate("Form", "G1 to G2 Transition Wavelength (um.):"))
        self.sequence_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.sequence_monochromator_osf1osf2_label.setText(_translate("Form", "OSF1 to OSF2 Transition Wavelength (um.):"))
        self.sequence_lockin_label.setText(_translate("Form", "Lock-In:"))
        self.sequence_lockin_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.auto_window_select_combobox_1.setItemText(0, _translate("Form", "Series Construction and Control Window"))
        self.auto_window_select_combobox_1.setItemText(1, _translate("Form", "Sequence Parameters Window"))
        self.sequence_monochromator_label.setText(_translate("Form", "Monochromator:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
