# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS260Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 484)
        self.gridLayout_12 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.start_scan_series_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_scan_series_button.sizePolicy().hasHeightForWidth())
        self.start_scan_series_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_scan_series_button.setFont(font)
        self.start_scan_series_button.setObjectName("start_scan_series_button")
        self.gridLayout_5.addWidget(self.start_scan_series_button, 0, 0, 1, 1)
        self.abort_scan_series_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort_scan_series_button.sizePolicy().hasHeightForWidth())
        self.abort_scan_series_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.abort_scan_series_button.setFont(font)
        self.abort_scan_series_button.setObjectName("abort_scan_series_button")
        self.gridLayout_5.addWidget(self.abort_scan_series_button, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.grating_select_cbox = QtWidgets.QComboBox(self.tab)
        self.grating_select_cbox.setObjectName("grating_select_cbox")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.gridLayout.addWidget(self.grating_select_cbox, 3, 0, 1, 1)
        self.grating_select_label = QtWidgets.QLabel(self.tab)
        self.grating_select_label.setObjectName("grating_select_label")
        self.gridLayout.addWidget(self.grating_select_label, 2, 0, 1, 1)
        self.osf_select_label = QtWidgets.QLabel(self.tab)
        self.osf_select_label.setObjectName("osf_select_label")
        self.gridLayout.addWidget(self.osf_select_label, 2, 1, 1, 1)
        self.osf_select_cbox = QtWidgets.QComboBox(self.tab)
        self.osf_select_cbox.setObjectName("osf_select_cbox")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.gridLayout.addWidget(self.osf_select_cbox, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequence_wave_end_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_end_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_end_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_end_ledit.setPlaceholderText("")
        self.sequence_wave_end_ledit.setObjectName("sequence_wave_end_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_end_ledit, 1, 1, 1, 1)
        self.sequence_end_wave_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_end_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_end_wave_label.setSizePolicy(sizePolicy)
        self.sequence_end_wave_label.setObjectName("sequence_end_wave_label")
        self.gridLayout_2.addWidget(self.sequence_end_wave_label, 0, 1, 1, 1)
        self.sequence_wave_step_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_step_ledit.setObjectName("sequence_wave_step_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_step_ledit, 1, 2, 1, 1)
        self.sequence_wave_step_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_label.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_label.setSizePolicy(sizePolicy)
        self.sequence_wave_step_label.setObjectName("sequence_wave_step_label")
        self.gridLayout_2.addWidget(self.sequence_wave_step_label, 0, 2, 1, 1)
        self.sequence_wave_start_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_start_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_start_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_start_ledit.setPlaceholderText("")
        self.sequence_wave_start_ledit.setObjectName("sequence_wave_start_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_start_ledit, 1, 0, 1, 1)
        self.sequence_start_wave_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_start_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_start_wave_label.setSizePolicy(sizePolicy)
        self.sequence_start_wave_label.setObjectName("sequence_start_wave_label")
        self.gridLayout_2.addWidget(self.sequence_start_wave_label, 0, 0, 1, 1)
        self.sequence_measure_int_ledit = QtWidgets.QLineEdit(self.tab)
        self.sequence_measure_int_ledit.setPlaceholderText("")
        self.sequence_measure_int_ledit.setObjectName("sequence_measure_int_ledit")
        self.gridLayout_2.addWidget(self.sequence_measure_int_ledit, 1, 3, 1, 1)
        self.sequence_measure_int_label = QtWidgets.QLabel(self.tab)
        self.sequence_measure_int_label.setObjectName("sequence_measure_int_label")
        self.gridLayout_2.addWidget(self.sequence_measure_int_label, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.remove_sequence_button = QtWidgets.QPushButton(self.tab)
        self.remove_sequence_button.setObjectName("remove_sequence_button")
        self.gridLayout_4.addWidget(self.remove_sequence_button, 5, 0, 1, 1)
        self.add_new_sequence_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_new_sequence_button.sizePolicy().hasHeightForWidth())
        self.add_new_sequence_button.setSizePolicy(sizePolicy)
        self.add_new_sequence_button.setObjectName("add_new_sequence_button")
        self.gridLayout_4.addWidget(self.add_new_sequence_button, 3, 0, 1, 1)
        self.sequence_name_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_label.sizePolicy().hasHeightForWidth())
        self.sequence_name_label.setSizePolicy(sizePolicy)
        self.sequence_name_label.setObjectName("sequence_name_label")
        self.gridLayout_4.addWidget(self.sequence_name_label, 0, 0, 1, 1)
        self.edit_sequence_button = QtWidgets.QPushButton(self.tab)
        self.edit_sequence_button.setObjectName("edit_sequence_button")
        self.gridLayout_4.addWidget(self.edit_sequence_button, 4, 0, 1, 1)
        self.series = QtWidgets.QListWidget(self.tab)
        self.series.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.series.setObjectName("series")
        self.gridLayout_4.addWidget(self.series, 0, 1, 6, 1)
        self.sequence_name_ledit = QtWidgets.QLineEdit(self.tab)
        self.sequence_name_ledit.setPlaceholderText("")
        self.sequence_name_ledit.setObjectName("sequence_name_ledit")
        self.gridLayout_4.addWidget(self.sequence_name_ledit, 1, 0, 1, 1)
        self.power_measure_checkbox = QtWidgets.QCheckBox(self.tab)
        self.power_measure_checkbox.setObjectName("power_measure_checkbox")
        self.gridLayout_4.addWidget(self.power_measure_checkbox, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.abort_manual_button = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort_manual_button.sizePolicy().hasHeightForWidth())
        self.abort_manual_button.setSizePolicy(sizePolicy)
        self.abort_manual_button.setObjectName("abort_manual_button")
        self.gridLayout_14.addWidget(self.abort_manual_button, 2, 0, 1, 1)
        self.set_parameters_button = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_parameters_button.sizePolicy().hasHeightForWidth())
        self.set_parameters_button.setSizePolicy(sizePolicy)
        self.set_parameters_button.setObjectName("set_parameters_button")
        self.gridLayout_14.addWidget(self.set_parameters_button, 0, 0, 1, 1)
        self.power_measure_button = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_measure_button.sizePolicy().hasHeightForWidth())
        self.power_measure_button.setSizePolicy(sizePolicy)
        self.power_measure_button.setObjectName("power_measure_button")
        self.gridLayout_14.addWidget(self.power_measure_button, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 1, 0, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.wavelength_current_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.wavelength_current_ledit.setEnabled(False)
        self.wavelength_current_ledit.setText("")
        self.wavelength_current_ledit.setObjectName("wavelength_current_ledit")
        self.gridLayout_7.addWidget(self.wavelength_current_ledit, 2, 0, 1, 1)
        self.osf_current_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.osf_current_ledit.setEnabled(False)
        self.osf_current_ledit.setObjectName("osf_current_ledit")
        self.gridLayout_7.addWidget(self.osf_current_ledit, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 7, 0, 1, 1)
        self.grating_current_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.grating_current_ledit.setEnabled(False)
        self.grating_current_ledit.setObjectName("grating_current_ledit")
        self.gridLayout_7.addWidget(self.grating_current_ledit, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 5, 0, 1, 1)
        self.shutter_current_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.shutter_current_ledit.setEnabled(False)
        self.shutter_current_ledit.setObjectName("shutter_current_ledit")
        self.gridLayout_7.addWidget(self.shutter_current_ledit, 8, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 7, 0, 1, 1)
        self.wavelength_new_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.wavelength_new_ledit.setObjectName("wavelength_new_ledit")
        self.gridLayout_8.addWidget(self.wavelength_new_ledit, 2, 0, 1, 1)
        self.osf_new_cbox = QtWidgets.QComboBox(self.tab_2)
        self.osf_new_cbox.setEditable(True)
        self.osf_new_cbox.setObjectName("osf_new_cbox")
        self.osf_new_cbox.addItem("")
        self.osf_new_cbox.addItem("")
        self.osf_new_cbox.addItem("")
        self.osf_new_cbox.addItem("")
        self.gridLayout_8.addWidget(self.osf_new_cbox, 4, 0, 1, 1)
        self.grating_new_cbox = QtWidgets.QComboBox(self.tab_2)
        self.grating_new_cbox.setEditable(True)
        self.grating_new_cbox.setObjectName("grating_new_cbox")
        self.grating_new_cbox.addItem("")
        self.grating_new_cbox.addItem("")
        self.grating_new_cbox.addItem("")
        self.gridLayout_8.addWidget(self.grating_new_cbox, 6, 0, 1, 1)
        self.shutter_new_cbox = QtWidgets.QComboBox(self.tab_2)
        self.shutter_new_cbox.setEditable(True)
        self.shutter_new_cbox.setObjectName("shutter_new_cbox")
        self.shutter_new_cbox.addItem("")
        self.shutter_new_cbox.addItem("")
        self.gridLayout_8.addWidget(self.shutter_new_cbox, 8, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 5, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.grating_select_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_scan_series_button.setText(_translate("Dialog", "Start Scan Series"))
        self.abort_scan_series_button.setText(_translate("Dialog", "Abort Scan Series"))
        self.grating_select_cbox.setItemText(0, _translate("Dialog", "Grating 1 (G1)"))
        self.grating_select_cbox.setItemText(1, _translate("Dialog", "Grating 2 (G2)"))
        self.grating_select_cbox.setItemText(2, _translate("Dialog", "Grating 3 (G3)"))
        self.grating_select_label.setText(_translate("Dialog", "Sequence Grating Selection:"))
        self.osf_select_label.setText(_translate("Dialog", "Sequence Order Sort Filter Selection:"))
        self.osf_select_cbox.setItemText(0, _translate("Dialog", "OSF1"))
        self.osf_select_cbox.setItemText(1, _translate("Dialog", "OSF2"))
        self.osf_select_cbox.setItemText(2, _translate("Dialog", "OSF3"))
        self.osf_select_cbox.setItemText(3, _translate("Dialog", "OSF4"))
        self.sequence_wave_end_ledit.setText(_translate("Dialog", "5.0"))
        self.sequence_end_wave_label.setText(_translate("Dialog", "Sequence End Wavelength (um.):"))
        self.sequence_wave_step_ledit.setText(_translate("Dialog", "1.0"))
        self.sequence_wave_step_ledit.setPlaceholderText(_translate("Dialog", "1.0"))
        self.sequence_wave_step_label.setText(_translate("Dialog", "Sequence Wavelength Step (nm.):"))
        self.sequence_wave_start_ledit.setText(_translate("Dialog", "0.75"))
        self.sequence_start_wave_label.setText(_translate("Dialog", "Sequence Start Wavelength (um.):"))
        self.sequence_measure_int_ledit.setText(_translate("Dialog", "5.0"))
        self.sequence_measure_int_label.setText(_translate("Dialog", "Sequence Measure Interval:"))
        self.remove_sequence_button.setText(_translate("Dialog", "Remove Sequence from Scan Series"))
        self.add_new_sequence_button.setText(_translate("Dialog", "Add New Sequence To Scan Series"))
        self.sequence_name_label.setText(_translate("Dialog", "Sequence Name:"))
        self.edit_sequence_button.setText(_translate("Dialog", "Edit Sequence"))
        self.sequence_name_ledit.setText(_translate("Dialog", "Seq1"))
        self.power_measure_checkbox.setText(_translate("Dialog", "Run power measurements over sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Scan"))
        self.abort_manual_button.setText(_translate("Dialog", "Abort"))
        self.set_parameters_button.setText(_translate("Dialog", "Set Parameters"))
        self.power_measure_button.setText(_translate("Dialog", "Run Power Measurement"))
        self.label_38.setText(_translate("Dialog", "Wavelength (um.):"))
        self.label_41.setText(_translate("Dialog", "Shutter:"))
        self.label_37.setText(_translate("Dialog", "Current Parameters:"))
        self.label_40.setText(_translate("Dialog", "Grating:"))
        self.label_39.setText(_translate("Dialog", "Filter:"))
        self.label_44.setText(_translate("Dialog", "Filter:"))
        self.label_42.setText(_translate("Dialog", "New Parameters:"))
        self.label_46.setText(_translate("Dialog", "Shutter:"))
        self.osf_new_cbox.setItemText(0, _translate("Dialog", "OSF1"))
        self.osf_new_cbox.setItemText(1, _translate("Dialog", "OSF2"))
        self.osf_new_cbox.setItemText(2, _translate("Dialog", "OSF3"))
        self.osf_new_cbox.setItemText(3, _translate("Dialog", "OSF4"))
        self.grating_new_cbox.setItemText(0, _translate("Dialog", "G1"))
        self.grating_new_cbox.setItemText(1, _translate("Dialog", "G2"))
        self.grating_new_cbox.setItemText(2, _translate("Dialog", "G3"))
        self.shutter_new_cbox.setItemText(0, _translate("Dialog", "Open"))
        self.shutter_new_cbox.setItemText(1, _translate("Dialog", "Close"))
        self.label_43.setText(_translate("Dialog", "Wavelength (um.):"))
        self.label_45.setText(_translate("Dialog", "Grating:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
