# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS260Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 597)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength.sizePolicy().hasHeightForWidth())
        self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength.setSizePolicy(sizePolicy)
        self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength.setReadOnly(False)
        self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength.setObjectName("lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength")
        self.gridLayout.addWidget(self.lineedit_base_CurrentMonochromatorParams_passive_CurrentWavelength, 3, 0, 1, 1)
        self.lineedit_base_NewMonochromatorParams_passive_NewWavelength = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_NewMonochromatorParams_passive_NewWavelength.sizePolicy().hasHeightForWidth())
        self.lineedit_base_NewMonochromatorParams_passive_NewWavelength.setSizePolicy(sizePolicy)
        self.lineedit_base_NewMonochromatorParams_passive_NewWavelength.setObjectName("lineedit_base_NewMonochromatorParams_passive_NewWavelength")
        self.gridLayout.addWidget(self.lineedit_base_NewMonochromatorParams_passive_NewWavelength, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setEnabled(False)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setObjectName("combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter, 5, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter = QtWidgets.QComboBox(Form)
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setObjectName("combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter")
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.sizePolicy().hasHeightForWidth())
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setSizePolicy(sizePolicy)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setObjectName("combobox_base_CurrentMonochromatorParams_passive_CurrentGrating")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating, 7, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_NewGrating = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewMonochromatorParams_passive_NewGrating.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setSizePolicy(sizePolicy)
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setObjectName("combobox_base_NewMonochromatorParams_passive_NewGrating")
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_NewGrating, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.sizePolicy().hasHeightForWidth())
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.setSizePolicy(sizePolicy)
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.setObjectName("combobox_base_CurrentMonochromatorParams_passive_CurrentShutter")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter, 9, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_NewShutter = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewMonochromatorParams_passive_NewShutter.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.setSizePolicy(sizePolicy)
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.setObjectName("combobox_base_NewMonochromatorParams_passive_NewShutter")
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_NewShutter, 9, 1, 1, 1)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_base_NewMonochromatorParams_getter_NewMonoButton.sizePolicy().hasHeightForWidth())
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setFont(font)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setObjectName("button_base_NewMonochromatorParams_getter_NewMonoButton")
        self.gridLayout.addWidget(self.button_base_NewMonochromatorParams_getter_NewMonoButton, 10, 0, 1, 2)

        self.retranslateUi(Form)
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monochromator"))
        self.label.setText(_translate("Form", "Monochromator:"))
        self.label_4.setText(_translate("Form", "Current Parameters:"))
        self.label_3.setText(_translate("Form", "New Parameters:"))
        self.label_10.setText(_translate("Form", "Wavelength (um.):"))
        self.label_11.setText(_translate("Form", "Wavelength (um.):"))
        self.label_2.setText(_translate("Form", "Filter:"))
        self.label_7.setText(_translate("Form", "Filter:"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setItemText(0, _translate("Form", "No OSF"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setItemText(1, _translate("Form", "OSF1"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setItemText(2, _translate("Form", "OSF2"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentOrderSortFilter.setItemText(3, _translate("Form", "OSF3"))
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setItemText(0, _translate("Form", "No OSF"))
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setItemText(1, _translate("Form", "Auto"))
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setItemText(2, _translate("Form", "OSF1"))
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setItemText(3, _translate("Form", "OSF2"))
        self.combobox_base_NewMonochromatorParams_passive_NewOrderSortFilter.setItemText(4, _translate("Form", "OSF3"))
        self.label_5.setText(_translate("Form", "Grating:"))
        self.label_6.setText(_translate("Form", "Grating:"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setItemText(0, _translate("Form", "G1"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setItemText(1, _translate("Form", "G2"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentGrating.setItemText(2, _translate("Form", "G3"))
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setItemText(0, _translate("Form", "Auto"))
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setItemText(1, _translate("Form", "G1"))
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setItemText(2, _translate("Form", "G2"))
        self.combobox_base_NewMonochromatorParams_passive_NewGrating.setItemText(3, _translate("Form", "G3"))
        self.label_8.setText(_translate("Form", "Shutter:"))
        self.label_9.setText(_translate("Form", "Shutter:"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_base_CurrentMonochromatorParams_passive_CurrentShutter.setItemText(1, _translate("Form", "Close"))
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_base_NewMonochromatorParams_passive_NewShutter.setItemText(1, _translate("Form", "Close"))
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setText(_translate("Form", "-> Press Here to Set New Monochromator Parameters <-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

