# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 501)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.manual_lockin_measurementstorage_label = QtWidgets.QLabel(Form)
        self.manual_lockin_measurementstorage_label.setObjectName("manual_lockin_measurementstorage_label")
        self.gridLayout.addWidget(self.manual_lockin_measurementstorage_label, 23, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 15, 0, 1, 1)
        self.manual_monochromator_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.manual_monochromator_label.setFont(font)
        self.manual_monochromator_label.setObjectName("manual_monochromator_label")
        self.gridLayout.addWidget(self.manual_monochromator_label, 0, 0, 1, 1)
        self.manual_monochromator_shutter_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_combobox.setObjectName("manual_monochromator_shutter_combobox")
        self.manual_monochromator_shutter_combobox.addItem("")
        self.manual_monochromator_shutter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_shutter_combobox, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 13, 1, 1, 1)
        self.manual_monochromator_abort_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_abort_button.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_abort_button.setSizePolicy(sizePolicy)
        self.manual_monochromator_abort_button.setObjectName("manual_monochromator_abort_button")
        self.gridLayout.addWidget(self.manual_monochromator_abort_button, 6, 1, 3, 1)
        self.manual_monochromator_wavelength_ledit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_ledit.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_ledit.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_ledit.setObjectName("manual_monochromator_wavelength_ledit")
        self.gridLayout.addWidget(self.manual_monochromator_wavelength_ledit, 2, 0, 1, 1)
        self.manual_lockin_timeconstantunit_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_timeconstantunit_cbox.setObjectName("manual_lockin_timeconstantunit_cbox")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantunit_cbox, 16, 1, 1, 1)
        self.manual_lockin_sensitivitymultiplier_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_sensitivitymultiplier_cbox.setObjectName("manual_lockin_sensitivitymultiplier_cbox")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivitymultiplier_cbox, 14, 0, 1, 1)
        self.manual_monochromator_filter_combobox = QtWidgets.QComboBox(Form)
        self.manual_monochromator_filter_combobox.setObjectName("manual_monochromator_filter_combobox")
        self.manual_monochromator_filter_combobox.addItem("")
        self.manual_monochromator_filter_combobox.addItem("")
        self.manual_monochromator_filter_combobox.addItem("")
        self.manual_monochromator_filter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_filter_combobox, 4, 0, 1, 1)
        self.manual_lockin_measurementstorage_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_measurementstorage_ledit.setObjectName("manual_lockin_measurementstorage_ledit")
        self.gridLayout.addWidget(self.manual_lockin_measurementstorage_ledit, 24, 0, 1, 2)
        self.manual_lockin_timeconstant_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_timeconstant_label.setFont(font)
        self.manual_lockin_timeconstant_label.setObjectName("manual_lockin_timeconstant_label")
        self.gridLayout.addWidget(self.manual_lockin_timeconstant_label, 10, 1, 1, 1)
        self.manual_lockin_sampletime_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_sampletime_ledit.setObjectName("manual_lockin_sampletime_ledit")
        self.gridLayout.addWidget(self.manual_lockin_sampletime_ledit, 21, 1, 1, 1)
        self.manual_lockin_samplerate_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_samplerate_combobox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_samplerate_combobox.setSizePolicy(sizePolicy)
        self.manual_lockin_samplerate_combobox.setObjectName("manual_lockin_samplerate_combobox")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_samplerate_combobox, 21, 0, 1, 1)
        self.manual_lockin_sensitivity_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivity_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_sensitivity_label.setFont(font)
        self.manual_lockin_sensitivity_label.setObjectName("manual_lockin_sensitivity_label")
        self.gridLayout.addWidget(self.manual_lockin_sensitivity_label, 10, 0, 1, 1)
        self.manual_lockin_startmeasurement_button = QtWidgets.QPushButton(Form)
        self.manual_lockin_startmeasurement_button.setObjectName("manual_lockin_startmeasurement_button")
        self.gridLayout.addWidget(self.manual_lockin_startmeasurement_button, 25, 0, 1, 2)
        self.manual_monochromator_filter_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_filter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_filter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_filter_label.setObjectName("manual_monochromator_filter_label")
        self.gridLayout.addWidget(self.manual_monochromator_filter_label, 3, 0, 1, 1)
        self.manual_lockin_timeconstantvalue_cbox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_timeconstantvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_timeconstantvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_timeconstantvalue_cbox.setObjectName("manual_lockin_timeconstantvalue_cbox")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantvalue_cbox, 12, 1, 1, 1)
        self.manual_monochromator_shutter_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_label.setObjectName("manual_monochromator_shutter_label")
        self.gridLayout.addWidget(self.manual_monochromator_shutter_label, 7, 0, 1, 1)
        self.manual_lockin_sampletime_label = QtWidgets.QLabel(Form)
        self.manual_lockin_sampletime_label.setObjectName("manual_lockin_sampletime_label")
        self.gridLayout.addWidget(self.manual_lockin_sampletime_label, 20, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 13, 0, 1, 1)
        self.manual_lockin_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_label.setFont(font)
        self.manual_lockin_label.setObjectName("manual_lockin_label")
        self.gridLayout.addWidget(self.manual_lockin_label, 9, 0, 1, 1)
        self.manual_monochromator_grating_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_combobox.setObjectName("manual_monochromator_grating_combobox")
        self.manual_monochromator_grating_combobox.addItem("")
        self.manual_monochromator_grating_combobox.addItem("")
        self.manual_monochromator_grating_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_grating_combobox, 6, 0, 1, 1)
        self.manual_monochromator_setparams_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_setparams_button.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_setparams_button.setSizePolicy(sizePolicy)
        self.manual_monochromator_setparams_button.setObjectName("manual_monochromator_setparams_button")
        self.gridLayout.addWidget(self.manual_monochromator_setparams_button, 2, 1, 3, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 1, 1, 1)
        self.manual_monochromator_grating_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_label.setObjectName("manual_monochromator_grating_label")
        self.gridLayout.addWidget(self.manual_monochromator_grating_label, 5, 0, 1, 1)
        self.manual_lockin_sensitivityunit_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_sensitivityunit_cbox.setObjectName("manual_lockin_sensitivityunit_cbox")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivityunit_cbox, 16, 0, 1, 1)
        self.manual_lockin_timeconstantmultiplier_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_timeconstantmultiplier_cbox.setObjectName("manual_lockin_timeconstantmultiplier_cbox")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantmultiplier_cbox, 14, 1, 1, 1)
        self.manual_lockin_samplerate_label = QtWidgets.QLabel(Form)
        self.manual_lockin_samplerate_label.setObjectName("manual_lockin_samplerate_label")
        self.gridLayout.addWidget(self.manual_lockin_samplerate_label, 20, 0, 1, 1)
        self.manual_lockin_sensitivityvalue_cbox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivityvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivityvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_sensitivityvalue_cbox.setObjectName("manual_lockin_sensitivityvalue_cbox")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivityvalue_cbox, 12, 0, 1, 1)
        self.manual_monochromator_wavelength_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_label.setObjectName("manual_monochromator_wavelength_label")
        self.gridLayout.addWidget(self.manual_monochromator_wavelength_label, 1, 0, 1, 1)
        self.manual_lockin_setparams_button = QtWidgets.QPushButton(Form)
        self.manual_lockin_setparams_button.setObjectName("manual_lockin_setparams_button")
        self.gridLayout.addWidget(self.manual_lockin_setparams_button, 17, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.manual_lockin_measurementstorage_label.setText(_translate("Form", "Measurement Storage Path:"))
        self.label_4.setText(_translate("Form", "Value:"))
        self.label_3.setText(_translate("Form", "Units:"))
        self.manual_monochromator_label.setText(_translate("Form", "Monochromator:"))
        self.manual_monochromator_shutter_combobox.setItemText(0, _translate("Form", "Open"))
        self.manual_monochromator_shutter_combobox.setItemText(1, _translate("Form", "Close"))
        self.label.setText(_translate("Form", "Value:"))
        self.label_5.setText(_translate("Form", "Multiplier:"))
        self.manual_monochromator_abort_button.setText(_translate("Form", "Abort"))
        self.manual_lockin_timeconstantunit_cbox.setItemText(0, _translate("Form", "ks."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(1, _translate("Form", "s."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(2, _translate("Form", "ms."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(3, _translate("Form", "us."))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.manual_monochromator_filter_combobox.setItemText(0, _translate("Form", "No OSF"))
        self.manual_monochromator_filter_combobox.setItemText(1, _translate("Form", "OSF1"))
        self.manual_monochromator_filter_combobox.setItemText(2, _translate("Form", "OSF2"))
        self.manual_monochromator_filter_combobox.setItemText(3, _translate("Form", "OSF3"))
        self.manual_lockin_timeconstant_label.setText(_translate("Form", "Time-Constant:"))
        self.manual_lockin_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.manual_lockin_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.manual_lockin_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.manual_lockin_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.manual_lockin_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.manual_lockin_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.manual_lockin_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.manual_lockin_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.manual_lockin_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.manual_lockin_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.manual_lockin_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.manual_lockin_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.manual_lockin_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.manual_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity:"))
        self.manual_lockin_startmeasurement_button.setText(_translate("Form", "Start Measurement"))
        self.manual_monochromator_filter_label.setText(_translate("Form", "Filter:"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(1, _translate("Form", "3"))
        self.manual_monochromator_shutter_label.setText(_translate("Form", "Shutter:"))
        self.manual_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.label_2.setText(_translate("Form", "Multiplier:"))
        self.manual_lockin_label.setText(_translate("Form", "Lock-In:"))
        self.manual_monochromator_grating_combobox.setItemText(0, _translate("Form", "G1"))
        self.manual_monochromator_grating_combobox.setItemText(1, _translate("Form", "G2"))
        self.manual_monochromator_grating_combobox.setItemText(2, _translate("Form", "G3"))
        self.manual_monochromator_setparams_button.setText(_translate("Form", "Set Parameters"))
        self.label_6.setText(_translate("Form", "Units:"))
        self.manual_monochromator_grating_label.setText(_translate("Form", "Grating:"))
        self.manual_lockin_sensitivityunit_cbox.setItemText(0, _translate("Form", "V."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(1, _translate("Form", "mV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(2, _translate("Form", "uV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(3, _translate("Form", "nV."))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.manual_lockin_samplerate_label.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(1, _translate("Form", "2"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(2, _translate("Form", "5"))
        self.manual_monochromator_wavelength_label.setText(_translate("Form", "Wavelength (um.):"))
        self.manual_lockin_setparams_button.setText(_translate("Form", "Set Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
