# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualWindowDialog2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1246, 1483)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.MonochromatorControl = QtWidgets.QWidget()
        self.MonochromatorControl.setObjectName("MonochromatorControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MonochromatorControl)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.manual_monochromator_shutter_label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_label.setObjectName("manual_monochromator_shutter_label")
        self.gridLayout_2.addWidget(self.manual_monochromator_shutter_label, 23, 2, 1, 1)
        self.manual_monochromator_currentfilter_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        self.manual_monochromator_currentfilter_combobox.setObjectName("manual_monochromator_currentfilter_combobox")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_currentfilter_combobox, 18, 0, 1, 2)
        self.manual_monochromator_newfilter_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        self.manual_monochromator_newfilter_combobox.setObjectName("manual_monochromator_newfilter_combobox")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_newfilter_combobox, 18, 2, 1, 2)
        self.manual_monochromator_newgrating_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newgrating_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newgrating_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_newgrating_combobox.setObjectName("manual_monochromator_newgrating_combobox")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_newgrating_combobox, 21, 2, 1, 2)
        self.manual_monochromator_wavelength_label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_label.setObjectName("manual_monochromator_wavelength_label")
        self.gridLayout_2.addWidget(self.manual_monochromator_wavelength_label, 12, 2, 1, 1)
        self.manual_monochromator_grating_label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_label.setObjectName("manual_monochromator_grating_label")
        self.gridLayout_2.addWidget(self.manual_monochromator_grating_label, 20, 2, 1, 1)
        self.manual_monochromator_filter_label_2 = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_filter_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_filter_label_2.setSizePolicy(sizePolicy)
        self.manual_monochromator_filter_label_2.setObjectName("manual_monochromator_filter_label_2")
        self.gridLayout_2.addWidget(self.manual_monochromator_filter_label_2, 17, 0, 1, 1)
        self.manual_monochromator_label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manual_monochromator_label.setFont(font)
        self.manual_monochromator_label.setObjectName("manual_monochromator_label")
        self.gridLayout_2.addWidget(self.manual_monochromator_label, 0, 0, 1, 2)
        self.manual_monochromator_grating_label_2 = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_label_2.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_label_2.setObjectName("manual_monochromator_grating_label_2")
        self.gridLayout_2.addWidget(self.manual_monochromator_grating_label_2, 20, 0, 1, 1)
        self.manual_monochromator_shutter_label_2 = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_label_2.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_label_2.setObjectName("manual_monochromator_shutter_label_2")
        self.gridLayout_2.addWidget(self.manual_monochromator_shutter_label_2, 23, 0, 1, 1)
        self.manual_monochromator_currentshutter_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentshutter_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentshutter_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentshutter_combobox.setObjectName("manual_monochromator_currentshutter_combobox")
        self.manual_monochromator_currentshutter_combobox.addItem("")
        self.manual_monochromator_currentshutter_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_currentshutter_combobox, 24, 0, 1, 2)
        self.manual_monochromator_filter_label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_filter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_filter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_filter_label.setObjectName("manual_monochromator_filter_label")
        self.gridLayout_2.addWidget(self.manual_monochromator_filter_label, 17, 2, 1, 1)
        self.manual_monochromator_currentgrating_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentgrating_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentgrating_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentgrating_combobox.setObjectName("manual_monochromator_currentgrating_combobox")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_currentgrating_combobox, 21, 0, 1, 2)
        self.manual_monochromator_wavelength_label_2 = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_label_2.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_label_2.setObjectName("manual_monochromator_wavelength_label_2")
        self.gridLayout_2.addWidget(self.manual_monochromator_wavelength_label_2, 12, 0, 1, 1)
        self.manual_monochromator_newwavelength_ledit = QtWidgets.QLineEdit(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newwavelength_ledit.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newwavelength_ledit.setSizePolicy(sizePolicy)
        self.manual_monochromator_newwavelength_ledit.setObjectName("manual_monochromator_newwavelength_ledit")
        self.gridLayout_2.addWidget(self.manual_monochromator_newwavelength_ledit, 15, 2, 1, 2)
        self.manual_monochromator_setparams_button = QtWidgets.QPushButton(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_setparams_button.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_setparams_button.setSizePolicy(sizePolicy)
        self.manual_monochromator_setparams_button.setObjectName("manual_monochromator_setparams_button")
        self.gridLayout_2.addWidget(self.manual_monochromator_setparams_button, 25, 0, 1, 4)
        self.manual_monochromator_newshutter_combobox = QtWidgets.QComboBox(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newshutter_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newshutter_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_newshutter_combobox.setObjectName("manual_monochromator_newshutter_combobox")
        self.manual_monochromator_newshutter_combobox.addItem("")
        self.manual_monochromator_newshutter_combobox.addItem("")
        self.gridLayout_2.addWidget(self.manual_monochromator_newshutter_combobox, 24, 2, 1, 2)
        self.manual_monochromator_currentwavelength_ledit = QtWidgets.QLineEdit(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentwavelength_ledit.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentwavelength_ledit.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentwavelength_ledit.setObjectName("manual_monochromator_currentwavelength_ledit")
        self.gridLayout_2.addWidget(self.manual_monochromator_currentwavelength_ledit, 15, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 11, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.MonochromatorControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 11, 2, 1, 1)
        self.stackedWidget.addWidget(self.MonochromatorControl)
        self.LockInControl = QtWidgets.QWidget()
        self.LockInControl.setObjectName("LockInControl")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.LockInControl)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.manual_lockin_label = QtWidgets.QLabel(self.LockInControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_label.setFont(font)
        self.manual_lockin_label.setObjectName("manual_lockin_label")
        self.gridLayout_3.addWidget(self.manual_lockin_label, 0, 0, 1, 1)
        self.manual_lockin_sensitivityvalue_cbox = QtWidgets.QComboBox(self.LockInControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivityvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivityvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_sensitivityvalue_cbox.setObjectName("manual_lockin_sensitivityvalue_cbox")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivityvalue_cbox, 8, 0, 1, 1)
        self.manual_lockin_measurementstorage_label = QtWidgets.QLabel(self.LockInControl)
        self.manual_lockin_measurementstorage_label.setObjectName("manual_lockin_measurementstorage_label")
        self.gridLayout_3.addWidget(self.manual_lockin_measurementstorage_label, 18, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.LockInControl)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 9, 1, 1, 1)
        self.manual_lockin_samplerate_combobox = QtWidgets.QComboBox(self.LockInControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_samplerate_combobox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_samplerate_combobox.setSizePolicy(sizePolicy)
        self.manual_lockin_samplerate_combobox.setObjectName("manual_lockin_samplerate_combobox")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_samplerate_combobox, 17, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.LockInControl)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 9, 0, 1, 1)
        self.manual_lockin_timeconstantunit_cbox = QtWidgets.QComboBox(self.LockInControl)
        self.manual_lockin_timeconstantunit_cbox.setObjectName("manual_lockin_timeconstantunit_cbox")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstantunit_cbox, 12, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.LockInControl)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.LockInControl)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 11, 0, 1, 1)
        self.manual_lockin_timeconstantmultiplier_cbox = QtWidgets.QComboBox(self.LockInControl)
        self.manual_lockin_timeconstantmultiplier_cbox.setObjectName("manual_lockin_timeconstantmultiplier_cbox")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstantmultiplier_cbox, 10, 1, 1, 1)
        self.manual_lockin_sampletime_label = QtWidgets.QLabel(self.LockInControl)
        self.manual_lockin_sampletime_label.setObjectName("manual_lockin_sampletime_label")
        self.gridLayout_3.addWidget(self.manual_lockin_sampletime_label, 16, 1, 1, 1)
        self.manual_lockin_measurementstorage_ledit = QtWidgets.QLineEdit(self.LockInControl)
        self.manual_lockin_measurementstorage_ledit.setObjectName("manual_lockin_measurementstorage_ledit")
        self.gridLayout_3.addWidget(self.manual_lockin_measurementstorage_ledit, 19, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.LockInControl)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 14, 0, 1, 2)
        self.manual_lockin_sensitivity_ledit = QtWidgets.QLineEdit(self.LockInControl)
        self.manual_lockin_sensitivity_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.manual_lockin_sensitivity_ledit.setFont(font)
        self.manual_lockin_sensitivity_ledit.setReadOnly(False)
        self.manual_lockin_sensitivity_ledit.setClearButtonEnabled(False)
        self.manual_lockin_sensitivity_ledit.setObjectName("manual_lockin_sensitivity_ledit")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivity_ledit, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.manual_lockin_timeconstantvalue_cbox = QtWidgets.QComboBox(self.LockInControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_timeconstantvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_timeconstantvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_timeconstantvalue_cbox.setObjectName("manual_lockin_timeconstantvalue_cbox")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstantvalue_cbox, 8, 1, 1, 1)
        self.manual_lockin_timeconstant_label = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_timeconstant_label.setFont(font)
        self.manual_lockin_timeconstant_label.setObjectName("manual_lockin_timeconstant_label")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstant_label, 6, 1, 1, 1)
        self.manual_lockin_samplerate_label = QtWidgets.QLabel(self.LockInControl)
        self.manual_lockin_samplerate_label.setObjectName("manual_lockin_samplerate_label")
        self.gridLayout_3.addWidget(self.manual_lockin_samplerate_label, 16, 0, 1, 1)
        self.manual_lockin_sensitivityunit_cbox = QtWidgets.QComboBox(self.LockInControl)
        self.manual_lockin_sensitivityunit_cbox.setObjectName("manual_lockin_sensitivityunit_cbox")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivityunit_cbox, 12, 0, 1, 1)
        self.manual_lockin_sampletime_ledit = QtWidgets.QLineEdit(self.LockInControl)
        self.manual_lockin_sampletime_ledit.setObjectName("manual_lockin_sampletime_ledit")
        self.gridLayout_3.addWidget(self.manual_lockin_sampletime_ledit, 17, 1, 1, 1)
        self.manual_lockin_timeconstant_ledit = QtWidgets.QLineEdit(self.LockInControl)
        self.manual_lockin_timeconstant_ledit.setEnabled(False)
        self.manual_lockin_timeconstant_ledit.setReadOnly(False)
        self.manual_lockin_timeconstant_ledit.setObjectName("manual_lockin_timeconstant_ledit")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstant_ledit, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.LockInControl)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 4, 0, 1, 2)
        self.manual_lockin_startmeasurement_button = QtWidgets.QPushButton(self.LockInControl)
        self.manual_lockin_startmeasurement_button.setObjectName("manual_lockin_startmeasurement_button")
        self.gridLayout_3.addWidget(self.manual_lockin_startmeasurement_button, 20, 0, 1, 2)
        self.manual_lockin_sensitivity_label = QtWidgets.QLabel(self.LockInControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivity_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_sensitivity_label.setFont(font)
        self.manual_lockin_sensitivity_label.setObjectName("manual_lockin_sensitivity_label")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivity_label, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.manual_lockin_sensitivitymultiplier_cbox = QtWidgets.QComboBox(self.LockInControl)
        self.manual_lockin_sensitivitymultiplier_cbox.setObjectName("manual_lockin_sensitivitymultiplier_cbox")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivitymultiplier_cbox, 10, 0, 1, 1)
        self.manual_lockin_setparams_button = QtWidgets.QPushButton(self.LockInControl)
        self.manual_lockin_setparams_button.setObjectName("manual_lockin_setparams_button")
        self.gridLayout_3.addWidget(self.manual_lockin_setparams_button, 13, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.LockInControl)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.LockInControl)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.LockInControl)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 15, 0, 1, 1)
        self.stackedWidget.addWidget(self.LockInControl)
        self.LabJackControl = QtWidgets.QWidget()
        self.LabJackControl.setObjectName("LabJackControl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.LabJackControl)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.manual_labjack_dio8state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio8state_check.setObjectName("manual_labjack_dio8state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio8state_check, 11, 0, 1, 1)
        self.manual_labjack_dio15config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio15config_cbox.setObjectName("manual_labjack_dio15config_cbox")
        self.manual_labjack_dio15config_cbox.addItem("")
        self.manual_labjack_dio15config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio15config_cbox, 7, 3, 1, 1)
        self.manual_labjack_dio4config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio4config_cbox.setObjectName("manual_labjack_dio4config_cbox")
        self.manual_labjack_dio4config_cbox.addItem("")
        self.manual_labjack_dio4config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio4config_cbox, 7, 1, 1, 1)
        self.manual_labjack_dio11config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio11config_cbox.setObjectName("manual_labjack_dio11config_cbox")
        self.manual_labjack_dio11config_cbox.addItem("")
        self.manual_labjack_dio11config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio11config_cbox, 3, 3, 1, 1)
        self.manual_labjack_dio18state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio18state_check.setObjectName("manual_labjack_dio18state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio18state_check, 10, 2, 1, 1)
        self.manual_labjack_dio20config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio20config_cbox.setObjectName("manual_labjack_dio20config_cbox")
        self.manual_labjack_dio20config_cbox.addItem("")
        self.manual_labjack_dio20config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio20config_cbox, 12, 3, 1, 1)
        self.manual_labjack_dio11state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio11state_check.setObjectName("manual_labjack_dio11state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio11state_check, 3, 2, 1, 1)
        self.manual_labjack_dio6state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio6state_check.setObjectName("manual_labjack_dio6state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio6state_check, 9, 0, 1, 1)
        self.manual_labjack_dio0state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio0state_check.setObjectName("manual_labjack_dio0state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio0state_check, 3, 0, 1, 1)
        self.manual_labjack_dio5config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio5config_cbox.setObjectName("manual_labjack_dio5config_cbox")
        self.manual_labjack_dio5config_cbox.addItem("")
        self.manual_labjack_dio5config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio5config_cbox, 8, 1, 1, 1)
        self.manual_labjack_dio0config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio0config_cbox.setObjectName("manual_labjack_dio0config_cbox")
        self.manual_labjack_dio0config_cbox.addItem("")
        self.manual_labjack_dio0config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio0config_cbox, 3, 1, 1, 1)
        self.manual_labjack_dio9config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio9config_cbox.setObjectName("manual_labjack_dio9config_cbox")
        self.manual_labjack_dio9config_cbox.addItem("")
        self.manual_labjack_dio9config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio9config_cbox, 12, 1, 1, 1)
        self.manual_labjack_dio2config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio2config_cbox.setObjectName("manual_labjack_dio2config_cbox")
        self.manual_labjack_dio2config_cbox.addItem("")
        self.manual_labjack_dio2config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio2config_cbox, 5, 1, 1, 1)
        self.manual_labjack_dio15state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio15state_check.setObjectName("manual_labjack_dio15state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio15state_check, 7, 2, 1, 1)
        self.manual_labjack_dio9state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio9state_check.setObjectName("manual_labjack_dio9state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio9state_check, 12, 0, 1, 1)
        self.manual_labjack_dio3state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio3state_check.setObjectName("manual_labjack_dio3state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio3state_check, 6, 0, 1, 1)
        self.manual_labjack_dio4state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio4state_check.setObjectName("manual_labjack_dio4state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio4state_check, 7, 0, 1, 1)
        self.manual_labjack_dio17config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio17config_cbox.setObjectName("manual_labjack_dio17config_cbox")
        self.manual_labjack_dio17config_cbox.addItem("")
        self.manual_labjack_dio17config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio17config_cbox, 9, 3, 1, 1)
        self.manual_labjack_dio6config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio6config_cbox.setObjectName("manual_labjack_dio6config_cbox")
        self.manual_labjack_dio6config_cbox.addItem("")
        self.manual_labjack_dio6config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio6config_cbox, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.LabJackControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 4)
        self.manual_labjack_dio13state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio13state_check.setObjectName("manual_labjack_dio13state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio13state_check, 5, 2, 1, 1)
        self.manual_labjack_dio7config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio7config_cbox.setObjectName("manual_labjack_dio7config_cbox")
        self.manual_labjack_dio7config_cbox.addItem("")
        self.manual_labjack_dio7config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio7config_cbox, 10, 1, 1, 1)
        self.manual_labjack_dio13config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio13config_cbox.setObjectName("manual_labjack_dio13config_cbox")
        self.manual_labjack_dio13config_cbox.addItem("")
        self.manual_labjack_dio13config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio13config_cbox, 5, 3, 1, 1)
        self.manual_labjack_dio16config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio16config_cbox.setObjectName("manual_labjack_dio16config_cbox")
        self.manual_labjack_dio16config_cbox.addItem("")
        self.manual_labjack_dio16config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio16config_cbox, 8, 3, 1, 1)
        self.manual_labjack_dio3config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio3config_cbox.setObjectName("manual_labjack_dio3config_cbox")
        self.manual_labjack_dio3config_cbox.addItem("")
        self.manual_labjack_dio3config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio3config_cbox, 6, 1, 1, 1)
        self.manual_labjack_dio8config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio8config_cbox.setObjectName("manual_labjack_dio8config_cbox")
        self.manual_labjack_dio8config_cbox.addItem("")
        self.manual_labjack_dio8config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio8config_cbox, 11, 1, 1, 1)
        self.manual_labjack_dio21config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio21config_cbox.setObjectName("manual_labjack_dio21config_cbox")
        self.manual_labjack_dio21config_cbox.addItem("")
        self.manual_labjack_dio21config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio21config_cbox, 13, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.LabJackControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.manual_labjack_dio12config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio12config_cbox.setObjectName("manual_labjack_dio12config_cbox")
        self.manual_labjack_dio12config_cbox.addItem("")
        self.manual_labjack_dio12config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio12config_cbox, 4, 3, 1, 1)
        self.manual_labjack_dio7state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio7state_check.setObjectName("manual_labjack_dio7state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio7state_check, 10, 0, 1, 1)
        self.manual_labjack_dio19state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio19state_check.setObjectName("manual_labjack_dio19state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio19state_check, 11, 2, 1, 1)
        self.manual_labjack_dio2state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio2state_check.setObjectName("manual_labjack_dio2state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio2state_check, 5, 0, 1, 1)
        self.manual_labjack_dio1config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio1config_cbox.setObjectName("manual_labjack_dio1config_cbox")
        self.manual_labjack_dio1config_cbox.addItem("")
        self.manual_labjack_dio1config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio1config_cbox, 4, 1, 1, 1)
        self.manual_labjack_dio1state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio1state_check.setObjectName("manual_labjack_dio1state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio1state_check, 4, 0, 1, 1)
        self.manual_labjack_dio10config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio10config_cbox.setObjectName("manual_labjack_dio10config_cbox")
        self.manual_labjack_dio10config_cbox.addItem("")
        self.manual_labjack_dio10config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio10config_cbox, 13, 1, 1, 1)
        self.manual_labjack_dio5state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio5state_check.setObjectName("manual_labjack_dio5state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio5state_check, 8, 0, 1, 1)
        self.manual_labjack_dio17state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio17state_check.setObjectName("manual_labjack_dio17state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio17state_check, 9, 2, 1, 1)
        self.manual_labjack_dio19config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio19config_cbox.setObjectName("manual_labjack_dio19config_cbox")
        self.manual_labjack_dio19config_cbox.addItem("")
        self.manual_labjack_dio19config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio19config_cbox, 11, 3, 1, 1)
        self.manual_labjack_dio10state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio10state_check.setObjectName("manual_labjack_dio10state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio10state_check, 13, 0, 1, 1)
        self.manual_labjack_dio16state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio16state_check.setObjectName("manual_labjack_dio16state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio16state_check, 8, 2, 1, 1)
        self.manual_labjack_dio18config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio18config_cbox.setObjectName("manual_labjack_dio18config_cbox")
        self.manual_labjack_dio18config_cbox.addItem("")
        self.manual_labjack_dio18config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio18config_cbox, 10, 3, 1, 1)
        self.manual_labjack_dio20state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio20state_check.setObjectName("manual_labjack_dio20state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio20state_check, 12, 2, 1, 1)
        self.manual_labjack_dio12state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio12state_check.setObjectName("manual_labjack_dio12state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio12state_check, 4, 2, 1, 1)
        self.manual_labjack_dio21state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio21state_check.setObjectName("manual_labjack_dio21state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio21state_check, 13, 2, 1, 1)
        self.manual_labjack_dio14state_check = QtWidgets.QCheckBox(self.LabJackControl)
        self.manual_labjack_dio14state_check.setObjectName("manual_labjack_dio14state_check")
        self.gridLayout_4.addWidget(self.manual_labjack_dio14state_check, 6, 2, 1, 1)
        self.manual_labjack_dio14config_cbox = QtWidgets.QComboBox(self.LabJackControl)
        self.manual_labjack_dio14config_cbox.setObjectName("manual_labjack_dio14config_cbox")
        self.manual_labjack_dio14config_cbox.addItem("")
        self.manual_labjack_dio14config_cbox.addItem("")
        self.gridLayout_4.addWidget(self.manual_labjack_dio14config_cbox, 6, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.LabJackControl)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 4)
        self.stackedWidget.addWidget(self.LabJackControl)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.manual_monochromator_shutter_label.setText(_translate("Form", "Shutter:"))
        self.manual_monochromator_currentfilter_combobox.setItemText(0, _translate("Form", "No OSF"))
        self.manual_monochromator_currentfilter_combobox.setItemText(1, _translate("Form", "OSF1"))
        self.manual_monochromator_currentfilter_combobox.setItemText(2, _translate("Form", "OSF2"))
        self.manual_monochromator_currentfilter_combobox.setItemText(3, _translate("Form", "OSF3"))
        self.manual_monochromator_newfilter_combobox.setItemText(0, _translate("Form", "No OSF"))
        self.manual_monochromator_newfilter_combobox.setItemText(1, _translate("Form", "OSF1"))
        self.manual_monochromator_newfilter_combobox.setItemText(2, _translate("Form", "OSF2"))
        self.manual_monochromator_newfilter_combobox.setItemText(3, _translate("Form", "OSF3"))
        self.manual_monochromator_newgrating_combobox.setItemText(0, _translate("Form", "G1"))
        self.manual_monochromator_newgrating_combobox.setItemText(1, _translate("Form", "G2"))
        self.manual_monochromator_newgrating_combobox.setItemText(2, _translate("Form", "G3"))
        self.manual_monochromator_wavelength_label.setText(_translate("Form", "Wavelength (um.):"))
        self.manual_monochromator_grating_label.setText(_translate("Form", "Grating:"))
        self.manual_monochromator_filter_label_2.setText(_translate("Form", "Filter:"))
        self.manual_monochromator_label.setText(_translate("Form", "Monochromator:"))
        self.manual_monochromator_grating_label_2.setText(_translate("Form", "Grating:"))
        self.manual_monochromator_shutter_label_2.setText(_translate("Form", "Shutter:"))
        self.manual_monochromator_currentshutter_combobox.setItemText(0, _translate("Form", "Open"))
        self.manual_monochromator_currentshutter_combobox.setItemText(1, _translate("Form", "Close"))
        self.manual_monochromator_filter_label.setText(_translate("Form", "Filter:"))
        self.manual_monochromator_currentgrating_combobox.setItemText(0, _translate("Form", "G1"))
        self.manual_monochromator_currentgrating_combobox.setItemText(1, _translate("Form", "G2"))
        self.manual_monochromator_currentgrating_combobox.setItemText(2, _translate("Form", "G3"))
        self.manual_monochromator_wavelength_label_2.setText(_translate("Form", "Wavelength (um.):"))
        self.manual_monochromator_setparams_button.setText(_translate("Form", "Set New Parameters"))
        self.manual_monochromator_newshutter_combobox.setItemText(0, _translate("Form", "Open"))
        self.manual_monochromator_newshutter_combobox.setItemText(1, _translate("Form", "Close"))
        self.label_2.setText(_translate("Form", "Current Parameters:"))
        self.label.setText(_translate("Form", "New Parameters:"))
        self.manual_lockin_label.setText(_translate("Form", "Lock-In:"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(1, _translate("Form", "2"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(2, _translate("Form", "5"))
        self.manual_lockin_measurementstorage_label.setText(_translate("Form", "Measurement Storage Path:"))
        self.label_5.setText(_translate("Form", "Multiplier:"))
        self.manual_lockin_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.manual_lockin_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.manual_lockin_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.manual_lockin_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.manual_lockin_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.manual_lockin_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.manual_lockin_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.manual_lockin_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.manual_lockin_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.manual_lockin_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.manual_lockin_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.manual_lockin_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.manual_lockin_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.label_3.setText(_translate("Form", "Multiplier:"))
        self.manual_lockin_timeconstantunit_cbox.setItemText(0, _translate("Form", "ks."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(1, _translate("Form", "s."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(2, _translate("Form", "ms."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(3, _translate("Form", "us."))
        self.label_7.setText(_translate("Form", "Value:"))
        self.label_8.setText(_translate("Form", "Units:"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.manual_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.label_12.setText(_translate("Form", "New Parameters:"))
        self.label_10.setText(_translate("Form", "Sensitivity:"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(1, _translate("Form", "3"))
        self.manual_lockin_timeconstant_label.setText(_translate("Form", "Time-Constant:"))
        self.manual_lockin_samplerate_label.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.manual_lockin_sensitivityunit_cbox.setItemText(0, _translate("Form", "V."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(1, _translate("Form", "mV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(2, _translate("Form", "uV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(3, _translate("Form", "nV."))
        self.manual_lockin_startmeasurement_button.setText(_translate("Form", "Start Measurement"))
        self.manual_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity:"))
        self.label_9.setText(_translate("Form", "Current Parameters:"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.manual_lockin_setparams_button.setText(_translate("Form", "Set New Parameters"))
        self.label_6.setText(_translate("Form", "Units:"))
        self.label_4.setText(_translate("Form", "Value:"))
        self.label_11.setText(_translate("Form", "Time-Constant:"))
        self.label_13.setText(_translate("Form", "Measurement:"))
        self.manual_labjack_dio8state_check.setText(_translate("Form", "DIO8"))
        self.manual_labjack_dio15config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio15config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio4config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio4config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio11config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio11config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio18state_check.setText(_translate("Form", "DIO18"))
        self.manual_labjack_dio20config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio20config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio11state_check.setText(_translate("Form", "DIO11"))
        self.manual_labjack_dio6state_check.setText(_translate("Form", "DIO6"))
        self.manual_labjack_dio0state_check.setText(_translate("Form", "DIO0"))
        self.manual_labjack_dio5config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio5config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio0config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio0config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio9config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio9config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio2config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio2config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio15state_check.setText(_translate("Form", "DIO15"))
        self.manual_labjack_dio9state_check.setText(_translate("Form", "DIO9"))
        self.manual_labjack_dio3state_check.setText(_translate("Form", "DIO3"))
        self.manual_labjack_dio4state_check.setText(_translate("Form", "DIO4"))
        self.manual_labjack_dio17config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio17config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio6config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio6config_cbox.setItemText(1, _translate("Form", "Output"))
        self.label_14.setText(_translate("Form", "LabJack:"))
        self.manual_labjack_dio13state_check.setText(_translate("Form", "DIO13"))
        self.manual_labjack_dio7config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio7config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio13config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio13config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio16config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio16config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio3config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio3config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio8config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio8config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio21config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio21config_cbox.setItemText(1, _translate("Form", "Output"))
        self.label_15.setText(_translate("Form", "Digital I/O:"))
        self.manual_labjack_dio12config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio12config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio7state_check.setText(_translate("Form", "DIO7"))
        self.manual_labjack_dio19state_check.setText(_translate("Form", "DIO19"))
        self.manual_labjack_dio2state_check.setText(_translate("Form", "DIO2"))
        self.manual_labjack_dio1config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio1config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio1state_check.setText(_translate("Form", "DIO1"))
        self.manual_labjack_dio10config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio10config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio5state_check.setText(_translate("Form", "DIO5"))
        self.manual_labjack_dio17state_check.setText(_translate("Form", "DIO17"))
        self.manual_labjack_dio19config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio19config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio10state_check.setText(_translate("Form", "DIO10"))
        self.manual_labjack_dio16state_check.setText(_translate("Form", "DIO16"))
        self.manual_labjack_dio18config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio18config_cbox.setItemText(1, _translate("Form", "Output"))
        self.manual_labjack_dio20state_check.setText(_translate("Form", "DIO20"))
        self.manual_labjack_dio12state_check.setText(_translate("Form", "DIO12"))
        self.manual_labjack_dio21state_check.setText(_translate("Form", "DIO21"))
        self.manual_labjack_dio14state_check.setText(_translate("Form", "DIO14"))
        self.manual_labjack_dio14config_cbox.setItemText(0, _translate("Form", "Input"))
        self.manual_labjack_dio14config_cbox.setItemText(1, _translate("Form", "Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

