# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockinAutoWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1709, 1422)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem1, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequence_sr510_sensitivity_units_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_sensitivity_units_label.setObjectName("sequence_sr510_sensitivity_units_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_units_label, 10, 0, 1, 1)
        self.sequence_sr510_samplefreq_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_samplefreq_label.setObjectName("sequence_sr510_samplefreq_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_samplefreq_label, 1, 0, 1, 1)
        self.sequence_sr510_timeconstant_value_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_timeconstant_value_label.setObjectName("sequence_sr510_timeconstant_value_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_value_label, 2, 0, 1, 1)
        self.sequence_sr510_samplerate_combobox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_samplerate_combobox.setObjectName("sequence_sr510_samplerate_combobox")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_samplerate_combobox, 1, 1, 1, 1)
        self.sequence_sr510_senstransitions_list = QtWidgets.QListWidget(self.tab)
        self.sequence_sr510_senstransitions_list.setObjectName("sequence_sr510_senstransitions_list")
        self.gridLayout_2.addWidget(self.sequence_sr510_senstransitions_list, 6, 0, 1, 2)
        self.sequence_sr510_senstransition_add_button = QtWidgets.QPushButton(self.tab)
        self.sequence_sr510_senstransition_add_button.setObjectName("sequence_sr510_senstransition_add_button")
        self.gridLayout_2.addWidget(self.sequence_sr510_senstransition_add_button, 11, 0, 1, 2)
        self.sequence_sr510_senstransition_removeall_button = QtWidgets.QPushButton(self.tab)
        self.sequence_sr510_senstransition_removeall_button.setObjectName("sequence_sr510_senstransition_removeall_button")
        self.gridLayout_2.addWidget(self.sequence_sr510_senstransition_removeall_button, 13, 0, 1, 2)
        self.sequence_sr510_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr510_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr510_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_sr510_label.setFont(font)
        self.sequence_sr510_label.setObjectName("sequence_sr510_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_label, 0, 0, 1, 2)
        self.sequence_sr510_wave_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_wave_label.setObjectName("sequence_sr510_wave_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_wave_label, 7, 0, 1, 1)
        self.sequence_sr510_senstransition_remove_button = QtWidgets.QPushButton(self.tab)
        self.sequence_sr510_senstransition_remove_button.setObjectName("sequence_sr510_senstransition_remove_button")
        self.gridLayout_2.addWidget(self.sequence_sr510_senstransition_remove_button, 12, 0, 1, 2)
        self.sequence_sr510_sensitivity_value_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_sensitivity_value_label.setObjectName("sequence_sr510_sensitivity_value_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_value_label, 8, 0, 1, 1)
        self.sequence_sr510_sensitivity_units_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_sensitivity_units_cbox.setObjectName("sequence_sr510_sensitivity_units_cbox")
        self.sequence_sr510_sensitivity_units_cbox.addItem("")
        self.sequence_sr510_sensitivity_units_cbox.addItem("")
        self.sequence_sr510_sensitivity_units_cbox.addItem("")
        self.sequence_sr510_sensitivity_units_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_units_cbox, 10, 1, 1, 1)
        self.sequence_sr510_timeconstant_multiplier_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_timeconstant_multiplier_label.setObjectName("sequence_sr510_timeconstant_multiplier_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_multiplier_label, 3, 0, 1, 1)
        self.sequence_sr510_timeconstant_value_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_timeconstant_value_cbox.setObjectName("sequence_sr510_timeconstant_value_cbox")
        self.sequence_sr510_timeconstant_value_cbox.addItem("")
        self.sequence_sr510_timeconstant_value_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_value_cbox, 2, 1, 1, 1)
        self.sequence_sr510_timeconstant_multiplier_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_timeconstant_multiplier_cbox.setObjectName("sequence_sr510_timeconstant_multiplier_cbox")
        self.sequence_sr510_timeconstant_multiplier_cbox.addItem("")
        self.sequence_sr510_timeconstant_multiplier_cbox.addItem("")
        self.sequence_sr510_timeconstant_multiplier_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_multiplier_cbox, 3, 1, 1, 1)
        self.sequence_sr510_wave_ledit = QtWidgets.QLineEdit(self.tab)
        self.sequence_sr510_wave_ledit.setObjectName("sequence_sr510_wave_ledit")
        self.gridLayout_2.addWidget(self.sequence_sr510_wave_ledit, 7, 1, 1, 1)
        self.sequence_sr510_sensitivity_value_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_sensitivity_value_cbox.setObjectName("sequence_sr510_sensitivity_value_cbox")
        self.sequence_sr510_sensitivity_value_cbox.addItem("")
        self.sequence_sr510_sensitivity_value_cbox.addItem("")
        self.sequence_sr510_sensitivity_value_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_value_cbox, 8, 1, 1, 1)
        self.sequence_sr510_sensitivity_multiplier_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_sensitivity_multiplier_cbox.setObjectName("sequence_sr510_sensitivity_multiplier_cbox")
        self.sequence_sr510_sensitivity_multiplier_cbox.addItem("")
        self.sequence_sr510_sensitivity_multiplier_cbox.addItem("")
        self.sequence_sr510_sensitivity_multiplier_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_multiplier_cbox, 9, 1, 1, 1)
        self.sequence_sr510_sensitivity_multiplier_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_sensitivity_multiplier_label.setObjectName("sequence_sr510_sensitivity_multiplier_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_sensitivity_multiplier_label, 9, 0, 1, 1)
        self.sequence_sr510_timeconstant_units_label = QtWidgets.QLabel(self.tab)
        self.sequence_sr510_timeconstant_units_label.setObjectName("sequence_sr510_timeconstant_units_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_units_label, 4, 0, 1, 1)
        self.sequence_sr510_timeconstant_units_cbox = QtWidgets.QComboBox(self.tab)
        self.sequence_sr510_timeconstant_units_cbox.setObjectName("sequence_sr510_timeconstant_units_cbox")
        self.sequence_sr510_timeconstant_units_cbox.addItem("")
        self.sequence_sr510_timeconstant_units_cbox.addItem("")
        self.sequence_sr510_timeconstant_units_cbox.addItem("")
        self.sequence_sr510_timeconstant_units_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sequence_sr510_timeconstant_units_cbox, 4, 1, 1, 1)
        self.sequence_sr510_senstransitions_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr510_senstransitions_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr510_senstransitions_label.setSizePolicy(sizePolicy)
        self.sequence_sr510_senstransitions_label.setObjectName("sequence_sr510_senstransitions_label")
        self.gridLayout_2.addWidget(self.sequence_sr510_senstransitions_label, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.sequence_sr830_label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_sr830_label.setFont(font)
        self.sequence_sr830_label.setObjectName("sequence_sr830_label")
        self.gridLayout.addWidget(self.sequence_sr830_label, 0, 0, 1, 1)
        self.sequence_sr830_samplefreq_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_samplefreq_label.setObjectName("sequence_sr830_samplefreq_label")
        self.gridLayout.addWidget(self.sequence_sr830_samplefreq_label, 1, 0, 1, 1)
        self.sequence_sr830_samplerate_combobox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_samplerate_combobox.setObjectName("sequence_sr830_samplerate_combobox")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_samplerate_combobox, 1, 1, 1, 1)
        self.sequence_sr830_timeconstant_value_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_timeconstant_value_label.setObjectName("sequence_sr830_timeconstant_value_label")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_value_label, 2, 0, 1, 1)
        self.sequence_sr830_sens_transition_removeall_button = QtWidgets.QPushButton(self.tab_2)
        self.sequence_sr830_sens_transition_removeall_button.setObjectName("sequence_sr830_sens_transition_removeall_button")
        self.gridLayout.addWidget(self.sequence_sr830_sens_transition_removeall_button, 13, 0, 1, 2)
        self.sequence_sr830_senstransitions_label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_senstransitions_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_senstransitions_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sequence_sr830_senstransitions_label.setFont(font)
        self.sequence_sr830_senstransitions_label.setObjectName("sequence_sr830_senstransitions_label")
        self.gridLayout.addWidget(self.sequence_sr830_senstransitions_label, 5, 0, 1, 1)
        self.sequence_sr830_senstransitions_list = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_senstransitions_list.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_senstransitions_list.setSizePolicy(sizePolicy)
        self.sequence_sr830_senstransitions_list.setObjectName("sequence_sr830_senstransitions_list")
        self.gridLayout.addWidget(self.sequence_sr830_senstransitions_list, 6, 0, 1, 2)
        self.sequence_sr830_senstransition_add_button = QtWidgets.QPushButton(self.tab_2)
        self.sequence_sr830_senstransition_add_button.setObjectName("sequence_sr830_senstransition_add_button")
        self.gridLayout.addWidget(self.sequence_sr830_senstransition_add_button, 11, 0, 1, 2)
        self.sequence_sr830_wave_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_wave_label.setObjectName("sequence_sr830_wave_label")
        self.gridLayout.addWidget(self.sequence_sr830_wave_label, 7, 0, 1, 1)
        self.sequence_sr830_sens_transition_remove_button = QtWidgets.QPushButton(self.tab_2)
        self.sequence_sr830_sens_transition_remove_button.setObjectName("sequence_sr830_sens_transition_remove_button")
        self.gridLayout.addWidget(self.sequence_sr830_sens_transition_remove_button, 12, 0, 1, 2)
        self.sequence_sr830_sensitivity_units_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_sensitivity_units_cbox.setObjectName("sequence_sr830_sensitivity_units_cbox")
        self.sequence_sr830_sensitivity_units_cbox.addItem("")
        self.sequence_sr830_sensitivity_units_cbox.addItem("")
        self.sequence_sr830_sensitivity_units_cbox.addItem("")
        self.sequence_sr830_sensitivity_units_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_units_cbox, 10, 1, 1, 1)
        self.sequence_sr830_timeconstant_multiplier_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_timeconstant_multiplier_label.setObjectName("sequence_sr830_timeconstant_multiplier_label")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_multiplier_label, 3, 0, 1, 1)
        self.sequence_sr830_sensitivity_multiplier_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_sensitivity_multiplier_label.setObjectName("sequence_sr830_sensitivity_multiplier_label")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_multiplier_label, 9, 0, 1, 1)
        self.sequence_sr830_sensitivity_value_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_sensitivity_value_cbox.setObjectName("sequence_sr830_sensitivity_value_cbox")
        self.sequence_sr830_sensitivity_value_cbox.addItem("")
        self.sequence_sr830_sensitivity_value_cbox.addItem("")
        self.sequence_sr830_sensitivity_value_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_value_cbox, 8, 1, 1, 1)
        self.sequence_sr830_sensitivity_units_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_sensitivity_units_label.setObjectName("sequence_sr830_sensitivity_units_label")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_units_label, 10, 0, 1, 1)
        self.sequence_sr830_sensitivity_value_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_sensitivity_value_label.setObjectName("sequence_sr830_sensitivity_value_label")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_value_label, 8, 0, 1, 1)
        self.sequence_sr830_sensitivity_multiplier_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_sensitivity_multiplier_cbox.setObjectName("sequence_sr830_sensitivity_multiplier_cbox")
        self.sequence_sr830_sensitivity_multiplier_cbox.addItem("")
        self.sequence_sr830_sensitivity_multiplier_cbox.addItem("")
        self.sequence_sr830_sensitivity_multiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_sensitivity_multiplier_cbox, 9, 1, 1, 1)
        self.sequence_sr830_wave_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.sequence_sr830_wave_ledit.setObjectName("sequence_sr830_wave_ledit")
        self.gridLayout.addWidget(self.sequence_sr830_wave_ledit, 7, 1, 1, 1)
        self.sequence_sr830_timeconstant_units_label = QtWidgets.QLabel(self.tab_2)
        self.sequence_sr830_timeconstant_units_label.setObjectName("sequence_sr830_timeconstant_units_label")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_units_label, 4, 0, 1, 1)
        self.sequence_sr830_timeconstant_value_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_timeconstant_value_cbox.setObjectName("sequence_sr830_timeconstant_value_cbox")
        self.sequence_sr830_timeconstant_value_cbox.addItem("")
        self.sequence_sr830_timeconstant_value_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_value_cbox, 2, 1, 1, 1)
        self.sequence_sr830_timeconstant_multiplier_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_timeconstant_multiplier_cbox.setObjectName("sequence_sr830_timeconstant_multiplier_cbox")
        self.sequence_sr830_timeconstant_multiplier_cbox.addItem("")
        self.sequence_sr830_timeconstant_multiplier_cbox.addItem("")
        self.sequence_sr830_timeconstant_multiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_multiplier_cbox, 3, 1, 1, 1)
        self.sequence_sr830_timeconstant_units_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sequence_sr830_timeconstant_units_cbox.setObjectName("sequence_sr830_timeconstant_units_cbox")
        self.sequence_sr830_timeconstant_units_cbox.addItem("")
        self.sequence_sr830_timeconstant_units_cbox.addItem("")
        self.sequence_sr830_timeconstant_units_cbox.addItem("")
        self.sequence_sr830_timeconstant_units_cbox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_units_cbox, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.main_layout.addWidget(self.tabWidget, 1, 0, 1, 2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lockin Amplifier(s)"))
        self.sequence_sr510_sensitivity_units_label.setText(_translate("Form", "Sensitivity Units:"))
        self.sequence_sr510_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.sequence_sr510_timeconstant_value_label.setText(_translate("Form", "Time Constant Value:"))
        self.sequence_sr510_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sequence_sr510_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sequence_sr510_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sequence_sr510_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sequence_sr510_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sequence_sr510_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sequence_sr510_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sequence_sr510_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sequence_sr510_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sequence_sr510_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sequence_sr510_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sequence_sr510_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sequence_sr510_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sequence_sr510_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sequence_sr510_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.sequence_sr510_senstransition_add_button.setText(_translate("Form", "Add SR510 Sensitivity Transition to Sequence"))
        self.sequence_sr510_senstransition_removeall_button.setText(_translate("Form", "Remove All SR510 Transitions from Sequence"))
        self.sequence_sr510_label.setText(_translate("Form", "SR510 Lock-In Sequence Control:"))
        self.sequence_sr510_wave_label.setText(_translate("Form", "Wavelength:"))
        self.sequence_sr510_senstransition_remove_button.setText(_translate("Form", "Remove SR510 Sensitivity Transition from Sequence"))
        self.sequence_sr510_sensitivity_value_label.setText(_translate("Form", "Sensitivity Value:"))
        self.sequence_sr510_sensitivity_units_cbox.setCurrentText(_translate("Form", "V."))
        self.sequence_sr510_sensitivity_units_cbox.setItemText(0, _translate("Form", "V."))
        self.sequence_sr510_sensitivity_units_cbox.setItemText(1, _translate("Form", "mV."))
        self.sequence_sr510_sensitivity_units_cbox.setItemText(2, _translate("Form", "uV."))
        self.sequence_sr510_sensitivity_units_cbox.setItemText(3, _translate("Form", "nV."))
        self.sequence_sr510_timeconstant_multiplier_label.setText(_translate("Form", "Time Constant Multiplier:"))
        self.sequence_sr510_timeconstant_value_cbox.setItemText(0, _translate("Form", "1"))
        self.sequence_sr510_timeconstant_value_cbox.setItemText(1, _translate("Form", "3"))
        self.sequence_sr510_timeconstant_multiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sequence_sr510_timeconstant_multiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sequence_sr510_timeconstant_multiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sequence_sr510_sensitivity_value_cbox.setCurrentText(_translate("Form", "1"))
        self.sequence_sr510_sensitivity_value_cbox.setItemText(0, _translate("Form", "1"))
        self.sequence_sr510_sensitivity_value_cbox.setItemText(1, _translate("Form", "2"))
        self.sequence_sr510_sensitivity_value_cbox.setItemText(2, _translate("Form", "5"))
        self.sequence_sr510_sensitivity_multiplier_cbox.setCurrentText(_translate("Form", "x1"))
        self.sequence_sr510_sensitivity_multiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sequence_sr510_sensitivity_multiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sequence_sr510_sensitivity_multiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sequence_sr510_sensitivity_multiplier_label.setText(_translate("Form", "Sensitivity Multiplier:"))
        self.sequence_sr510_timeconstant_units_label.setText(_translate("Form", "Time Constant Units:"))
        self.sequence_sr510_timeconstant_units_cbox.setCurrentText(_translate("Form", "ks."))
        self.sequence_sr510_timeconstant_units_cbox.setItemText(0, _translate("Form", "ks."))
        self.sequence_sr510_timeconstant_units_cbox.setItemText(1, _translate("Form", "s."))
        self.sequence_sr510_timeconstant_units_cbox.setItemText(2, _translate("Form", "ms."))
        self.sequence_sr510_timeconstant_units_cbox.setItemText(3, _translate("Form", "us."))
        self.sequence_sr510_senstransitions_label.setText(_translate("Form", "SR510 Sensitivity Transitions in Sequence:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "SR510"))
        self.sequence_sr830_label.setText(_translate("Form", "SR830 Lock-In Sequence Control:"))
        self.sequence_sr830_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.sequence_sr830_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sequence_sr830_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sequence_sr830_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sequence_sr830_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sequence_sr830_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sequence_sr830_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sequence_sr830_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sequence_sr830_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sequence_sr830_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sequence_sr830_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sequence_sr830_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sequence_sr830_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sequence_sr830_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sequence_sr830_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sequence_sr830_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.sequence_sr830_timeconstant_value_label.setText(_translate("Form", "Time Constant Value:"))
        self.sequence_sr830_sens_transition_removeall_button.setText(_translate("Form", "Remove All SR830 Transitions from Sequence"))
        self.sequence_sr830_senstransitions_label.setText(_translate("Form", "SR830 Sensitivity Transitions in Sequence:"))
        self.sequence_sr830_senstransition_add_button.setText(_translate("Form", "Add SR830 Sensitivity Transition to Sequence"))
        self.sequence_sr830_wave_label.setText(_translate("Form", "Wavelength:"))
        self.sequence_sr830_sens_transition_remove_button.setText(_translate("Form", "Remove SR830 Sensitivity Transitions from Sequence"))
        self.sequence_sr830_sensitivity_units_cbox.setItemText(0, _translate("Form", "V."))
        self.sequence_sr830_sensitivity_units_cbox.setItemText(1, _translate("Form", "mV."))
        self.sequence_sr830_sensitivity_units_cbox.setItemText(2, _translate("Form", "uV."))
        self.sequence_sr830_sensitivity_units_cbox.setItemText(3, _translate("Form", "nV."))
        self.sequence_sr830_timeconstant_multiplier_label.setText(_translate("Form", "Time Constant Multiplier:"))
        self.sequence_sr830_sensitivity_multiplier_label.setText(_translate("Form", "Sensitivity Multiplier:"))
        self.sequence_sr830_sensitivity_value_cbox.setItemText(0, _translate("Form", "1"))
        self.sequence_sr830_sensitivity_value_cbox.setItemText(1, _translate("Form", "2"))
        self.sequence_sr830_sensitivity_value_cbox.setItemText(2, _translate("Form", "5"))
        self.sequence_sr830_sensitivity_units_label.setText(_translate("Form", "Sensitivity Units:"))
        self.sequence_sr830_sensitivity_value_label.setText(_translate("Form", "Sensitivity Value:"))
        self.sequence_sr830_sensitivity_multiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sequence_sr830_sensitivity_multiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sequence_sr830_sensitivity_multiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sequence_sr830_timeconstant_units_label.setText(_translate("Form", "Time Constant Units:"))
        self.sequence_sr830_timeconstant_value_cbox.setItemText(0, _translate("Form", "1"))
        self.sequence_sr830_timeconstant_value_cbox.setItemText(1, _translate("Form", "3"))
        self.sequence_sr830_timeconstant_multiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sequence_sr830_timeconstant_multiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sequence_sr830_timeconstant_multiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sequence_sr830_timeconstant_units_cbox.setCurrentText(_translate("Form", "ks."))
        self.sequence_sr830_timeconstant_units_cbox.setItemText(0, _translate("Form", "ks."))
        self.sequence_sr830_timeconstant_units_cbox.setItemText(1, _translate("Form", "s."))
        self.sequence_sr830_timeconstant_units_cbox.setItemText(2, _translate("Form", "ms."))
        self.sequence_sr830_timeconstant_units_cbox.setItemText(3, _translate("Form", "us."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "SR830"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

