# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockinWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1192, 1263)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sr510_manual_lockin_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr510_manual_lockin_label.sizePolicy().hasHeightForWidth())
        self.sr510_manual_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sr510_manual_lockin_label.setFont(font)
        self.sr510_manual_lockin_label.setObjectName("sr510_manual_lockin_label")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_label, 0, 0, 1, 1)
        self.sr510_current_parameters_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sr510_current_parameters_label.setFont(font)
        self.sr510_current_parameters_label.setObjectName("sr510_current_parameters_label")
        self.gridLayout_2.addWidget(self.sr510_current_parameters_label, 1, 0, 1, 1)
        self.sr510_cursens_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sr510_cursens_label.setFont(font)
        self.sr510_cursens_label.setObjectName("sr510_cursens_label")
        self.gridLayout_2.addWidget(self.sr510_cursens_label, 2, 0, 1, 1)
        self.sr510_curtc_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sr510_curtc_label.setFont(font)
        self.sr510_curtc_label.setObjectName("sr510_curtc_label")
        self.gridLayout_2.addWidget(self.sr510_curtc_label, 2, 1, 1, 1)
        self.sr510_manual_lockin_sensitivity_ledit = QtWidgets.QLineEdit(self.tab)
        self.sr510_manual_lockin_sensitivity_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sr510_manual_lockin_sensitivity_ledit.setFont(font)
        self.sr510_manual_lockin_sensitivity_ledit.setReadOnly(False)
        self.sr510_manual_lockin_sensitivity_ledit.setClearButtonEnabled(False)
        self.sr510_manual_lockin_sensitivity_ledit.setObjectName("sr510_manual_lockin_sensitivity_ledit")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sensitivity_ledit, 3, 0, 1, 1)
        self.sr510_manual_lockin_timeconstant_ledit = QtWidgets.QLineEdit(self.tab)
        self.sr510_manual_lockin_timeconstant_ledit.setEnabled(False)
        self.sr510_manual_lockin_timeconstant_ledit.setReadOnly(False)
        self.sr510_manual_lockin_timeconstant_ledit.setObjectName("sr510_manual_lockin_timeconstant_ledit")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_timeconstant_ledit, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 2)
        self.sr510_new_parameters_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sr510_new_parameters_label.setFont(font)
        self.sr510_new_parameters_label.setObjectName("sr510_new_parameters_label")
        self.gridLayout_2.addWidget(self.sr510_new_parameters_label, 5, 0, 1, 2)
        self.sr510_manual_lockin_sensitivity_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr510_manual_lockin_sensitivity_label.sizePolicy().hasHeightForWidth())
        self.sr510_manual_lockin_sensitivity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sr510_manual_lockin_sensitivity_label.setFont(font)
        self.sr510_manual_lockin_sensitivity_label.setObjectName("sr510_manual_lockin_sensitivity_label")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sensitivity_label, 6, 0, 1, 1)
        self.sr510_manual_lockin_timeconstant_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sr510_manual_lockin_timeconstant_label.setFont(font)
        self.sr510_manual_lockin_timeconstant_label.setObjectName("sr510_manual_lockin_timeconstant_label")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_timeconstant_label, 6, 1, 1, 1)
        self.sr510_sens_value_label = QtWidgets.QLabel(self.tab)
        self.sr510_sens_value_label.setObjectName("sr510_sens_value_label")
        self.gridLayout_2.addWidget(self.sr510_sens_value_label, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 1, 1, 1)
        self.sr510_manual_lockin_sensitivityvalue_cbox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr510_manual_lockin_sensitivityvalue_cbox.sizePolicy().hasHeightForWidth())
        self.sr510_manual_lockin_sensitivityvalue_cbox.setSizePolicy(sizePolicy)
        self.sr510_manual_lockin_sensitivityvalue_cbox.setObjectName("sr510_manual_lockin_sensitivityvalue_cbox")
        self.sr510_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.sr510_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.sr510_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sensitivityvalue_cbox, 8, 0, 1, 1)
        self.sr510_manual_lockin_timeconstantvalue_cbox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr510_manual_lockin_timeconstantvalue_cbox.sizePolicy().hasHeightForWidth())
        self.sr510_manual_lockin_timeconstantvalue_cbox.setSizePolicy(sizePolicy)
        self.sr510_manual_lockin_timeconstantvalue_cbox.setObjectName("sr510_manual_lockin_timeconstantvalue_cbox")
        self.sr510_manual_lockin_timeconstantvalue_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantvalue_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_timeconstantvalue_cbox, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 1, 1, 1)
        self.sr510_manual_lockin_sensitivitymultiplier_cbox = QtWidgets.QComboBox(self.tab)
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.setObjectName("sr510_manual_lockin_sensitivitymultiplier_cbox")
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sensitivitymultiplier_cbox, 10, 0, 1, 1)
        self.sr510_manual_lockin_timeconstantmultiplier_cbox = QtWidgets.QComboBox(self.tab)
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.setObjectName("sr510_manual_lockin_timeconstantmultiplier_cbox")
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_timeconstantmultiplier_cbox, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 11, 1, 1, 1)
        self.sr510_manual_lockin_sensitivityunit_cbox = QtWidgets.QComboBox(self.tab)
        self.sr510_manual_lockin_sensitivityunit_cbox.setObjectName("sr510_manual_lockin_sensitivityunit_cbox")
        self.sr510_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr510_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr510_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr510_manual_lockin_sensitivityunit_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sensitivityunit_cbox, 12, 0, 1, 1)
        self.sr510_manual_lockin_timeconstantunit_cbox = QtWidgets.QComboBox(self.tab)
        self.sr510_manual_lockin_timeconstantunit_cbox.setObjectName("sr510_manual_lockin_timeconstantunit_cbox")
        self.sr510_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr510_manual_lockin_timeconstantunit_cbox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_timeconstantunit_cbox, 12, 1, 1, 1)
        self.sr510_manual_lockin_setparams_button = QtWidgets.QPushButton(self.tab)
        self.sr510_manual_lockin_setparams_button.setObjectName("sr510_manual_lockin_setparams_button")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_setparams_button, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 14, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 15, 0, 1, 1)
        self.manual_lockin_samplerate_label = QtWidgets.QLabel(self.tab)
        self.manual_lockin_samplerate_label.setObjectName("manual_lockin_samplerate_label")
        self.gridLayout_2.addWidget(self.manual_lockin_samplerate_label, 16, 0, 1, 1)
        self.manual_lockin_sampletime_label = QtWidgets.QLabel(self.tab)
        self.manual_lockin_sampletime_label.setObjectName("manual_lockin_sampletime_label")
        self.gridLayout_2.addWidget(self.manual_lockin_sampletime_label, 16, 1, 1, 1)
        self.sr510_manual_lockin_samplerate_combobox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr510_manual_lockin_samplerate_combobox.sizePolicy().hasHeightForWidth())
        self.sr510_manual_lockin_samplerate_combobox.setSizePolicy(sizePolicy)
        self.sr510_manual_lockin_samplerate_combobox.setObjectName("sr510_manual_lockin_samplerate_combobox")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.sr510_manual_lockin_samplerate_combobox.addItem("")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_samplerate_combobox, 17, 0, 1, 1)
        self.sr510_manual_lockin_sampletime_ledit = QtWidgets.QLineEdit(self.tab)
        self.sr510_manual_lockin_sampletime_ledit.setObjectName("sr510_manual_lockin_sampletime_ledit")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_sampletime_ledit, 17, 1, 1, 1)
        self.manual_lockin_measurementstorage_label = QtWidgets.QLabel(self.tab)
        self.manual_lockin_measurementstorage_label.setObjectName("manual_lockin_measurementstorage_label")
        self.gridLayout_2.addWidget(self.manual_lockin_measurementstorage_label, 18, 0, 1, 1)
        self.sr510_manual_lockin_measurementstorage_ledit = QtWidgets.QLineEdit(self.tab)
        self.sr510_manual_lockin_measurementstorage_ledit.setObjectName("sr510_manual_lockin_measurementstorage_ledit")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_measurementstorage_ledit, 19, 0, 1, 2)
        self.sr510_manual_lockin_startmeasurement_button = QtWidgets.QPushButton(self.tab)
        self.sr510_manual_lockin_startmeasurement_button.setObjectName("sr510_manual_lockin_startmeasurement_button")
        self.gridLayout_2.addWidget(self.sr510_manual_lockin_startmeasurement_button, 20, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.manual_lockin_label_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_label_2.sizePolicy().hasHeightForWidth())
        self.manual_lockin_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_label_2.setFont(font)
        self.manual_lockin_label_2.setObjectName("manual_lockin_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_label_2, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 1, 1, 1)
        self.sr830_manual_lockin_sensitivity_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.sr830_manual_lockin_sensitivity_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sr830_manual_lockin_sensitivity_ledit.setFont(font)
        self.sr830_manual_lockin_sensitivity_ledit.setReadOnly(False)
        self.sr830_manual_lockin_sensitivity_ledit.setClearButtonEnabled(False)
        self.sr830_manual_lockin_sensitivity_ledit.setObjectName("sr830_manual_lockin_sensitivity_ledit")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_sensitivity_ledit, 3, 0, 1, 1)
        self.sr830_manual_lockin_timeconstant_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.sr830_manual_lockin_timeconstant_ledit.setEnabled(False)
        self.sr830_manual_lockin_timeconstant_ledit.setReadOnly(False)
        self.sr830_manual_lockin_timeconstant_ledit.setObjectName("sr830_manual_lockin_timeconstant_ledit")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_timeconstant_ledit, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 4, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 5, 0, 1, 2)
        self.manual_lockin_sensitivity_label_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivity_label_2.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivity_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_sensitivity_label_2.setFont(font)
        self.manual_lockin_sensitivity_label_2.setObjectName("manual_lockin_sensitivity_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_sensitivity_label_2, 6, 0, 1, 1)
        self.manual_lockin_timeconstant_label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_timeconstant_label_2.setFont(font)
        self.manual_lockin_timeconstant_label_2.setObjectName("manual_lockin_timeconstant_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_timeconstant_label_2, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 7, 1, 1, 1)
        self.sr830_manual_lockin_sensitivityvalue_cbox = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr830_manual_lockin_sensitivityvalue_cbox.sizePolicy().hasHeightForWidth())
        self.sr830_manual_lockin_sensitivityvalue_cbox.setSizePolicy(sizePolicy)
        self.sr830_manual_lockin_sensitivityvalue_cbox.setObjectName("sr830_manual_lockin_sensitivityvalue_cbox")
        self.sr830_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.sr830_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.sr830_manual_lockin_sensitivityvalue_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_sensitivityvalue_cbox, 8, 0, 1, 1)
        self.sr830_manual_lockin_timeconstantvalue_cbox = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr830_manual_lockin_timeconstantvalue_cbox.sizePolicy().hasHeightForWidth())
        self.sr830_manual_lockin_timeconstantvalue_cbox.setSizePolicy(sizePolicy)
        self.sr830_manual_lockin_timeconstantvalue_cbox.setObjectName("sr830_manual_lockin_timeconstantvalue_cbox")
        self.sr830_manual_lockin_timeconstantvalue_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantvalue_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_timeconstantvalue_cbox, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 1, 1, 1)
        self.sr830_manual_lockin_sensitivitymultiplier_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.setObjectName("sr830_manual_lockin_sensitivitymultiplier_cbox")
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_sensitivitymultiplier_cbox, 10, 0, 1, 1)
        self.sr830_manual_lockin_timeconstantmultiplier_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.setObjectName("sr830_manual_lockin_timeconstantmultiplier_cbox")
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_timeconstantmultiplier_cbox, 10, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 11, 1, 1, 1)
        self.sr830_manual_lockin_sensitivityunit_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sr830_manual_lockin_sensitivityunit_cbox.setObjectName("sr830_manual_lockin_sensitivityunit_cbox")
        self.sr830_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr830_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr830_manual_lockin_sensitivityunit_cbox.addItem("")
        self.sr830_manual_lockin_sensitivityunit_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_sensitivityunit_cbox, 12, 0, 1, 1)
        self.sr830_manual_lockin_timeconstantunit_cbox = QtWidgets.QComboBox(self.tab_2)
        self.sr830_manual_lockin_timeconstantunit_cbox.setObjectName("sr830_manual_lockin_timeconstantunit_cbox")
        self.sr830_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantunit_cbox.addItem("")
        self.sr830_manual_lockin_timeconstantunit_cbox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_timeconstantunit_cbox, 12, 1, 1, 1)
        self.sr830_manual_lockin_setparams_button = QtWidgets.QPushButton(self.tab_2)
        self.sr830_manual_lockin_setparams_button.setObjectName("sr830_manual_lockin_setparams_button")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_setparams_button, 13, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 14, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 15, 0, 1, 1)
        self.manual_lockin_samplerate_label_2 = QtWidgets.QLabel(self.tab_2)
        self.manual_lockin_samplerate_label_2.setObjectName("manual_lockin_samplerate_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_samplerate_label_2, 16, 0, 1, 1)
        self.manual_lockin_sampletime_label_2 = QtWidgets.QLabel(self.tab_2)
        self.manual_lockin_sampletime_label_2.setObjectName("manual_lockin_sampletime_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_sampletime_label_2, 16, 1, 1, 1)
        self.sr830_manual_lockin_samplerate_combobox = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr830_manual_lockin_samplerate_combobox.sizePolicy().hasHeightForWidth())
        self.sr830_manual_lockin_samplerate_combobox.setSizePolicy(sizePolicy)
        self.sr830_manual_lockin_samplerate_combobox.setObjectName("sr830_manual_lockin_samplerate_combobox")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.sr830_manual_lockin_samplerate_combobox.addItem("")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_samplerate_combobox, 17, 0, 1, 1)
        self.sr830_manual_lockin_sampletime_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.sr830_manual_lockin_sampletime_ledit.setObjectName("sr830_manual_lockin_sampletime_ledit")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_sampletime_ledit, 17, 1, 1, 1)
        self.manual_lockin_measurementstorage_label_2 = QtWidgets.QLabel(self.tab_2)
        self.manual_lockin_measurementstorage_label_2.setObjectName("manual_lockin_measurementstorage_label_2")
        self.gridLayout_3.addWidget(self.manual_lockin_measurementstorage_label_2, 18, 0, 1, 1)
        self.sr830_manual_lockin_measurementstorage_ledit = QtWidgets.QLineEdit(self.tab_2)
        self.sr830_manual_lockin_measurementstorage_ledit.setObjectName("sr830_manual_lockin_measurementstorage_ledit")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_measurementstorage_ledit, 19, 0, 1, 2)
        self.sr830_manual_lockin_startmeasurement_button = QtWidgets.QPushButton(self.tab_2)
        self.sr830_manual_lockin_startmeasurement_button.setObjectName("sr830_manual_lockin_startmeasurement_button")
        self.gridLayout_3.addWidget(self.sr830_manual_lockin_startmeasurement_button, 20, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lockin Amplifier(s)"))
        self.sr510_manual_lockin_label.setText(_translate("Form", "SR510 Lock-In:"))
        self.sr510_current_parameters_label.setText(_translate("Form", "Current Parameters:"))
        self.sr510_cursens_label.setText(_translate("Form", "Sensitivity:"))
        self.sr510_curtc_label.setText(_translate("Form", "Time-Constant:"))
        self.sr510_new_parameters_label.setText(_translate("Form", "New Parameters:"))
        self.sr510_manual_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity:"))
        self.sr510_manual_lockin_timeconstant_label.setText(_translate("Form", "Time-Constant:"))
        self.sr510_sens_value_label.setText(_translate("Form", "Value:"))
        self.label_4.setText(_translate("Form", "Value:"))
        self.sr510_manual_lockin_sensitivityvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.sr510_manual_lockin_sensitivityvalue_cbox.setItemText(1, _translate("Form", "2"))
        self.sr510_manual_lockin_sensitivityvalue_cbox.setItemText(2, _translate("Form", "5"))
        self.sr510_manual_lockin_timeconstantvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.sr510_manual_lockin_timeconstantvalue_cbox.setItemText(1, _translate("Form", "3"))
        self.label_3.setText(_translate("Form", "Multiplier:"))
        self.label_5.setText(_translate("Form", "Multiplier:"))
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sr510_manual_lockin_sensitivitymultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sr510_manual_lockin_timeconstantmultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.label_8.setText(_translate("Form", "Units:"))
        self.label_6.setText(_translate("Form", "Units:"))
        self.sr510_manual_lockin_sensitivityunit_cbox.setItemText(0, _translate("Form", "V."))
        self.sr510_manual_lockin_sensitivityunit_cbox.setItemText(1, _translate("Form", "mV."))
        self.sr510_manual_lockin_sensitivityunit_cbox.setItemText(2, _translate("Form", "uV."))
        self.sr510_manual_lockin_sensitivityunit_cbox.setItemText(3, _translate("Form", "nV."))
        self.sr510_manual_lockin_timeconstantunit_cbox.setItemText(0, _translate("Form", "ks."))
        self.sr510_manual_lockin_timeconstantunit_cbox.setItemText(1, _translate("Form", "s."))
        self.sr510_manual_lockin_timeconstantunit_cbox.setItemText(2, _translate("Form", "ms."))
        self.sr510_manual_lockin_timeconstantunit_cbox.setItemText(3, _translate("Form", "us."))
        self.sr510_manual_lockin_setparams_button.setText(_translate("Form", "Set New Parameters"))
        self.label_13.setText(_translate("Form", "Measurement:"))
        self.manual_lockin_samplerate_label.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.manual_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.sr510_manual_lockin_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sr510_manual_lockin_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.manual_lockin_measurementstorage_label.setText(_translate("Form", "Measurement Storage Path:"))
        self.sr510_manual_lockin_startmeasurement_button.setText(_translate("Form", "Start Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "SR510"))
        self.manual_lockin_label_2.setText(_translate("Form", "SR830 Lock-In:"))
        self.label_17.setText(_translate("Form", "Current Parameters:"))
        self.label_14.setText(_translate("Form", "Sensitivity:"))
        self.label_18.setText(_translate("Form", "Time-Constant:"))
        self.label_24.setText(_translate("Form", "New Parameters:"))
        self.manual_lockin_sensitivity_label_2.setText(_translate("Form", "Sensitivity:"))
        self.manual_lockin_timeconstant_label_2.setText(_translate("Form", "Time-Constant:"))
        self.label_23.setText(_translate("Form", "Value:"))
        self.label_21.setText(_translate("Form", "Value:"))
        self.sr830_manual_lockin_sensitivityvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.sr830_manual_lockin_sensitivityvalue_cbox.setItemText(1, _translate("Form", "2"))
        self.sr830_manual_lockin_sensitivityvalue_cbox.setItemText(2, _translate("Form", "5"))
        self.sr830_manual_lockin_timeconstantvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.sr830_manual_lockin_timeconstantvalue_cbox.setItemText(1, _translate("Form", "3"))
        self.label_15.setText(_translate("Form", "Multiplier:"))
        self.label_22.setText(_translate("Form", "Multiplier:"))
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sr830_manual_lockin_sensitivitymultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.sr830_manual_lockin_timeconstantmultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.label_16.setText(_translate("Form", "Units:"))
        self.label_20.setText(_translate("Form", "Units:"))
        self.sr830_manual_lockin_sensitivityunit_cbox.setItemText(0, _translate("Form", "V."))
        self.sr830_manual_lockin_sensitivityunit_cbox.setItemText(1, _translate("Form", "mV."))
        self.sr830_manual_lockin_sensitivityunit_cbox.setItemText(2, _translate("Form", "uV."))
        self.sr830_manual_lockin_sensitivityunit_cbox.setItemText(3, _translate("Form", "nV."))
        self.sr830_manual_lockin_timeconstantunit_cbox.setItemText(0, _translate("Form", "ks."))
        self.sr830_manual_lockin_timeconstantunit_cbox.setItemText(1, _translate("Form", "s."))
        self.sr830_manual_lockin_timeconstantunit_cbox.setItemText(2, _translate("Form", "ms."))
        self.sr830_manual_lockin_timeconstantunit_cbox.setItemText(3, _translate("Form", "us."))
        self.sr830_manual_lockin_setparams_button.setText(_translate("Form", "Set New Parameters"))
        self.label_19.setText(_translate("Form", "Measurement:"))
        self.manual_lockin_samplerate_label_2.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.manual_lockin_sampletime_label_2.setText(_translate("Form", "Sample Time (s.):"))
        self.sr830_manual_lockin_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sr830_manual_lockin_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.manual_lockin_measurementstorage_label_2.setText(_translate("Form", "Measurement Storage Path:"))
        self.sr830_manual_lockin_startmeasurement_button.setText(_translate("Form", "Start Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "SR830"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

