# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockinAutoWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1336, 1462)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.sequence_sr510_senstransition_removeall_button = QtWidgets.QPushButton(Form)
        self.sequence_sr510_senstransition_removeall_button.setObjectName("sequence_sr510_senstransition_removeall_button")
        self.gridLayout.addWidget(self.sequence_sr510_senstransition_removeall_button, 22, 2, 1, 3)
        self.sequence_sr830_timeconstant_label = QtWidgets.QLabel(Form)
        self.sequence_sr830_timeconstant_label.setObjectName("sequence_sr830_timeconstant_label")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_label, 3, 2, 1, 1)
        self.sequence_sr830_senstransitions_list = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_senstransitions_list.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_senstransitions_list.setSizePolicy(sizePolicy)
        self.sequence_sr830_senstransitions_list.setObjectName("sequence_sr830_senstransitions_list")
        self.gridLayout.addWidget(self.sequence_sr830_senstransitions_list, 5, 2, 1, 3)
        self.sequence_sr830_samplerate_combobox = QtWidgets.QComboBox(Form)
        self.sequence_sr830_samplerate_combobox.setObjectName("sequence_sr830_samplerate_combobox")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.sequence_sr830_samplerate_combobox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr830_samplerate_combobox, 2, 3, 1, 2)
        self.sequence_sr830_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_sr830_label.setFont(font)
        self.sequence_sr830_label.setObjectName("sequence_sr830_label")
        self.gridLayout.addWidget(self.sequence_sr830_label, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 1, 3)
        self.sequence_sr830_samplefreq_label = QtWidgets.QLabel(Form)
        self.sequence_sr830_samplefreq_label.setObjectName("sequence_sr830_samplefreq_label")
        self.gridLayout.addWidget(self.sequence_sr830_samplefreq_label, 2, 2, 1, 1)
        self.sequence_sr510_senstransitions_list = QtWidgets.QListWidget(Form)
        self.sequence_sr510_senstransitions_list.setObjectName("sequence_sr510_senstransitions_list")
        self.gridLayout.addWidget(self.sequence_sr510_senstransitions_list, 17, 2, 1, 3)
        self.sequence_sr510_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr510_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr510_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_sr510_label.setFont(font)
        self.sequence_sr510_label.setObjectName("sequence_sr510_label")
        self.gridLayout.addWidget(self.sequence_sr510_label, 11, 2, 1, 2)
        self.sequence_sr510_senstransition_add_button = QtWidgets.QPushButton(Form)
        self.sequence_sr510_senstransition_add_button.setObjectName("sequence_sr510_senstransition_add_button")
        self.gridLayout.addWidget(self.sequence_sr510_senstransition_add_button, 20, 2, 1, 3)
        self.sequence_lockin_sampletime_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_lockin_sampletime_label.setFont(font)
        self.sequence_lockin_sampletime_label.setObjectName("sequence_lockin_sampletime_label")
        self.gridLayout.addWidget(self.sequence_lockin_sampletime_label, 24, 2, 1, 1)
        self.sequence_sr830_senstransition_add_button = QtWidgets.QPushButton(Form)
        self.sequence_sr830_senstransition_add_button.setObjectName("sequence_sr830_senstransition_add_button")
        self.gridLayout.addWidget(self.sequence_sr830_senstransition_add_button, 8, 2, 1, 3)
        self.sequence_lockin_sampletime_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_lockin_sampletime_ledit.setObjectName("sequence_lockin_sampletime_ledit")
        self.gridLayout.addWidget(self.sequence_lockin_sampletime_ledit, 24, 3, 1, 2)
        self.sequence_sr510_senstransitions_label = QtWidgets.QLabel(Form)
        self.sequence_sr510_senstransitions_label.setObjectName("sequence_sr510_senstransitions_label")
        self.gridLayout.addWidget(self.sequence_sr510_senstransitions_label, 16, 2, 1, 2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 23, 2, 1, 3)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 12, 2, 1, 3)
        self.sequence_sr830_senstransitions_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_senstransitions_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_senstransitions_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sequence_sr830_senstransitions_label.setFont(font)
        self.sequence_sr830_senstransitions_label.setObjectName("sequence_sr830_senstransitions_label")
        self.gridLayout.addWidget(self.sequence_sr830_senstransitions_label, 4, 2, 1, 1)
        self.sequence_sr830_timeconstant_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr830_timeconstant_ledit.setObjectName("sequence_sr830_timeconstant_ledit")
        self.gridLayout.addWidget(self.sequence_sr830_timeconstant_ledit, 3, 3, 1, 2)
        self.sequence_sr510_senstransition_remove_button = QtWidgets.QPushButton(Form)
        self.sequence_sr510_senstransition_remove_button.setObjectName("sequence_sr510_senstransition_remove_button")
        self.gridLayout.addWidget(self.sequence_sr510_senstransition_remove_button, 21, 2, 1, 3)
        self.sequence_sr830_sens_transition_remove_button = QtWidgets.QPushButton(Form)
        self.sequence_sr830_sens_transition_remove_button.setObjectName("sequence_sr830_sens_transition_remove_button")
        self.gridLayout.addWidget(self.sequence_sr830_sens_transition_remove_button, 9, 2, 1, 3)
        self.sequence_sr830_sens_transition_removeall_button = QtWidgets.QPushButton(Form)
        self.sequence_sr830_sens_transition_removeall_button.setObjectName("sequence_sr830_sens_transition_removeall_button")
        self.gridLayout.addWidget(self.sequence_sr830_sens_transition_removeall_button, 10, 2, 1, 3)
        self.sequence_sr830_wave_label = QtWidgets.QLabel(Form)
        self.sequence_sr830_wave_label.setObjectName("sequence_sr830_wave_label")
        self.gridLayout.addWidget(self.sequence_sr830_wave_label, 6, 2, 1, 1)
        self.sequence_sr830_wave_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr830_wave_ledit.setObjectName("sequence_sr830_wave_ledit")
        self.gridLayout.addWidget(self.sequence_sr830_wave_ledit, 7, 2, 1, 1)
        self.sequence_sr510_wave_label = QtWidgets.QLabel(Form)
        self.sequence_sr510_wave_label.setObjectName("sequence_sr510_wave_label")
        self.gridLayout.addWidget(self.sequence_sr510_wave_label, 18, 2, 1, 1)
        self.sequence_sr510_wave_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr510_wave_ledit.setObjectName("sequence_sr510_wave_ledit")
        self.gridLayout.addWidget(self.sequence_sr510_wave_ledit, 19, 2, 1, 1)
        self.sequence_sr830_sens_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_sr830_sens_label.sizePolicy().hasHeightForWidth())
        self.sequence_sr830_sens_label.setSizePolicy(sizePolicy)
        self.sequence_sr830_sens_label.setObjectName("sequence_sr830_sens_label")
        self.gridLayout.addWidget(self.sequence_sr830_sens_label, 6, 3, 1, 1)
        self.sequence_sr830_sens_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr830_sens_ledit.setObjectName("sequence_sr830_sens_ledit")
        self.gridLayout.addWidget(self.sequence_sr830_sens_ledit, 7, 3, 1, 1)
        self.sequence_sr510_sens_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr510_sens_ledit.setObjectName("sequence_sr510_sens_ledit")
        self.gridLayout.addWidget(self.sequence_sr510_sens_ledit, 19, 3, 1, 2)
        self.sequence_sr510_sens_label = QtWidgets.QLabel(Form)
        self.sequence_sr510_sens_label.setObjectName("sequence_sr510_sens_label")
        self.gridLayout.addWidget(self.sequence_sr510_sens_label, 18, 3, 1, 2)
        self.sequence_sr510_timeconstant_label = QtWidgets.QLabel(Form)
        self.sequence_sr510_timeconstant_label.setObjectName("sequence_sr510_timeconstant_label")
        self.gridLayout.addWidget(self.sequence_sr510_timeconstant_label, 15, 2, 1, 1)
        self.sequence_sr510_samplefreq_label = QtWidgets.QLabel(Form)
        self.sequence_sr510_samplefreq_label.setObjectName("sequence_sr510_samplefreq_label")
        self.gridLayout.addWidget(self.sequence_sr510_samplefreq_label, 13, 2, 1, 1)
        self.sequence_sr510_samplerate_combobox = QtWidgets.QComboBox(Form)
        self.sequence_sr510_samplerate_combobox.setObjectName("sequence_sr510_samplerate_combobox")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.sequence_sr510_samplerate_combobox.addItem("")
        self.gridLayout.addWidget(self.sequence_sr510_samplerate_combobox, 13, 3, 1, 2)
        self.sequence_sr510_timeconstant_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_sr510_timeconstant_ledit.setObjectName("sequence_sr510_timeconstant_ledit")
        self.gridLayout.addWidget(self.sequence_sr510_timeconstant_ledit, 15, 3, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "lockin_sequence_control"))
        self.sequence_sr510_senstransition_removeall_button.setText(_translate("Form", "Remove All SR510 Transitions from Sequence"))
        self.sequence_sr830_timeconstant_label.setText(_translate("Form", "Time Constant (s.):"))
        self.sequence_sr830_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sequence_sr830_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sequence_sr830_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sequence_sr830_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sequence_sr830_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sequence_sr830_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sequence_sr830_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sequence_sr830_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sequence_sr830_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sequence_sr830_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sequence_sr830_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sequence_sr830_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sequence_sr830_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sequence_sr830_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sequence_sr830_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.sequence_sr830_label.setText(_translate("Form", "SR830 Lock-In Sequence Control:"))
        self.sequence_sr830_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.sequence_sr510_label.setText(_translate("Form", "SR510 Lock-In Sequence Control:"))
        self.sequence_sr510_senstransition_add_button.setText(_translate("Form", "Add SR510 Sensitivity Transition to Sequence"))
        self.sequence_lockin_sampletime_label.setText(_translate("Form", "Sequence Sample Time (s.):"))
        self.sequence_sr830_senstransition_add_button.setText(_translate("Form", "Add SR830 Sensitivity Transition to Sequence"))
        self.sequence_sr510_senstransitions_label.setText(_translate("Form", "SR510 Sensitivity Transitions in Sequence:"))
        self.sequence_sr830_senstransitions_label.setText(_translate("Form", "SR830 Sensitivity Transitions in Sequence:"))
        self.sequence_sr510_senstransition_remove_button.setText(_translate("Form", "Remove SR510 Sensitivity Transition from Sequence"))
        self.sequence_sr830_sens_transition_remove_button.setText(_translate("Form", "Remove SR830 Sensitivity Transitions from Sequence"))
        self.sequence_sr830_sens_transition_removeall_button.setText(_translate("Form", "Remove All SR830 Transitions from Sequence"))
        self.sequence_sr830_wave_label.setText(_translate("Form", "Wavelength:"))
        self.sequence_sr510_wave_label.setText(_translate("Form", "Wavelength:"))
        self.sequence_sr830_sens_label.setText(_translate("Form", "Sensitivity:"))
        self.sequence_sr510_sens_label.setText(_translate("Form", "Sensitivity:"))
        self.sequence_sr510_timeconstant_label.setText(_translate("Form", "Time Constant (s.):"))
        self.sequence_sr510_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.sequence_sr510_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.sequence_sr510_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.sequence_sr510_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.sequence_sr510_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.sequence_sr510_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.sequence_sr510_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.sequence_sr510_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.sequence_sr510_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.sequence_sr510_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.sequence_sr510_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.sequence_sr510_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.sequence_sr510_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.sequence_sr510_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.sequence_sr510_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.sequence_sr510_samplerate_combobox.setItemText(13, _translate("Form", "512"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

