# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockinWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1470, 1356)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 1)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity = QtWidgets.QLineEdit(self.tab)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity.setFont(font)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity.setReadOnly(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity.setClearButtonEnabled(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity.setObjectName("lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity")
        self.gridLayout_2.addWidget(self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentSensitivity, 3, 0, 1, 1)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant = QtWidgets.QLineEdit(self.tab)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant.setEnabled(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant.setReadOnly(False)
        self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant.setObjectName("lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant")
        self.gridLayout_2.addWidget(self.lineedit_base_Sr510CurrentConfigParameters_passive_Sr510CurrentTimeConstant, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 1, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.sizePolicy().hasHeightForWidth())
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.setSizePolicy(sizePolicy)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue, 8, 0, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.sizePolicy().hasHeightForWidth())
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.setSizePolicy(sizePolicy)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 1, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier = QtWidgets.QComboBox(self.tab)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier, 10, 0, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier = QtWidgets.QComboBox(self.tab)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 11, 1, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits = QtWidgets.QComboBox(self.tab)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits, 12, 0, 1, 1)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits = QtWidgets.QComboBox(self.tab)
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.setObjectName("combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.addItem("")
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits, 12, 1, 1, 1)
        self.button_base_Sr510NewConfigParameters_getter_Sr510NewConfigButton = QtWidgets.QPushButton(self.tab)
        self.button_base_Sr510NewConfigParameters_getter_Sr510NewConfigButton.setObjectName("button_base_Sr510NewConfigParameters_getter_Sr510NewConfigButton")
        self.gridLayout_2.addWidget(self.button_base_Sr510NewConfigParameters_getter_Sr510NewConfigButton, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 14, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 15, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 16, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 16, 1, 1, 1)
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.sizePolicy().hasHeightForWidth())
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setSizePolicy(sizePolicy)
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setObjectName("combobox_base_Sr510MeasurementParameters_passive_SampleRate")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.addItem("")
        self.gridLayout_2.addWidget(self.combobox_base_Sr510MeasurementParameters_passive_SampleRate, 17, 0, 1, 1)
        self.lineedit_base_Sr510MeasurementParameters_passive_SampleTime = QtWidgets.QLineEdit(self.tab)
        self.lineedit_base_Sr510MeasurementParameters_passive_SampleTime.setObjectName("lineedit_base_Sr510MeasurementParameters_passive_SampleTime")
        self.gridLayout_2.addWidget(self.lineedit_base_Sr510MeasurementParameters_passive_SampleTime, 17, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 18, 0, 1, 1)
        self.lineedit_base_Sr510MeasurementParameters_passive_MeasurementStoragePath = QtWidgets.QLineEdit(self.tab)
        self.lineedit_base_Sr510MeasurementParameters_passive_MeasurementStoragePath.setObjectName("lineedit_base_Sr510MeasurementParameters_passive_MeasurementStoragePath")
        self.gridLayout_2.addWidget(self.lineedit_base_Sr510MeasurementParameters_passive_MeasurementStoragePath, 19, 0, 1, 2)
        self.button_base_Sr510MeasurementParameters_getter_Sr510StartMeasurementButton = QtWidgets.QPushButton(self.tab)
        self.button_base_Sr510MeasurementParameters_getter_Sr510StartMeasurementButton.setObjectName("button_base_Sr510MeasurementParameters_getter_Sr510StartMeasurementButton")
        self.gridLayout_2.addWidget(self.button_base_Sr510MeasurementParameters_getter_Sr510StartMeasurementButton, 20, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 1, 1, 1)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity = QtWidgets.QLineEdit(self.tab_2)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity.setFont(font)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity.setReadOnly(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity.setClearButtonEnabled(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity.setObjectName("lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentSensitivity, 3, 0, 1, 1)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant = QtWidgets.QLineEdit(self.tab_2)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant.setEnabled(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant.setReadOnly(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant.setObjectName("lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830CurrentConfigParameters_passive_Sr830CurrentTimeConstant, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 4, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 5, 0, 1, 2)
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 6, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 7, 1, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.sizePolicy().hasHeightForWidth())
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.setSizePolicy(sizePolicy)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue, 8, 0, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.sizePolicy().hasHeightForWidth())
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.setSizePolicy(sizePolicy)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 1, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier = QtWidgets.QComboBox(self.tab_2)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier, 10, 0, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier = QtWidgets.QComboBox(self.tab_2)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier, 10, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 11, 1, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits = QtWidgets.QComboBox(self.tab_2)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits, 12, 0, 1, 1)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits = QtWidgets.QComboBox(self.tab_2)
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.setObjectName("lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.addItem("")
        self.gridLayout_3.addWidget(self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits, 12, 1, 1, 1)
        self.button_base_Sr830NewConfigParameters_getter_Sr830SetNewParametersButton = QtWidgets.QPushButton(self.tab_2)
        self.button_base_Sr830NewConfigParameters_getter_Sr830SetNewParametersButton.setObjectName("button_base_Sr830NewConfigParameters_getter_Sr830SetNewParametersButton")
        self.gridLayout_3.addWidget(self.button_base_Sr830NewConfigParameters_getter_Sr830SetNewParametersButton, 13, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 14, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 15, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 16, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 16, 1, 1, 1)
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.sizePolicy().hasHeightForWidth())
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setSizePolicy(sizePolicy)
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setObjectName("combobox_base_Sr830MeasurementParameters_passive_SampleRate")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.addItem("")
        self.gridLayout_3.addWidget(self.combobox_base_Sr830MeasurementParameters_passive_SampleRate, 17, 0, 1, 1)
        self.combobox_base_Sr830MeasurementParameters_passive_SampleTime = QtWidgets.QLineEdit(self.tab_2)
        self.combobox_base_Sr830MeasurementParameters_passive_SampleTime.setObjectName("combobox_base_Sr830MeasurementParameters_passive_SampleTime")
        self.gridLayout_3.addWidget(self.combobox_base_Sr830MeasurementParameters_passive_SampleTime, 17, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 18, 0, 1, 1)
        self.combobox_base_Sr830MeasurementParameters_passive_MeasurementStoragePath = QtWidgets.QLineEdit(self.tab_2)
        self.combobox_base_Sr830MeasurementParameters_passive_MeasurementStoragePath.setObjectName("combobox_base_Sr830MeasurementParameters_passive_MeasurementStoragePath")
        self.gridLayout_3.addWidget(self.combobox_base_Sr830MeasurementParameters_passive_MeasurementStoragePath, 19, 0, 1, 2)
        self.button_base_Sr830MeasurementParameters_getter_Sr830StartMeasurement = QtWidgets.QPushButton(self.tab_2)
        self.button_base_Sr830MeasurementParameters_getter_Sr830StartMeasurement.setObjectName("button_base_Sr830MeasurementParameters_getter_Sr830StartMeasurement")
        self.gridLayout_3.addWidget(self.button_base_Sr830MeasurementParameters_getter_Sr830StartMeasurement, 20, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lockin Amplifier(s)"))
        self.label.setText(_translate("Form", "SR510 Lock-In:"))
        self.label_2.setText(_translate("Form", "Current Parameters:"))
        self.label_7.setText(_translate("Form", "Sensitivity:"))
        self.label_9.setText(_translate("Form", "Time-Constant:"))
        self.label_10.setText(_translate("Form", "New Parameters:"))
        self.label_11.setText(_translate("Form", "Sensitivity:"))
        self.label_12.setText(_translate("Form", "Time-Constant:"))
        self.label_25.setText(_translate("Form", "Value:"))
        self.label_4.setText(_translate("Form", "Value:"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.setItemText(0, _translate("Form", "1"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.setItemText(1, _translate("Form", "2"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityValue.setItemText(2, _translate("Form", "5"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.setItemText(0, _translate("Form", "1"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantValue.setItemText(1, _translate("Form", "3"))
        self.label_3.setText(_translate("Form", "Multiplier:"))
        self.label_5.setText(_translate("Form", "Multiplier:"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.setItemText(0, _translate("Form", "x1"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.setItemText(1, _translate("Form", "x10"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityMultiplier.setItemText(2, _translate("Form", "x100"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.setItemText(0, _translate("Form", "x1"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.setItemText(1, _translate("Form", "x10"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantMultiplier.setItemText(2, _translate("Form", "x100"))
        self.label_8.setText(_translate("Form", "Units:"))
        self.label_6.setText(_translate("Form", "Units:"))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.setItemText(0, _translate("Form", "V."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.setItemText(1, _translate("Form", "mV."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.setItemText(2, _translate("Form", "uV."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewSensitivityUnits.setItemText(3, _translate("Form", "nV."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.setItemText(0, _translate("Form", "ks."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.setItemText(1, _translate("Form", "s."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.setItemText(2, _translate("Form", "ms."))
        self.combobox_base_Sr510NewConfigParameters_passive_Sr510NewTimeConstantUnits.setItemText(3, _translate("Form", "us."))
        self.button_base_Sr510NewConfigParameters_getter_Sr510NewConfigButton.setText(_translate("Form", "Set New Parameters"))
        self.label_13.setText(_translate("Form", "Measurement:"))
        self.label_26.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.label_27.setText(_translate("Form", "Sample Time (s.):"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setCurrentText(_translate("Form", "0.0625"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(0, _translate("Form", "0.0625"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(1, _translate("Form", "0.125"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(2, _translate("Form", "0.250"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(3, _translate("Form", "0.5"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(4, _translate("Form", "1"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(5, _translate("Form", "2"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(6, _translate("Form", "4"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(7, _translate("Form", "8"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(8, _translate("Form", "16"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(9, _translate("Form", "32"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(10, _translate("Form", "64"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(11, _translate("Form", "128"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(12, _translate("Form", "256"))
        self.combobox_base_Sr510MeasurementParameters_passive_SampleRate.setItemText(13, _translate("Form", "512"))
        self.label_28.setText(_translate("Form", "Measurement Storage Path:"))
        self.button_base_Sr510MeasurementParameters_getter_Sr510StartMeasurementButton.setText(_translate("Form", "Start Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "SR510"))
        self.label_29.setText(_translate("Form", "SR830 Lock-In:"))
        self.label_17.setText(_translate("Form", "Current Parameters:"))
        self.label_14.setText(_translate("Form", "Sensitivity:"))
        self.label_18.setText(_translate("Form", "Time-Constant:"))
        self.label_24.setText(_translate("Form", "New Parameters:"))
        self.label_30.setText(_translate("Form", "Sensitivity:"))
        self.label_31.setText(_translate("Form", "Time-Constant:"))
        self.label_23.setText(_translate("Form", "Value:"))
        self.label_21.setText(_translate("Form", "Value:"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.setItemText(0, _translate("Form", "1"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.setItemText(1, _translate("Form", "2"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityValue.setItemText(2, _translate("Form", "5"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.setItemText(0, _translate("Form", "1"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantValue.setItemText(1, _translate("Form", "3"))
        self.label_15.setText(_translate("Form", "Multiplier:"))
        self.label_22.setText(_translate("Form", "Multiplier:"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.setItemText(0, _translate("Form", "x1"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.setItemText(1, _translate("Form", "x10"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityMultiplier.setItemText(2, _translate("Form", "x100"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.setItemText(0, _translate("Form", "x1"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.setItemText(1, _translate("Form", "x10"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantMultiplier.setItemText(2, _translate("Form", "x100"))
        self.label_16.setText(_translate("Form", "Units:"))
        self.label_20.setText(_translate("Form", "Units:"))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.setItemText(0, _translate("Form", "V."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.setItemText(1, _translate("Form", "mV."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.setItemText(2, _translate("Form", "uV."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewSensitivityUnits.setItemText(3, _translate("Form", "nV."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.setItemText(0, _translate("Form", "ks."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.setItemText(1, _translate("Form", "s."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.setItemText(2, _translate("Form", "ms."))
        self.lineedit_base_Sr830NewConfigParameters_passive_Sr830NewTimeConstantUnits.setItemText(3, _translate("Form", "us."))
        self.button_base_Sr830NewConfigParameters_getter_Sr830SetNewParametersButton.setText(_translate("Form", "Set New Parameters"))
        self.label_19.setText(_translate("Form", "Measurement:"))
        self.label_32.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.label_33.setText(_translate("Form", "Sample Time (s.):"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setCurrentText(_translate("Form", "0.0625"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(0, _translate("Form", "0.0625"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(1, _translate("Form", "0.125"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(2, _translate("Form", "0.250"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(3, _translate("Form", "0.5"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(4, _translate("Form", "1"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(5, _translate("Form", "2"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(6, _translate("Form", "4"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(7, _translate("Form", "8"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(8, _translate("Form", "16"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(9, _translate("Form", "32"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(10, _translate("Form", "64"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(11, _translate("Form", "128"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(12, _translate("Form", "256"))
        self.combobox_base_Sr830MeasurementParameters_passive_SampleRate.setItemText(13, _translate("Form", "512"))
        self.label_34.setText(_translate("Form", "Measurement Storage Path:"))
        self.button_base_Sr830MeasurementParameters_getter_Sr830StartMeasurement.setText(_translate("Form", "Start Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "SR830"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

