# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockinWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1505, 1359)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.manual_lockin_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_label.setFont(font)
        self.manual_lockin_label.setObjectName("manual_lockin_label")
        self.gridLayout.addWidget(self.manual_lockin_label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.manual_lockin_sensitivity_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_sensitivity_ledit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.manual_lockin_sensitivity_ledit.setFont(font)
        self.manual_lockin_sensitivity_ledit.setReadOnly(False)
        self.manual_lockin_sensitivity_ledit.setClearButtonEnabled(False)
        self.manual_lockin_sensitivity_ledit.setObjectName("manual_lockin_sensitivity_ledit")
        self.gridLayout.addWidget(self.manual_lockin_sensitivity_ledit, 3, 0, 1, 1)
        self.manual_lockin_timeconstant_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_timeconstant_ledit.setEnabled(False)
        self.manual_lockin_timeconstant_ledit.setReadOnly(False)
        self.manual_lockin_timeconstant_ledit.setObjectName("manual_lockin_timeconstant_ledit")
        self.gridLayout.addWidget(self.manual_lockin_timeconstant_ledit, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 2)
        self.manual_lockin_sensitivity_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivity_label.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_sensitivity_label.setFont(font)
        self.manual_lockin_sensitivity_label.setObjectName("manual_lockin_sensitivity_label")
        self.gridLayout.addWidget(self.manual_lockin_sensitivity_label, 6, 0, 1, 1)
        self.manual_lockin_timeconstant_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.manual_lockin_timeconstant_label.setFont(font)
        self.manual_lockin_timeconstant_label.setObjectName("manual_lockin_timeconstant_label")
        self.gridLayout.addWidget(self.manual_lockin_timeconstant_label, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 1, 1, 1)
        self.manual_lockin_sensitivityvalue_cbox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_sensitivityvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_sensitivityvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_sensitivityvalue_cbox.setObjectName("manual_lockin_sensitivityvalue_cbox")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.manual_lockin_sensitivityvalue_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivityvalue_cbox, 8, 0, 1, 1)
        self.manual_lockin_timeconstantvalue_cbox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_timeconstantvalue_cbox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_timeconstantvalue_cbox.setSizePolicy(sizePolicy)
        self.manual_lockin_timeconstantvalue_cbox.setObjectName("manual_lockin_timeconstantvalue_cbox")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.manual_lockin_timeconstantvalue_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantvalue_cbox, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 1, 1, 1)
        self.manual_lockin_sensitivitymultiplier_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_sensitivitymultiplier_cbox.setObjectName("manual_lockin_sensitivitymultiplier_cbox")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.manual_lockin_sensitivitymultiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivitymultiplier_cbox, 10, 0, 1, 1)
        self.manual_lockin_timeconstantmultiplier_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_timeconstantmultiplier_cbox.setObjectName("manual_lockin_timeconstantmultiplier_cbox")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.manual_lockin_timeconstantmultiplier_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantmultiplier_cbox, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 1, 1, 1)
        self.manual_lockin_sensitivityunit_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_sensitivityunit_cbox.setObjectName("manual_lockin_sensitivityunit_cbox")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.manual_lockin_sensitivityunit_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_sensitivityunit_cbox, 12, 0, 1, 1)
        self.manual_lockin_timeconstantunit_cbox = QtWidgets.QComboBox(Form)
        self.manual_lockin_timeconstantunit_cbox.setObjectName("manual_lockin_timeconstantunit_cbox")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.manual_lockin_timeconstantunit_cbox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_timeconstantunit_cbox, 12, 1, 1, 1)
        self.manual_lockin_setparams_button = QtWidgets.QPushButton(Form)
        self.manual_lockin_setparams_button.setObjectName("manual_lockin_setparams_button")
        self.gridLayout.addWidget(self.manual_lockin_setparams_button, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 14, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 15, 0, 1, 1)
        self.manual_lockin_samplerate_label = QtWidgets.QLabel(Form)
        self.manual_lockin_samplerate_label.setObjectName("manual_lockin_samplerate_label")
        self.gridLayout.addWidget(self.manual_lockin_samplerate_label, 16, 0, 1, 1)
        self.manual_lockin_sampletime_label = QtWidgets.QLabel(Form)
        self.manual_lockin_sampletime_label.setObjectName("manual_lockin_sampletime_label")
        self.gridLayout.addWidget(self.manual_lockin_sampletime_label, 16, 1, 1, 1)
        self.manual_lockin_samplerate_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_lockin_samplerate_combobox.sizePolicy().hasHeightForWidth())
        self.manual_lockin_samplerate_combobox.setSizePolicy(sizePolicy)
        self.manual_lockin_samplerate_combobox.setObjectName("manual_lockin_samplerate_combobox")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.manual_lockin_samplerate_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_lockin_samplerate_combobox, 17, 0, 1, 1)
        self.manual_lockin_sampletime_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_sampletime_ledit.setObjectName("manual_lockin_sampletime_ledit")
        self.gridLayout.addWidget(self.manual_lockin_sampletime_ledit, 17, 1, 1, 1)
        self.manual_lockin_measurementstorage_label = QtWidgets.QLabel(Form)
        self.manual_lockin_measurementstorage_label.setObjectName("manual_lockin_measurementstorage_label")
        self.gridLayout.addWidget(self.manual_lockin_measurementstorage_label, 18, 0, 1, 1)
        self.manual_lockin_measurementstorage_ledit = QtWidgets.QLineEdit(Form)
        self.manual_lockin_measurementstorage_ledit.setObjectName("manual_lockin_measurementstorage_ledit")
        self.gridLayout.addWidget(self.manual_lockin_measurementstorage_ledit, 19, 0, 1, 2)
        self.manual_lockin_startmeasurement_button = QtWidgets.QPushButton(Form)
        self.manual_lockin_startmeasurement_button.setObjectName("manual_lockin_startmeasurement_button")
        self.gridLayout.addWidget(self.manual_lockin_startmeasurement_button, 20, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lockin"))
        self.manual_lockin_label.setText(_translate("Form", "Lock-In:"))
        self.label_9.setText(_translate("Form", "Current Parameters:"))
        self.label_10.setText(_translate("Form", "Sensitivity:"))
        self.label_11.setText(_translate("Form", "Time-Constant:"))
        self.label_12.setText(_translate("Form", "New Parameters:"))
        self.manual_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity:"))
        self.manual_lockin_timeconstant_label.setText(_translate("Form", "Time-Constant:"))
        self.label_7.setText(_translate("Form", "Value:"))
        self.label_4.setText(_translate("Form", "Value:"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(1, _translate("Form", "2"))
        self.manual_lockin_sensitivityvalue_cbox.setItemText(2, _translate("Form", "5"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(0, _translate("Form", "1"))
        self.manual_lockin_timeconstantvalue_cbox.setItemText(1, _translate("Form", "3"))
        self.label_3.setText(_translate("Form", "Multiplier:"))
        self.label_5.setText(_translate("Form", "Multiplier:"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_sensitivitymultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(0, _translate("Form", "x1"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(1, _translate("Form", "x10"))
        self.manual_lockin_timeconstantmultiplier_cbox.setItemText(2, _translate("Form", "x100"))
        self.label_8.setText(_translate("Form", "Units:"))
        self.label_6.setText(_translate("Form", "Units:"))
        self.manual_lockin_sensitivityunit_cbox.setItemText(0, _translate("Form", "V."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(1, _translate("Form", "mV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(2, _translate("Form", "uV."))
        self.manual_lockin_sensitivityunit_cbox.setItemText(3, _translate("Form", "nV."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(0, _translate("Form", "ks."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(1, _translate("Form", "s."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(2, _translate("Form", "ms."))
        self.manual_lockin_timeconstantunit_cbox.setItemText(3, _translate("Form", "us."))
        self.manual_lockin_setparams_button.setText(_translate("Form", "Set New Parameters"))
        self.label_13.setText(_translate("Form", "Measurement:"))
        self.manual_lockin_samplerate_label.setText(_translate("Form", "Sample Rate (Hz.):"))
        self.manual_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.manual_lockin_samplerate_combobox.setCurrentText(_translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(0, _translate("Form", "0.0625"))
        self.manual_lockin_samplerate_combobox.setItemText(1, _translate("Form", "0.125"))
        self.manual_lockin_samplerate_combobox.setItemText(2, _translate("Form", "0.250"))
        self.manual_lockin_samplerate_combobox.setItemText(3, _translate("Form", "0.5"))
        self.manual_lockin_samplerate_combobox.setItemText(4, _translate("Form", "1"))
        self.manual_lockin_samplerate_combobox.setItemText(5, _translate("Form", "2"))
        self.manual_lockin_samplerate_combobox.setItemText(6, _translate("Form", "4"))
        self.manual_lockin_samplerate_combobox.setItemText(7, _translate("Form", "8"))
        self.manual_lockin_samplerate_combobox.setItemText(8, _translate("Form", "16"))
        self.manual_lockin_samplerate_combobox.setItemText(9, _translate("Form", "32"))
        self.manual_lockin_samplerate_combobox.setItemText(10, _translate("Form", "64"))
        self.manual_lockin_samplerate_combobox.setItemText(11, _translate("Form", "128"))
        self.manual_lockin_samplerate_combobox.setItemText(12, _translate("Form", "256"))
        self.manual_lockin_samplerate_combobox.setItemText(13, _translate("Form", "512"))
        self.manual_lockin_measurementstorage_label.setText(_translate("Form", "Measurement Storage Path:"))
        self.manual_lockin_startmeasurement_button.setText(_translate("Form", "Start Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

