# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonochromatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 550)
        self.gridLayout_12 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 3, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_5.addWidget(self.checkBox_15, 0, 2, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_5.addWidget(self.lineEdit_29, 4, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_5.addWidget(self.checkBox_16, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 3, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_5.addWidget(self.lineEdit_30, 2, 2, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_5.addWidget(self.checkBox_17, 0, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_5.addWidget(self.lineEdit_31, 2, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_5.addWidget(self.lineEdit_32, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 3, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 3, 2, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_5.addWidget(self.lineEdit_33, 4, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_5.addWidget(self.lineEdit_34, 4, 3, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_4.addWidget(self.checkBox_11, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_4.addWidget(self.lineEdit_21, 2, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_4.addWidget(self.checkBox_12, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_4.addWidget(self.lineEdit_22, 2, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_13.sizePolicy().hasHeightForWidth())
        self.checkBox_13.setSizePolicy(sizePolicy)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_4.addWidget(self.checkBox_13, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 3, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_4.addWidget(self.lineEdit_23, 2, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_14.sizePolicy().hasHeightForWidth())
        self.checkBox_14.setSizePolicy(sizePolicy)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_4.addWidget(self.checkBox_14, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_4.addWidget(self.lineEdit_24, 2, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 1, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_4.addWidget(self.lineEdit_25, 4, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_4.addWidget(self.lineEdit_26, 4, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_4.addWidget(self.lineEdit_27, 4, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_4.addWidget(self.lineEdit_28, 4, 3, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_6.addWidget(self.lineEdit_6, 1, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_6.addWidget(self.lineEdit_35, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 2, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_6.addWidget(self.lineEdit_36, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 3, 0, 1, 4)
        self.gridLayout_10.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_37.setEnabled(False)
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_7.addWidget(self.lineEdit_37, 2, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_38.setEnabled(False)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_7.addWidget(self.lineEdit_38, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 7, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_39.setEnabled(False)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_7.addWidget(self.lineEdit_39, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 5, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_40.setEnabled(False)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_7.addWidget(self.lineEdit_40, 8, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 7, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_8.addWidget(self.lineEdit_41, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 6, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_3, 8, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 5, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.gridLayout_13.addWidget(self.label_47, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_4, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_13, 1, 0, 1, 2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_14.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_14.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_30.setText(_translate("Dialog", "G2 Min. Wavelength:"))
        self.label_31.setText(_translate("Dialog", "G1 Max Wavelength:"))
        self.checkBox_15.setText(_translate("Dialog", "Use Grating 2 (G2)"))
        self.checkBox_16.setText(_translate("Dialog", "Use Grating 3 (G3)"))
        self.label_32.setText(_translate("Dialog", "G3 Min. Wavelength:"))
        self.checkBox_17.setText(_translate("Dialog", "Use Grating 1 (G1)"))
        self.label_33.setText(_translate("Dialog", "G3 Max. Wavelength:"))
        self.label_34.setText(_translate("Dialog", "G1 Min Wavelength:"))
        self.label_35.setText(_translate("Dialog", "G2 Max Wavelength:"))
        self.checkBox_11.setText(_translate("Dialog", "Use OSF3"))
        self.label_22.setText(_translate("Dialog", "OSF2 Min. Wavelength"))
        self.checkBox_12.setText(_translate("Dialog", "Use OSF1"))
        self.label_23.setText(_translate("Dialog", "OSF4 Max Wavelength:"))
        self.label_24.setText(_translate("Dialog", "OSF1 Min. Wavelength"))
        self.checkBox_13.setText(_translate("Dialog", "Use OSF2"))
        self.label_25.setText(_translate("Dialog", "OSF3 Min. Wavelength"))
        self.label_26.setText(_translate("Dialog", "OSF1 Max Wavelength:"))
        self.label_27.setText(_translate("Dialog", "OSF2 Max Wavelength:"))
        self.checkBox_14.setText(_translate("Dialog", "Use OSF4"))
        self.label_28.setText(_translate("Dialog", "OSF3 Max Wavelength:"))
        self.label_29.setText(_translate("Dialog", "OSF4 Min. Wavelength"))
        self.label_5.setText(_translate("Dialog", "Scan Ending Microns:"))
        self.label_6.setText(_translate("Dialog", "Scan Step Microns:"))
        self.pushButton_3.setText(_translate("Dialog", "Start Scan"))
        self.label_7.setText(_translate("Dialog", "Measuring Interval (s):"))
        self.label_36.setText(_translate("Dialog", "Scan Starting Microns:"))
        self.pushButton_4.setText(_translate("Dialog", "Abort Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Scan"))
        self.label_38.setText(_translate("Dialog", "Wavelength:"))
        self.label_41.setText(_translate("Dialog", "Shutter:"))
        self.label_37.setText(_translate("Dialog", "Current Parameters:"))
        self.label_40.setText(_translate("Dialog", "Grating:"))
        self.label_39.setText(_translate("Dialog", "Filter:"))
        self.label_44.setText(_translate("Dialog", "Filter:"))
        self.label_42.setText(_translate("Dialog", "New Parameters:"))
        self.label_46.setText(_translate("Dialog", "Shutter:"))
        self.comboBox.setItemText(0, _translate("Dialog", "OSF1"))
        self.comboBox.setItemText(1, _translate("Dialog", "OSF2"))
        self.comboBox.setItemText(2, _translate("Dialog", "OSF3"))
        self.comboBox.setItemText(3, _translate("Dialog", "OSF4"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "G1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "G2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "G3"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Open"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Close"))
        self.label_43.setText(_translate("Dialog", "Wavelength:"))
        self.label_45.setText(_translate("Dialog", "Grating:"))
        self.label_47.setText(_translate("Dialog", "Units:"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "um."))
        self.comboBox_4.setItemText(1, _translate("Dialog", "nm."))
        self.comboBox_4.setItemText(2, _translate("Dialog", "wn (cm^-1)"))
        self.pushButton_5.setText(_translate("Dialog", "Set Parameters"))
        self.pushButton_6.setText(_translate("Dialog", "Abort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
