# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonochromatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(641, 484)
        self.gridLayout_12 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.start_scan_series_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_scan_series_button.sizePolicy().hasHeightForWidth())
        self.start_scan_series_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_scan_series_button.setFont(font)
        self.start_scan_series_button.setObjectName("start_scan_series_button")
        self.gridLayout_5.addWidget(self.start_scan_series_button, 0, 0, 1, 1)
        self.abort_scan_series_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort_scan_series_button.sizePolicy().hasHeightForWidth())
        self.abort_scan_series_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.abort_scan_series_button.setFont(font)
        self.abort_scan_series_button.setObjectName("abort_scan_series_button")
        self.gridLayout_5.addWidget(self.abort_scan_series_button, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.grating_select_cbox = QtWidgets.QComboBox(self.tab)
        self.grating_select_cbox.setObjectName("grating_select_cbox")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.gridLayout.addWidget(self.grating_select_cbox, 3, 0, 1, 1)
        self.grating_select_label = QtWidgets.QLabel(self.tab)
        self.grating_select_label.setObjectName("grating_select_label")
        self.gridLayout.addWidget(self.grating_select_label, 2, 0, 1, 1)
        self.osf_select_label = QtWidgets.QLabel(self.tab)
        self.osf_select_label.setObjectName("osf_select_label")
        self.gridLayout.addWidget(self.osf_select_label, 2, 1, 1, 1)
        self.osf_select_cbox = QtWidgets.QComboBox(self.tab)
        self.osf_select_cbox.setObjectName("osf_select_cbox")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.gridLayout.addWidget(self.osf_select_cbox, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequence_wave_end_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_end_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_end_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_end_ledit.setObjectName("sequence_wave_end_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_end_ledit, 1, 1, 1, 1)
        self.sequence_end_wave_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_end_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_end_wave_label.setSizePolicy(sizePolicy)
        self.sequence_end_wave_label.setObjectName("sequence_end_wave_label")
        self.gridLayout_2.addWidget(self.sequence_end_wave_label, 0, 1, 1, 1)
        self.sequence_wave_step_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_step_ledit.setObjectName("sequence_wave_step_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_step_ledit, 1, 2, 1, 1)
        self.sequence_wave_step_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_label.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_label.setSizePolicy(sizePolicy)
        self.sequence_wave_step_label.setObjectName("sequence_wave_step_label")
        self.gridLayout_2.addWidget(self.sequence_wave_step_label, 0, 2, 1, 1)
        self.sequence_wave_start_ledit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_start_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_start_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_start_ledit.setObjectName("sequence_wave_start_ledit")
        self.gridLayout_2.addWidget(self.sequence_wave_start_ledit, 1, 0, 1, 1)
        self.sequence_start_wave_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_start_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_start_wave_label.setSizePolicy(sizePolicy)
        self.sequence_start_wave_label.setObjectName("sequence_start_wave_label")
        self.gridLayout_2.addWidget(self.sequence_start_wave_label, 0, 0, 1, 1)
        self.sequence_measure_int_ledit = QtWidgets.QLineEdit(self.tab)
        self.sequence_measure_int_ledit.setObjectName("sequence_measure_int_ledit")
        self.gridLayout_2.addWidget(self.sequence_measure_int_ledit, 1, 3, 1, 1)
        self.sequence_measure_int_label = QtWidgets.QLabel(self.tab)
        self.sequence_measure_int_label.setObjectName("sequence_measure_int_label")
        self.gridLayout_2.addWidget(self.sequence_measure_int_label, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sequence_name_ledit = QtWidgets.QLineEdit(self.tab)
        self.sequence_name_ledit.setObjectName("sequence_name_ledit")
        self.gridLayout_4.addWidget(self.sequence_name_ledit, 1, 0, 1, 1)
        self.add_new_sequence_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_new_sequence_button.sizePolicy().hasHeightForWidth())
        self.add_new_sequence_button.setSizePolicy(sizePolicy)
        self.add_new_sequence_button.setObjectName("add_new_sequence_button")
        self.gridLayout_4.addWidget(self.add_new_sequence_button, 2, 0, 1, 1)
        self.sequence_name_label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_label.sizePolicy().hasHeightForWidth())
        self.sequence_name_label.setSizePolicy(sizePolicy)
        self.sequence_name_label.setObjectName("sequence_name_label")
        self.gridLayout_4.addWidget(self.sequence_name_label, 0, 0, 1, 1)
        self.remove_sequence_button = QtWidgets.QPushButton(self.tab)
        self.remove_sequence_button.setObjectName("remove_sequence_button")
        self.gridLayout_4.addWidget(self.remove_sequence_button, 4, 0, 1, 1)
        self.edit_sequence_button = QtWidgets.QPushButton(self.tab)
        self.edit_sequence_button.setObjectName("edit_sequence_button")
        self.gridLayout_4.addWidget(self.edit_sequence_button, 3, 0, 1, 1)
        self.series_list = QtWidgets.QListWidget(self.tab)
        self.series_list.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.series_list.setObjectName("series_list")
        self.gridLayout_4.addWidget(self.series_list, 0, 1, 5, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_37.setEnabled(False)
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_7.addWidget(self.lineEdit_37, 2, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_38.setEnabled(False)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_7.addWidget(self.lineEdit_38, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 7, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_39.setEnabled(False)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_7.addWidget(self.lineEdit_39, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 5, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_40.setEnabled(False)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_7.addWidget(self.lineEdit_40, 8, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 7, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_8.addWidget(self.lineEdit_41, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 6, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_3, 8, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 5, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.gridLayout_13.addWidget(self.label_47, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_4, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_13, 1, 0, 1, 2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_14.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_14.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_scan_series_button.setText(_translate("Dialog", "Start Scan Series"))
        self.abort_scan_series_button.setText(_translate("Dialog", "Abort Scan Series"))
        self.grating_select_cbox.setItemText(0, _translate("Dialog", "Grating 1 (G1)"))
        self.grating_select_cbox.setItemText(1, _translate("Dialog", "Grating 2 (G2)"))
        self.grating_select_cbox.setItemText(2, _translate("Dialog", "Grating 3 (G3)"))
        self.grating_select_label.setText(_translate("Dialog", "Seqeuence Grating Selection:"))
        self.osf_select_label.setText(_translate("Dialog", "Sequence Order Sort Filter Selection:"))
        self.osf_select_cbox.setItemText(0, _translate("Dialog", "OSF1"))
        self.osf_select_cbox.setItemText(1, _translate("Dialog", "OSF2"))
        self.osf_select_cbox.setItemText(2, _translate("Dialog", "OSF3"))
        self.osf_select_cbox.setItemText(3, _translate("Dialog", "OSF4"))
        self.sequence_end_wave_label.setText(_translate("Dialog", "Sequence End Wavelength (um.):"))
        self.sequence_wave_step_label.setText(_translate("Dialog", "Sequence Wavelength Step (nm.):"))
        self.sequence_start_wave_label.setText(_translate("Dialog", "Sequence Start Wavelength (um.):"))
        self.sequence_measure_int_label.setText(_translate("Dialog", "Sequence Measure Interval:"))
        self.add_new_sequence_button.setText(_translate("Dialog", "Add New Sequence To Scan Series"))
        self.sequence_name_label.setText(_translate("Dialog", "Sequence Name:"))
        self.remove_sequence_button.setText(_translate("Dialog", "Remove Sequence from Scan Series"))
        self.edit_sequence_button.setText(_translate("Dialog", "Edit Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Scan"))
        self.label_38.setText(_translate("Dialog", "Wavelength:"))
        self.label_41.setText(_translate("Dialog", "Shutter:"))
        self.label_37.setText(_translate("Dialog", "Current Parameters:"))
        self.label_40.setText(_translate("Dialog", "Grating:"))
        self.label_39.setText(_translate("Dialog", "Filter:"))
        self.label_44.setText(_translate("Dialog", "Filter:"))
        self.label_42.setText(_translate("Dialog", "New Parameters:"))
        self.label_46.setText(_translate("Dialog", "Shutter:"))
        self.comboBox.setItemText(0, _translate("Dialog", "OSF1"))
        self.comboBox.setItemText(1, _translate("Dialog", "OSF2"))
        self.comboBox.setItemText(2, _translate("Dialog", "OSF3"))
        self.comboBox.setItemText(3, _translate("Dialog", "OSF4"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "G1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "G2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "G3"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Open"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Close"))
        self.label_43.setText(_translate("Dialog", "Wavelength:"))
        self.label_45.setText(_translate("Dialog", "Grating:"))
        self.label_47.setText(_translate("Dialog", "Units:"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "um."))
        self.comboBox_4.setItemText(1, _translate("Dialog", "nm."))
        self.comboBox_4.setItemText(2, _translate("Dialog", "wn (cm^-1)"))
        self.pushButton_5.setText(_translate("Dialog", "Set Parameters"))
        self.pushButton_6.setText(_translate("Dialog", "Abort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
