# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sr510AutoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sr510(object):
    def setupUi(self, Sr510):
        Sr510.setObjectName("Sr510")
        Sr510.resize(593, 605)
        self.gridLayout = QtWidgets.QGridLayout(Sr510)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(Sr510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Sr510)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr510SampleRate = QtWidgets.QComboBox(Sr510)
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setObjectName("combobox_list_SavedSequences_passive_Sr510SampleRate")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr510SampleRate, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(Sr510)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue = QtWidgets.QComboBox(Sr510)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue.setObjectName("combobox_list_SavedSequences_passive_Sr510TimeConstantValue")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Sr510)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier = QtWidgets.QComboBox(Sr510)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.setObjectName("combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Sr510)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits = QtWidgets.QComboBox(Sr510)
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.setObjectName("combobox_list_SavedSequences_passive_Sr510TimeConstantUnits")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.addItem("")
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(Sr510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions = QtWidgets.QListWidget(Sr510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions.sizePolicy().hasHeightForWidth())
        self.list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions.setSizePolicy(sizePolicy)
        self.list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions.setObjectName("list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions")
        self.gridLayout.addWidget(self.list_listXlist_Sr510SensTransitionsXSavedSequences_listXPassiveListAll_Sr510SensitivityTransitions, 6, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(Sr510)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.lineedit_list_Sr510SensTransitions_ItemDisplay_wavelength = QtWidgets.QLineEdit(Sr510)
        self.lineedit_list_Sr510SensTransitions_ItemDisplay_wavelength.setObjectName("lineedit_list_Sr510SensTransitions_ItemDisplay_wavelength")
        self.gridLayout.addWidget(self.lineedit_list_Sr510SensTransitions_ItemDisplay_wavelength, 7, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Sr510)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue = QtWidgets.QComboBox(Sr510)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.setObjectName("lineedit_list_Sr510SensTransitions_passive_SensitivityValue")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Sr510)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier = QtWidgets.QComboBox(Sr510)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.setObjectName("lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(Sr510)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits = QtWidgets.QComboBox(Sr510)
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.setObjectName("lineedit_list_Sr510SensTransitions_passive_SensitivityUnits")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.addItem("")
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits, 10, 1, 1, 1)
        self.button_list_Sr510SensTransitions_setter_AddSr510SensTransition = QtWidgets.QPushButton(Sr510)
        self.button_list_Sr510SensTransitions_setter_AddSr510SensTransition.setObjectName("button_list_Sr510SensTransitions_setter_AddSr510SensTransition")
        self.gridLayout.addWidget(self.button_list_Sr510SensTransitions_setter_AddSr510SensTransition, 11, 0, 1, 2)
        self.button_list_Sr510SensTransitions_remover_RemoveSr510SensTransition = QtWidgets.QPushButton(Sr510)
        self.button_list_Sr510SensTransitions_remover_RemoveSr510SensTransition.setObjectName("button_list_Sr510SensTransitions_remover_RemoveSr510SensTransition")
        self.gridLayout.addWidget(self.button_list_Sr510SensTransitions_remover_RemoveSr510SensTransition, 12, 0, 1, 2)
        self.button_list_Sr510SensTransitions_RemoverOfAll_RemoveAllSr510SensTransitions = QtWidgets.QPushButton(Sr510)
        self.button_list_Sr510SensTransitions_RemoverOfAll_RemoveAllSr510SensTransitions.setObjectName("button_list_Sr510SensTransitions_RemoverOfAll_RemoveAllSr510SensTransitions")
        self.gridLayout.addWidget(self.button_list_Sr510SensTransitions_RemoverOfAll_RemoveAllSr510SensTransitions, 13, 0, 1, 2)

        self.retranslateUi(Sr510)
        QtCore.QMetaObject.connectSlotsByName(Sr510)

    def retranslateUi(self, Sr510):
        _translate = QtCore.QCoreApplication.translate
        Sr510.setWindowTitle(_translate("Sr510", "Sr510"))
        self.label_11.setText(_translate("Sr510", "SR510 Lock-In Sequence Control:"))
        self.label_12.setText(_translate("Sr510", "Sample Rate (Hz.):"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setCurrentText(_translate("Sr510", "0.0625"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(0, _translate("Sr510", "0.0625"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(1, _translate("Sr510", "0.125"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(2, _translate("Sr510", "0.250"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(3, _translate("Sr510", "0.5"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(4, _translate("Sr510", "1"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(5, _translate("Sr510", "2"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(6, _translate("Sr510", "4"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(7, _translate("Sr510", "8"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(8, _translate("Sr510", "16"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(9, _translate("Sr510", "32"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(10, _translate("Sr510", "64"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(11, _translate("Sr510", "128"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(12, _translate("Sr510", "256"))
        self.combobox_list_SavedSequences_passive_Sr510SampleRate.setItemText(13, _translate("Sr510", "512"))
        self.label_19.setText(_translate("Sr510", "Time Constant Value:"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue.setItemText(0, _translate("Sr510", "1"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantValue.setItemText(1, _translate("Sr510", "3"))
        self.label_17.setText(_translate("Sr510", "Time Constant Multiplier:"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.setItemText(0, _translate("Sr510", "x1"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.setItemText(1, _translate("Sr510", "x10"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantMultiplier.setItemText(2, _translate("Sr510", "x100"))
        self.label_18.setText(_translate("Sr510", "Time Constant Units:"))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.setCurrentText(_translate("Sr510", "s."))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.setItemText(0, _translate("Sr510", "s."))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.setItemText(1, _translate("Sr510", "ms."))
        self.combobox_list_SavedSequences_passive_Sr510TimeConstantUnits.setItemText(2, _translate("Sr510", "us."))
        self.label_16.setText(_translate("Sr510", "SR510 Sensitivity Transitions in Sequence:"))
        self.label_20.setText(_translate("Sr510", "Wavelength:"))
        self.label_15.setText(_translate("Sr510", "Sensitivity Value:"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.setItemText(0, _translate("Sr510", "1"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.setItemText(1, _translate("Sr510", "2"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityValue.setItemText(2, _translate("Sr510", "5"))
        self.label_13.setText(_translate("Sr510", "Sensitivity Multiplier:"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.setItemText(0, _translate("Sr510", "x1"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.setItemText(1, _translate("Sr510", "x10"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityMultiplier.setItemText(2, _translate("Sr510", "x100"))
        self.label_14.setText(_translate("Sr510", "Sensitivity Units:"))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.setItemText(0, _translate("Sr510", "mV."))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.setItemText(1, _translate("Sr510", "uV."))
        self.lineedit_list_Sr510SensTransitions_passive_SensitivityUnits.setItemText(2, _translate("Sr510", "nV."))
        self.button_list_Sr510SensTransitions_setter_AddSr510SensTransition.setText(_translate("Sr510", "Add SR510 Sensitivity Transition to Sequence"))
        self.button_list_Sr510SensTransitions_remover_RemoveSr510SensTransition.setText(_translate("Sr510", "Remove SR510 Sensitivity Transitions from Sequence"))
        self.button_list_Sr510SensTransitions_RemoverOfAll_RemoveAllSr510SensTransitions.setText(_translate("Sr510", "Remove All SR510 Transitions from Sequence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sr510 = QtWidgets.QWidget()
    ui = Ui_Sr510()
    ui.setupUi(Sr510)
    Sr510.show()
    sys.exit(app.exec_())

