# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sr830Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sr830Dialog(object):
    def setupUi(self, Sr830Dialog):
        Sr830Dialog.setObjectName("Sr830Dialog")
        Sr830Dialog.resize(677, 639)
        self.gridLayout = QtWidgets.QGridLayout(Sr830Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_29 = QtWidgets.QLabel(Sr830Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 1, 1, 1)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity = QtWidgets.QLineEdit(Sr830Dialog)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity.setFont(font)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity.setReadOnly(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity.setClearButtonEnabled(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity.setObjectName("lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity")
        self.gridLayout.addWidget(self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentSensitivity, 3, 0, 1, 1)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant = QtWidgets.QLineEdit(Sr830Dialog)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant.setEnabled(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant.setReadOnly(False)
        self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant.setObjectName("lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant")
        self.gridLayout.addWidget(self.lineedit_base_Sr830CurrentConfigParameters_passive_CurrentTimeConstant, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(Sr830Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 0, 1, 2)
        self.label_30 = QtWidgets.QLabel(Sr830Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 6, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(Sr830Dialog)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(Sr830Dialog)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 7, 1, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue = QtWidgets.QComboBox(Sr830Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.sizePolicy().hasHeightForWidth())
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.setSizePolicy(sizePolicy)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue, 8, 0, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue = QtWidgets.QComboBox(Sr830Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.sizePolicy().hasHeightForWidth())
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.setSizePolicy(sizePolicy)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Sr830Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(Sr830Dialog)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 1, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier = QtWidgets.QComboBox(Sr830Dialog)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier, 10, 0, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier = QtWidgets.QComboBox(Sr830Dialog)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier, 10, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(Sr830Dialog)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Sr830Dialog)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 11, 1, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits = QtWidgets.QComboBox(Sr830Dialog)
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits, 12, 0, 1, 1)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits = QtWidgets.QComboBox(Sr830Dialog)
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.setObjectName("lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.addItem("")
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.addItem("")
        self.gridLayout.addWidget(self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits, 12, 1, 1, 1)
        self.button_base_NewSr830State_getter_Sr830SetNewParametersButton = QtWidgets.QPushButton(Sr830Dialog)
        self.button_base_NewSr830State_getter_Sr830SetNewParametersButton.setObjectName("button_base_NewSr830State_getter_Sr830SetNewParametersButton")
        self.gridLayout.addWidget(self.button_base_NewSr830State_getter_Sr830SetNewParametersButton, 13, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(Sr830Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 14, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(Sr830Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 15, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(Sr830Dialog)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 16, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(Sr830Dialog)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 16, 1, 1, 1)
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate = QtWidgets.QComboBox(Sr830Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setSizePolicy(sizePolicy)
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setObjectName("combobox_base_NewSr830Measurement_passive_Sr830SampleRate")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate, 17, 0, 1, 1)
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleTime = QtWidgets.QLineEdit(Sr830Dialog)
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleTime.setObjectName("combobox_base_NewSr830Measurement_passive_Sr830SampleTime")
        self.gridLayout.addWidget(self.combobox_base_NewSr830Measurement_passive_Sr830SampleTime, 17, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(Sr830Dialog)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 18, 0, 1, 1)
        self.combobox_base_NewSr830Measurement_passive_Sr830MeasurementStoragePath = QtWidgets.QLineEdit(Sr830Dialog)
        self.combobox_base_NewSr830Measurement_passive_Sr830MeasurementStoragePath.setObjectName("combobox_base_NewSr830Measurement_passive_Sr830MeasurementStoragePath")
        self.gridLayout.addWidget(self.combobox_base_NewSr830Measurement_passive_Sr830MeasurementStoragePath, 19, 0, 1, 2)
        self.button_base_NewSr830Measurement_getter_Sr830StartMeasurement = QtWidgets.QPushButton(Sr830Dialog)
        self.button_base_NewSr830Measurement_getter_Sr830StartMeasurement.setObjectName("button_base_NewSr830Measurement_getter_Sr830StartMeasurement")
        self.gridLayout.addWidget(self.button_base_NewSr830Measurement_getter_Sr830StartMeasurement, 20, 0, 1, 2)

        self.retranslateUi(Sr830Dialog)
        QtCore.QMetaObject.connectSlotsByName(Sr830Dialog)

    def retranslateUi(self, Sr830Dialog):
        _translate = QtCore.QCoreApplication.translate
        Sr830Dialog.setWindowTitle(_translate("Sr830Dialog", "Sr830"))
        self.label_29.setText(_translate("Sr830Dialog", "SR830 Lock-In:"))
        self.label_17.setText(_translate("Sr830Dialog", "Current Parameters:"))
        self.label_14.setText(_translate("Sr830Dialog", "Sensitivity:"))
        self.label_18.setText(_translate("Sr830Dialog", "Time-Constant:"))
        self.label_24.setText(_translate("Sr830Dialog", "New Parameters:"))
        self.label_30.setText(_translate("Sr830Dialog", "Sensitivity:"))
        self.label_31.setText(_translate("Sr830Dialog", "Time-Constant:"))
        self.label_23.setText(_translate("Sr830Dialog", "Value:"))
        self.label_21.setText(_translate("Sr830Dialog", "Value:"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.setItemText(0, _translate("Sr830Dialog", "1"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.setItemText(1, _translate("Sr830Dialog", "2"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityValue.setItemText(2, _translate("Sr830Dialog", "5"))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.setItemText(0, _translate("Sr830Dialog", "1"))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantValue.setItemText(1, _translate("Sr830Dialog", "3"))
        self.label_15.setText(_translate("Sr830Dialog", "Multiplier:"))
        self.label_22.setText(_translate("Sr830Dialog", "Multiplier:"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.setItemText(0, _translate("Sr830Dialog", "x1"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.setItemText(1, _translate("Sr830Dialog", "x10"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityMultiplier.setItemText(2, _translate("Sr830Dialog", "x100"))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.setItemText(0, _translate("Sr830Dialog", "x1"))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.setItemText(1, _translate("Sr830Dialog", "x10"))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantMultiplier.setItemText(2, _translate("Sr830Dialog", "x100"))
        self.label_16.setText(_translate("Sr830Dialog", "Units:"))
        self.label_20.setText(_translate("Sr830Dialog", "Units:"))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.setItemText(0, _translate("Sr830Dialog", "V."))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.setItemText(1, _translate("Sr830Dialog", "mV."))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.setItemText(2, _translate("Sr830Dialog", "uV."))
        self.lineedit_base_NewSr830State_passive_Sr830NewSensitivityUnits.setItemText(3, _translate("Sr830Dialog", "nV."))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.setItemText(0, _translate("Sr830Dialog", "ks."))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.setItemText(1, _translate("Sr830Dialog", "s."))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.setItemText(2, _translate("Sr830Dialog", "ms."))
        self.lineedit_base_NewSr830State_passive_Sr830NewTimeConstantUnits.setItemText(3, _translate("Sr830Dialog", "us."))
        self.button_base_NewSr830State_getter_Sr830SetNewParametersButton.setText(_translate("Sr830Dialog", "Set New Parameters"))
        self.label_19.setText(_translate("Sr830Dialog", "Measurement:"))
        self.label_32.setText(_translate("Sr830Dialog", "Sample Rate (Hz.):"))
        self.label_33.setText(_translate("Sr830Dialog", "Sample Time (s.):"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setCurrentText(_translate("Sr830Dialog", "0.0625"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(0, _translate("Sr830Dialog", "0.0625"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(1, _translate("Sr830Dialog", "0.125"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(2, _translate("Sr830Dialog", "0.250"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(3, _translate("Sr830Dialog", "0.5"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(4, _translate("Sr830Dialog", "1"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(5, _translate("Sr830Dialog", "2"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(6, _translate("Sr830Dialog", "4"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(7, _translate("Sr830Dialog", "8"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(8, _translate("Sr830Dialog", "16"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(9, _translate("Sr830Dialog", "32"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(10, _translate("Sr830Dialog", "64"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(11, _translate("Sr830Dialog", "128"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(12, _translate("Sr830Dialog", "256"))
        self.combobox_base_NewSr830Measurement_passive_Sr830SampleRate.setItemText(13, _translate("Sr830Dialog", "512"))
        self.label_34.setText(_translate("Sr830Dialog", "Measurement Storage Path:"))
        self.button_base_NewSr830Measurement_getter_Sr830StartMeasurement.setText(_translate("Sr830Dialog", "Start Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sr830Dialog = QtWidgets.QWidget()
    ui = Ui_Sr830Dialog()
    ui.setupUi(Sr830Dialog)
    Sr830Dialog.show()
    sys.exit(app.exec_())

