# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sr830AutoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1628, 1569)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setObjectName("combobox_list_SavedSequences_passive_Sr830SampleFrequency")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr830SampleFrequency, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue.setObjectName("combobox_list_SavedSequences_passive_Sr830TimeConstantValue")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.setObjectName("combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setObjectName("combobox_list_SavedSequences_passive_Sr830TimeConstantUnits")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.addItem("")
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.addItem("")
        self.gridLayout.addWidget(self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions.sizePolicy().hasHeightForWidth())
        self.list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions.setSizePolicy(sizePolicy)
        self.list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions.setObjectName("list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions")
        self.gridLayout.addWidget(self.list_listXlist_Sr830SensTransitionsXSavedSequences_listXPassiveListAll_Sr830SensitivityTransitions, 6, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.lineedit_list_Sr830SensTransitions_ItemDisplay_wavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_Sr830SensTransitions_ItemDisplay_wavelength.setObjectName("lineedit_list_Sr830SensTransitions_ItemDisplay_wavelength")
        self.gridLayout.addWidget(self.lineedit_list_Sr830SensTransitions_ItemDisplay_wavelength, 7, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue = QtWidgets.QComboBox(Form)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.setObjectName("lineedit_list_Sr830SensTransitions_passive_SensitivityValue")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier = QtWidgets.QComboBox(Form)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.setObjectName("lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits = QtWidgets.QComboBox(Form)
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.setObjectName("lineedit_list_Sr830SensTransitions_passive_SensitivityUnits")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.addItem("")
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.addItem("")
        self.gridLayout.addWidget(self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits, 10, 1, 1, 1)
        self.button_list_Sr830SensTransitions_setter_AddSr830SensTransition = QtWidgets.QPushButton(Form)
        self.button_list_Sr830SensTransitions_setter_AddSr830SensTransition.setObjectName("button_list_Sr830SensTransitions_setter_AddSr830SensTransition")
        self.gridLayout.addWidget(self.button_list_Sr830SensTransitions_setter_AddSr830SensTransition, 11, 0, 1, 2)
        self.button_list_Sr830SensTransitions_remover_RemoveSr830SensTransition = QtWidgets.QPushButton(Form)
        self.button_list_Sr830SensTransitions_remover_RemoveSr830SensTransition.setObjectName("button_list_Sr830SensTransitions_remover_RemoveSr830SensTransition")
        self.gridLayout.addWidget(self.button_list_Sr830SensTransitions_remover_RemoveSr830SensTransition, 12, 0, 1, 2)
        self.button_list_Sr830SensTransitions_RemoverOfAll_RemoveAllSr830SensTransitions = QtWidgets.QPushButton(Form)
        self.button_list_Sr830SensTransitions_RemoverOfAll_RemoveAllSr830SensTransitions.setObjectName("button_list_Sr830SensTransitions_RemoverOfAll_RemoveAllSr830SensTransitions")
        self.gridLayout.addWidget(self.button_list_Sr830SensTransitions_RemoverOfAll_RemoveAllSr830SensTransitions, 13, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sr830"))
        self.label_11.setText(_translate("Form", "SR830 Lock-In Sequence Control:"))
        self.label_12.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setCurrentText(_translate("Form", "0.0625"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(0, _translate("Form", "0.0625"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(1, _translate("Form", "0.125"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(2, _translate("Form", "0.250"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(3, _translate("Form", "0.5"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(4, _translate("Form", "1"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(5, _translate("Form", "2"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(6, _translate("Form", "4"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(7, _translate("Form", "8"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(8, _translate("Form", "16"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(9, _translate("Form", "32"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(10, _translate("Form", "64"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(11, _translate("Form", "128"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(12, _translate("Form", "256"))
        self.combobox_list_SavedSequences_passive_Sr830SampleFrequency.setItemText(13, _translate("Form", "512"))
        self.label_19.setText(_translate("Form", "Time Constant Value:"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue.setItemText(0, _translate("Form", "1"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantValue.setItemText(1, _translate("Form", "3"))
        self.label_17.setText(_translate("Form", "Time Constant Multiplier:"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.setItemText(0, _translate("Form", "x1"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.setItemText(1, _translate("Form", "x10"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantMultiplier.setItemText(2, _translate("Form", "x100"))
        self.label_18.setText(_translate("Form", "Time Constant Units:"))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setCurrentText(_translate("Form", "ks."))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setItemText(0, _translate("Form", "ks."))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setItemText(1, _translate("Form", "s."))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setItemText(2, _translate("Form", "ms."))
        self.combobox_list_SavedSequences_passive_Sr830TimeConstantUnits.setItemText(3, _translate("Form", "us."))
        self.label_16.setText(_translate("Form", "SR830 Sensitivity Transitions in Sequence:"))
        self.label_20.setText(_translate("Form", "Wavelength:"))
        self.label_15.setText(_translate("Form", "Sensitivity Value:"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.setItemText(0, _translate("Form", "1"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.setItemText(1, _translate("Form", "2"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityValue.setItemText(2, _translate("Form", "5"))
        self.label_13.setText(_translate("Form", "Sensitivity Multiplier:"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.setItemText(0, _translate("Form", "x1"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.setItemText(1, _translate("Form", "x10"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityMultiplier.setItemText(2, _translate("Form", "x100"))
        self.label_14.setText(_translate("Form", "Sensitivity Units:"))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.setItemText(0, _translate("Form", "V."))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.setItemText(1, _translate("Form", "mV."))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.setItemText(2, _translate("Form", "uV."))
        self.lineedit_list_Sr830SensTransitions_passive_SensitivityUnits.setItemText(3, _translate("Form", "nV."))
        self.button_list_Sr830SensTransitions_setter_AddSr830SensTransition.setText(_translate("Form", "Add SR830 Sensitivity Transition to Sequence"))
        self.button_list_Sr830SensTransitions_remover_RemoveSr830SensTransition.setText(_translate("Form", "Remove SR830 Sensitivity Transitions from Sequence"))
        self.button_list_Sr830SensTransitions_RemoverOfAll_RemoveAllSr830SensTransitions.setText(_translate("Form", "Remove All SR830 Transitions from Sequence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

