# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seriesconstructionWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1967, 1605)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 0, 1, 1)
        self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence = QtWidgets.QListWidget(Form)
        self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence.setObjectName("list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence")
        self.gridLayout_13.addWidget(self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence, 4, 0, 1, 1)
        self.button_list_SavedSequences_setter_SaveNewSequenceButton = QtWidgets.QPushButton(Form)
        self.button_list_SavedSequences_setter_SaveNewSequenceButton.setObjectName("button_list_SavedSequences_setter_SaveNewSequenceButton")
        self.gridLayout_13.addWidget(self.button_list_SavedSequences_setter_SaveNewSequenceButton, 2, 0, 1, 1)
        self.lineedit_list_SavedSequences_ItemDisplay_SequenceName = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_ItemDisplay_SequenceName.setObjectName("lineedit_list_SavedSequences_ItemDisplay_SequenceName")
        self.gridLayout_13.addWidget(self.lineedit_list_SavedSequences_ItemDisplay_SequenceName, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 3, 0, 1, 1)
        self.button_list_Series_setter_AddSequenceToSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_setter_AddSequenceToSeriesButton.setObjectName("button_list_Series_setter_AddSequenceToSeriesButton")
        self.gridLayout_13.addWidget(self.button_list_Series_setter_AddSequenceToSeriesButton, 5, 0, 1, 1)
        self.main_layout.addLayout(self.gridLayout_13, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.main_layout.addWidget(self.label_5, 3, 0, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton.setObjectName("button_list_Series_remover_RemoveSequenceFromSeriesButton")
        self.gridLayout_15.addWidget(self.button_list_Series_remover_RemoveSequenceFromSeriesButton, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.list_list_Series_ItemSelectorList_SeriesList = QtWidgets.QListWidget(Form)
        self.list_list_Series_ItemSelectorList_SeriesList.setObjectName("list_list_Series_ItemSelectorList_SeriesList")
        self.gridLayout_15.addWidget(self.list_list_Series_ItemSelectorList_SeriesList, 1, 0, 1, 1)
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton.setObjectName("button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton")
        self.gridLayout_15.addWidget(self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton, 3, 0, 1, 1)
        self.main_layout.addLayout(self.gridLayout_15, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.main_layout.addWidget(self.line_2, 4, 0, 1, 2)
        self.button_3 = QtWidgets.QPushButton(Form)
        self.button_3.setObjectName("button_3")
        self.main_layout.addWidget(self.button_3, 10, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.main_layout.addWidget(self.line_3, 7, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.main_layout.addWidget(self.label_9, 6, 0, 1, 2)
        self.button_2 = QtWidgets.QPushButton(Form)
        self.button_2.setObjectName("button_2")
        self.main_layout.addWidget(self.button_2, 9, 0, 1, 2)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 0, 1, 1, 2)
        self.checkbox_list_SavedSequences_passive_MetadataNdfPosition = QtWidgets.QCheckBox(Form)
        self.checkbox_list_SavedSequences_passive_MetadataNdfPosition.setObjectName("checkbox_list_SavedSequences_passive_MetadataNdfPosition")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataNdfPosition, 6, 2, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataLabjackDioState = QtWidgets.QCheckBox(Form)
        self.checkbox_list_SavedSequences_passive_MetadataLabjackDioState.setObjectName("checkbox_list_SavedSequences_passive_MetadataLabjackDioState")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataLabjackDioState, 6, 1, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating.setObjectName("checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating, 1, 2, 2, 1)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime.setObjectName("checkbox_list_SavedSequences_passive_MetadataLockinSampleTime")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime, 4, 2, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity.setObjectName("checkbox_list_SavedSequences_passive_MetadataLockinSensitivity")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity, 5, 2, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter.setObjectName("checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter, 3, 2, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate.setObjectName("checkbox_list_SavedSequences_passive_MetadataLockinSampleRate")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate, 4, 1, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength.setObjectName("checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength, 1, 1, 2, 1)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf.setObjectName("checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf, 3, 1, 1, 1)
        self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant.setObjectName("checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant, 5, 1, 1, 1)
        self.ledit_list_SavedSequences_passive_DataExposureDuration = QtWidgets.QLineEdit(Form)
        self.ledit_list_SavedSequences_passive_DataExposureDuration.setObjectName("ledit_list_SavedSequences_passive_DataExposureDuration")
        self.gridLayout_16.addWidget(self.ledit_list_SavedSequences_passive_DataExposureDuration, 10, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 10, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 7, 1, 1, 1)
        self.ledit_list_SavedSequences_passive_DataStoragePath = QtWidgets.QLineEdit(Form)
        self.ledit_list_SavedSequences_passive_DataStoragePath.setObjectName("ledit_list_SavedSequences_passive_DataStoragePath")
        self.gridLayout_16.addWidget(self.ledit_list_SavedSequences_passive_DataStoragePath, 7, 2, 1, 1)
        self.main_layout.addLayout(self.gridLayout_16, 5, 0, 1, 2)
        self.button_list_Series_getter_RunSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_getter_RunSeriesButton.setObjectName("button_list_Series_getter_RunSeriesButton")
        self.main_layout.addWidget(self.button_list_Series_getter_RunSeriesButton, 8, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Series Construction"))
        self.label.setText(_translate("Form", "Series Construction:"))
        self.label_2.setText(_translate("Form", "Sequence Name:"))
        self.button_list_SavedSequences_setter_SaveNewSequenceButton.setText(_translate("Form", "Save New Sequence"))
        self.label_4.setText(_translate("Form", "Saved Sequences:"))
        self.button_list_Series_setter_AddSequenceToSeriesButton.setText(_translate("Form", "Add Sequence To Series"))
        self.label_5.setText(_translate("Form", "Data Configuration:"))
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton.setText(_translate("Form", "Remove Sequence From Series"))
        self.label_3.setText(_translate("Form", "Series:"))
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton.setText(_translate("Form", "Remove All Sequences From Series"))
        self.button_3.setText(_translate("Form", "Abort Series"))
        self.label_9.setText(_translate("Form", "Control:"))
        self.button_2.setText(_translate("Form", "Pause Series"))
        self.label_6.setText(_translate("Form", "Metadata to Include:"))
        self.checkbox_list_SavedSequences_passive_MetadataNdfPosition.setText(_translate("Form", "NDF Wheel Position"))
        self.checkbox_list_SavedSequences_passive_MetadataLabjackDioState.setText(_translate("Form", "LabJack DIO State"))
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorGrating.setText(_translate("Form", "Monochromator Grating"))
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleTime.setText(_translate("Form", "Lock-in Sample Time"))
        self.checkbox_list_SavedSequences_passive_MetadataLockinSensitivity.setText(_translate("Form", "Lock-in Sensitivity"))
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorShutter.setText(_translate("Form", "Monochromator Shutter"))
        self.checkbox_list_SavedSequences_passive_MetadataLockinSampleRate.setText(_translate("Form", "Lock-in Sample Rate"))
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorWavelength.setText(_translate("Form", "Monochromator Wavelength"))
        self.checkbox_list_SavedSequences_passive_MetadataMonochromatorOsf.setText(_translate("Form", "Monochromator Order Sort Filter"))
        self.checkbox_list_SavedSequences_passive_MetadataLockinTimeConstant.setText(_translate("Form", "Lock-in Time Constant"))
        self.label_8.setText(_translate("Form", "Exposure Duration (s.):"))
        self.label_7.setText(_translate("Form", "Storage Path:"))
        self.button_list_Series_getter_RunSeriesButton.setText(_translate("Form", "Run Series"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

