# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS260Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1686, 1518)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.manual_monochromator_label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manual_monochromator_label_2.setFont(font)
        self.manual_monochromator_label_2.setObjectName("manual_monochromator_label_2")
        self.gridLayout.addWidget(self.manual_monochromator_label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.manual_monochromator_wavelength_label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_label_3.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_label_3.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_label_3.setObjectName("manual_monochromator_wavelength_label_3")
        self.gridLayout.addWidget(self.manual_monochromator_wavelength_label_3, 2, 0, 1, 1)
        self.manual_monochromator_wavelength_label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_wavelength_label_4.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_wavelength_label_4.setSizePolicy(sizePolicy)
        self.manual_monochromator_wavelength_label_4.setObjectName("manual_monochromator_wavelength_label_4")
        self.gridLayout.addWidget(self.manual_monochromator_wavelength_label_4, 2, 1, 1, 1)
        self.manual_monochromator_currentwavelength_ledit = QtWidgets.QLineEdit(Form)
        self.manual_monochromator_currentwavelength_ledit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentwavelength_ledit.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentwavelength_ledit.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentwavelength_ledit.setReadOnly(False)
        self.manual_monochromator_currentwavelength_ledit.setObjectName("manual_monochromator_currentwavelength_ledit")
        self.gridLayout.addWidget(self.manual_monochromator_currentwavelength_ledit, 3, 0, 1, 1)
        self.manual_monochromator_newwavelength_ledit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newwavelength_ledit.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newwavelength_ledit.setSizePolicy(sizePolicy)
        self.manual_monochromator_newwavelength_ledit.setObjectName("manual_monochromator_newwavelength_ledit")
        self.gridLayout.addWidget(self.manual_monochromator_newwavelength_ledit, 3, 1, 1, 1)
        self.manual_monochromator_curfilter_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_curfilter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_curfilter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_curfilter_label.setObjectName("manual_monochromator_curfilter_label")
        self.gridLayout.addWidget(self.manual_monochromator_curfilter_label, 4, 0, 1, 1)
        self.manual_monochromator_newfilter_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newfilter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newfilter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_newfilter_label.setObjectName("manual_monochromator_newfilter_label")
        self.gridLayout.addWidget(self.manual_monochromator_newfilter_label, 4, 1, 1, 1)
        self.manual_monochromator_currentfilter_combobox = QtWidgets.QComboBox(Form)
        self.manual_monochromator_currentfilter_combobox.setEnabled(False)
        self.manual_monochromator_currentfilter_combobox.setObjectName("manual_monochromator_currentfilter_combobox")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.manual_monochromator_currentfilter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_currentfilter_combobox, 5, 0, 1, 1)
        self.manual_monochromator_newfilter_combobox = QtWidgets.QComboBox(Form)
        self.manual_monochromator_newfilter_combobox.setObjectName("manual_monochromator_newfilter_combobox")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.manual_monochromator_newfilter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_newfilter_combobox, 5, 1, 1, 1)
        self.manual_monochromator_grating_label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_label_3.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_label_3.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_label_3.setObjectName("manual_monochromator_grating_label_3")
        self.gridLayout.addWidget(self.manual_monochromator_grating_label_3, 6, 0, 1, 1)
        self.manual_monochromator_grating_label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_grating_label_4.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_grating_label_4.setSizePolicy(sizePolicy)
        self.manual_monochromator_grating_label_4.setObjectName("manual_monochromator_grating_label_4")
        self.gridLayout.addWidget(self.manual_monochromator_grating_label_4, 6, 1, 1, 1)
        self.manual_monochromator_currentgrating_combobox = QtWidgets.QComboBox(Form)
        self.manual_monochromator_currentgrating_combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentgrating_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentgrating_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentgrating_combobox.setObjectName("manual_monochromator_currentgrating_combobox")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.manual_monochromator_currentgrating_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_currentgrating_combobox, 7, 0, 1, 1)
        self.manual_monochromator_newgrating_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newgrating_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newgrating_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_newgrating_combobox.setObjectName("manual_monochromator_newgrating_combobox")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.manual_monochromator_newgrating_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_newgrating_combobox, 7, 1, 1, 1)
        self.manual_monochromator_shutter_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_label.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_label.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_label.setObjectName("manual_monochromator_shutter_label")
        self.gridLayout.addWidget(self.manual_monochromator_shutter_label, 8, 0, 1, 1)
        self.manual_monochromator_shutter_label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_shutter_label_2.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_shutter_label_2.setSizePolicy(sizePolicy)
        self.manual_monochromator_shutter_label_2.setObjectName("manual_monochromator_shutter_label_2")
        self.gridLayout.addWidget(self.manual_monochromator_shutter_label_2, 8, 1, 1, 1)
        self.manual_monochromator_currentshutter_combobox = QtWidgets.QComboBox(Form)
        self.manual_monochromator_currentshutter_combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_currentshutter_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_currentshutter_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_currentshutter_combobox.setObjectName("manual_monochromator_currentshutter_combobox")
        self.manual_monochromator_currentshutter_combobox.addItem("")
        self.manual_monochromator_currentshutter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_currentshutter_combobox, 9, 0, 1, 1)
        self.manual_monochromator_newshutter_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_monochromator_newshutter_combobox.sizePolicy().hasHeightForWidth())
        self.manual_monochromator_newshutter_combobox.setSizePolicy(sizePolicy)
        self.manual_monochromator_newshutter_combobox.setObjectName("manual_monochromator_newshutter_combobox")
        self.manual_monochromator_newshutter_combobox.addItem("")
        self.manual_monochromator_newshutter_combobox.addItem("")
        self.gridLayout.addWidget(self.manual_monochromator_newshutter_combobox, 9, 1, 1, 1)
        self.manual_get_monochromator_all_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_get_monochromator_all_button.sizePolicy().hasHeightForWidth())
        self.manual_get_monochromator_all_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.manual_get_monochromator_all_button.setFont(font)
        self.manual_get_monochromator_all_button.setObjectName("manual_get_monochromator_all_button")
        self.gridLayout.addWidget(self.manual_get_monochromator_all_button, 10, 0, 1, 2)

        self.retranslateUi(Form)
        self.manual_monochromator_newfilter_combobox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monochromator"))
        self.manual_monochromator_label_2.setText(_translate("Form", "Monochromator:"))
        self.label_4.setText(_translate("Form", "Current Parameters:"))
        self.label_3.setText(_translate("Form", "New Parameters:"))
        self.manual_monochromator_wavelength_label_3.setText(_translate("Form", "Wavelength (um.):"))
        self.manual_monochromator_wavelength_label_4.setText(_translate("Form", "Wavelength (um.):"))
        self.manual_monochromator_curfilter_label.setText(_translate("Form", "Filter:"))
        self.manual_monochromator_newfilter_label.setText(_translate("Form", "Filter:"))
        self.manual_monochromator_currentfilter_combobox.setItemText(0, _translate("Form", "No OSF"))
        self.manual_monochromator_currentfilter_combobox.setItemText(1, _translate("Form", "OSF1"))
        self.manual_monochromator_currentfilter_combobox.setItemText(2, _translate("Form", "OSF2"))
        self.manual_monochromator_currentfilter_combobox.setItemText(3, _translate("Form", "OSF3"))
        self.manual_monochromator_newfilter_combobox.setItemText(0, _translate("Form", "No OSF"))
        self.manual_monochromator_newfilter_combobox.setItemText(1, _translate("Form", "Auto"))
        self.manual_monochromator_newfilter_combobox.setItemText(2, _translate("Form", "OSF1"))
        self.manual_monochromator_newfilter_combobox.setItemText(3, _translate("Form", "OSF2"))
        self.manual_monochromator_newfilter_combobox.setItemText(4, _translate("Form", "OSF3"))
        self.manual_monochromator_grating_label_3.setText(_translate("Form", "Grating:"))
        self.manual_monochromator_grating_label_4.setText(_translate("Form", "Grating:"))
        self.manual_monochromator_currentgrating_combobox.setItemText(0, _translate("Form", "G1"))
        self.manual_monochromator_currentgrating_combobox.setItemText(1, _translate("Form", "G2"))
        self.manual_monochromator_currentgrating_combobox.setItemText(2, _translate("Form", "G3"))
        self.manual_monochromator_newgrating_combobox.setItemText(0, _translate("Form", "Auto"))
        self.manual_monochromator_newgrating_combobox.setItemText(1, _translate("Form", "G1"))
        self.manual_monochromator_newgrating_combobox.setItemText(2, _translate("Form", "G2"))
        self.manual_monochromator_newgrating_combobox.setItemText(3, _translate("Form", "G3"))
        self.manual_monochromator_shutter_label.setText(_translate("Form", "Shutter:"))
        self.manual_monochromator_shutter_label_2.setText(_translate("Form", "Shutter:"))
        self.manual_monochromator_currentshutter_combobox.setItemText(0, _translate("Form", "Open"))
        self.manual_monochromator_currentshutter_combobox.setItemText(1, _translate("Form", "Close"))
        self.manual_monochromator_newshutter_combobox.setItemText(0, _translate("Form", "Open"))
        self.manual_monochromator_newshutter_combobox.setItemText(1, _translate("Form", "Close"))
        self.manual_get_monochromator_all_button.setText(_translate("Form", "-> Press Here to Set New Monochromator Parameters <-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

