# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cs260AutoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1982, 1615)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.lineedit_list_SavedSequences_passive_MonochromatorOsf1ToOsf2TransitionWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorOsf1ToOsf2TransitionWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorOsf1ToOsf2TransitionWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorOsf1ToOsf2TransitionWavelength, 9, 1, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorG2ToG3TransitionWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorG2ToG3TransitionWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorG2ToG3TransitionWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorG2ToG3TransitionWavelength, 7, 1, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorOsf2ToOsf3TransitionWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorOsf2ToOsf3TransitionWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorOsf2ToOsf3TransitionWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorOsf2ToOsf3TransitionWavelength, 10, 1, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorNoOsfToOsf1TransitionWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorNoOsfToOsf1TransitionWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorNoOsfToOsf1TransitionWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorNoOsfToOsf1TransitionWavelength, 8, 1, 1, 1)
        self.sequence_monochromator_startwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_startwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_startwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_startwave_label.setObjectName("sequence_monochromator_startwave_label")
        self.main_layout.addWidget(self.sequence_monochromator_startwave_label, 2, 0, 1, 1)
        self.sequence_monochromator_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_monochromator_label.setFont(font)
        self.sequence_monochromator_label.setObjectName("sequence_monochromator_label")
        self.main_layout.addWidget(self.sequence_monochromator_label, 0, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorEndWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorEndWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorEndWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorEndWavelength, 3, 1, 1, 1)
        self.sequence_monochromator_endwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_endwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_endwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_endwave_label.setObjectName("sequence_monochromator_endwave_label")
        self.main_layout.addWidget(self.sequence_monochromator_endwave_label, 3, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorStartWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorStartWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorStartWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorStartWavelength, 2, 1, 1, 1)
        self.sequence_monochromator_stepsize_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_stepsize_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_stepsize_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_stepsize_label.setObjectName("sequence_monochromator_stepsize_label")
        self.main_layout.addWidget(self.sequence_monochromator_stepsize_label, 4, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorStepSize = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorStepSize.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorStepSize")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorStepSize, 4, 1, 1, 1)
        self.sequence_monochromator_shutter_label = QtWidgets.QLabel(Form)
        self.sequence_monochromator_shutter_label.setObjectName("sequence_monochromator_shutter_label")
        self.main_layout.addWidget(self.sequence_monochromator_shutter_label, 5, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_MonochromatorG1ToG2TransitionWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_MonochromatorG1ToG2TransitionWavelength.setObjectName("lineedit_list_SavedSequences_passive_MonochromatorG1ToG2TransitionWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_MonochromatorG1ToG2TransitionWavelength, 6, 1, 1, 1)
        self.combobox_list_SavedSequences_passive_MonochromatorShutter = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_MonochromatorShutter.setObjectName("combobox_list_SavedSequences_passive_MonochromatorShutter")
        self.combobox_list_SavedSequences_passive_MonochromatorShutter.addItem("")
        self.combobox_list_SavedSequences_passive_MonochromatorShutter.addItem("")
        self.main_layout.addWidget(self.combobox_list_SavedSequences_passive_MonochromatorShutter, 5, 1, 1, 1)
        self.sequence_monochromator_g1g2_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g1g2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g1g2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g1g2_label.setObjectName("sequence_monochromator_g1g2_label")
        self.main_layout.addWidget(self.sequence_monochromator_g1g2_label, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 1, 0, 1, 2)
        self.sequence_monochromator_osf1osf2_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf1osf2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf1osf2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf1osf2_label.setObjectName("sequence_monochromator_osf1osf2_label")
        self.main_layout.addWidget(self.sequence_monochromator_osf1osf2_label, 9, 0, 1, 1)
        self.sequence_monochromator_g2g3_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g2g3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g2g3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g2g3_label.setObjectName("sequence_monochromator_g2g3_label")
        self.main_layout.addWidget(self.sequence_monochromator_g2g3_label, 7, 0, 1, 1)
        self.sequence_monochromator_osf2osf3_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf2osf3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf2osf3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf2osf3_label.setObjectName("sequence_monochromator_osf2osf3_label")
        self.main_layout.addWidget(self.sequence_monochromator_osf2osf3_label, 10, 0, 1, 1)
        self.sequence_monochromator_noosfosf1_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_noosfosf1_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_noosfosf1_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_noosfosf1_label.setObjectName("sequence_monochromator_noosfosf1_label")
        self.main_layout.addWidget(self.sequence_monochromator_noosfosf1_label, 8, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monochromator"))
        self.sequence_monochromator_startwave_label.setText(_translate("Form", "Start Wavelength (um.):"))
        self.sequence_monochromator_label.setText(_translate("Form", "Monochromator Sequence Control:"))
        self.sequence_monochromator_endwave_label.setText(_translate("Form", "End Wavelength (um.): "))
        self.sequence_monochromator_stepsize_label.setText(_translate("Form", "Step Size (um.): "))
        self.sequence_monochromator_shutter_label.setText(_translate("Form", "Shutter"))
        self.combobox_list_SavedSequences_passive_MonochromatorShutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_list_SavedSequences_passive_MonochromatorShutter.setItemText(1, _translate("Form", "Closed"))
        self.sequence_monochromator_g1g2_label.setText(_translate("Form", "G1 to G2 Transition Wavelength (um.):"))
        self.sequence_monochromator_osf1osf2_label.setText(_translate("Form", "OSF1 to OSF2 Transition Wavelength (um.):"))
        self.sequence_monochromator_g2g3_label.setText(_translate("Form", "G2 to G3 Transition Wavelength (um.):"))
        self.sequence_monochromator_osf2osf3_label.setText(_translate("Form", "OSF2 to OSF3 Transition Wavelength (um.):"))
        self.sequence_monochromator_noosfosf1_label.setText(_translate("Form", "No OSF to OSF1 Transition Wavelength (um.):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

