# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cs260Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1686, 1518)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength.sizePolicy().hasHeightForWidth())
        self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength.setSizePolicy(sizePolicy)
        self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength.setReadOnly(False)
        self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength.setObjectName("lineedit_base_CurrentMonochromatorParams_passive_Wavelength")
        self.gridLayout.addWidget(self.lineedit_base_CurrentMonochromatorParams_passive_Wavelength, 3, 0, 1, 1)
        self.lineedit_base_NewMonochromatorParams_passive_Wavelength = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineedit_base_NewMonochromatorParams_passive_Wavelength.sizePolicy().hasHeightForWidth())
        self.lineedit_base_NewMonochromatorParams_passive_Wavelength.setSizePolicy(sizePolicy)
        self.lineedit_base_NewMonochromatorParams_passive_Wavelength.setObjectName("lineedit_base_NewMonochromatorParams_passive_Wavelength")
        self.gridLayout.addWidget(self.lineedit_base_NewMonochromatorParams_passive_Wavelength, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setEnabled(False)
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setObjectName("combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter")
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter, 5, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter = QtWidgets.QComboBox(Form)
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setObjectName("combobox_base_NewMonochromatorParams_passive_OrderSortFilter")
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_Grating = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_CurrentMonochromatorParams_passive_Grating.sizePolicy().hasHeightForWidth())
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setSizePolicy(sizePolicy)
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setObjectName("combobox_base_CurrentMonochromatorParams_passive_Grating")
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_Grating, 7, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_Grating = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewMonochromatorParams_passive_Grating.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewMonochromatorParams_passive_Grating.setSizePolicy(sizePolicy)
        self.combobox_base_NewMonochromatorParams_passive_Grating.setObjectName("combobox_base_NewMonochromatorParams_passive_Grating")
        self.combobox_base_NewMonochromatorParams_passive_Grating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_Grating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_Grating.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_Grating.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_Grating, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter = QtWidgets.QComboBox(Form)
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_CurrentMonochromatorParams_passive_Shutter.sizePolicy().hasHeightForWidth())
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.setSizePolicy(sizePolicy)
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.setObjectName("combobox_base_CurrentMonochromatorParams_passive_Shutter")
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.addItem("")
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_CurrentMonochromatorParams_passive_Shutter, 9, 0, 1, 1)
        self.combobox_base_NewMonochromatorParams_passive_Shutter = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_base_NewMonochromatorParams_passive_Shutter.sizePolicy().hasHeightForWidth())
        self.combobox_base_NewMonochromatorParams_passive_Shutter.setSizePolicy(sizePolicy)
        self.combobox_base_NewMonochromatorParams_passive_Shutter.setObjectName("combobox_base_NewMonochromatorParams_passive_Shutter")
        self.combobox_base_NewMonochromatorParams_passive_Shutter.addItem("")
        self.combobox_base_NewMonochromatorParams_passive_Shutter.addItem("")
        self.gridLayout.addWidget(self.combobox_base_NewMonochromatorParams_passive_Shutter, 9, 1, 1, 1)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_base_NewMonochromatorParams_getter_NewMonoButton.sizePolicy().hasHeightForWidth())
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setFont(font)
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setObjectName("button_base_NewMonochromatorParams_getter_NewMonoButton")
        self.gridLayout.addWidget(self.button_base_NewMonochromatorParams_getter_NewMonoButton, 10, 0, 1, 2)

        self.retranslateUi(Form)
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monochromator"))
        self.label.setText(_translate("Form", "Monochromator:"))
        self.label_4.setText(_translate("Form", "Current Parameters:"))
        self.label_3.setText(_translate("Form", "New Parameters:"))
        self.label_10.setText(_translate("Form", "Wavelength (um.):"))
        self.label_11.setText(_translate("Form", "Wavelength (um.):"))
        self.label_2.setText(_translate("Form", "Filter:"))
        self.label_7.setText(_translate("Form", "Filter:"))
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setItemText(0, _translate("Form", "No OSF"))
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setItemText(1, _translate("Form", "OSF1"))
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setItemText(2, _translate("Form", "OSF2"))
        self.combobox_base_CurrentMonochromatorParams_passive_OrderSortFilter.setItemText(3, _translate("Form", "OSF3"))
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setItemText(0, _translate("Form", "No OSF"))
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setItemText(1, _translate("Form", "Auto"))
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setItemText(2, _translate("Form", "OSF1"))
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setItemText(3, _translate("Form", "OSF2"))
        self.combobox_base_NewMonochromatorParams_passive_OrderSortFilter.setItemText(4, _translate("Form", "OSF3"))
        self.label_5.setText(_translate("Form", "Grating:"))
        self.label_6.setText(_translate("Form", "Grating:"))
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setItemText(0, _translate("Form", "G1"))
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setItemText(1, _translate("Form", "G2"))
        self.combobox_base_CurrentMonochromatorParams_passive_Grating.setItemText(2, _translate("Form", "G3"))
        self.combobox_base_NewMonochromatorParams_passive_Grating.setItemText(0, _translate("Form", "Auto"))
        self.combobox_base_NewMonochromatorParams_passive_Grating.setItemText(1, _translate("Form", "G1"))
        self.combobox_base_NewMonochromatorParams_passive_Grating.setItemText(2, _translate("Form", "G2"))
        self.combobox_base_NewMonochromatorParams_passive_Grating.setItemText(3, _translate("Form", "G3"))
        self.label_8.setText(_translate("Form", "Shutter:"))
        self.label_9.setText(_translate("Form", "Shutter:"))
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_base_CurrentMonochromatorParams_passive_Shutter.setItemText(1, _translate("Form", "Close"))
        self.combobox_base_NewMonochromatorParams_passive_Shutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_base_NewMonochromatorParams_passive_Shutter.setItemText(1, _translate("Form", "Close"))
        self.button_base_NewMonochromatorParams_getter_NewMonoButton.setText(_translate("Form", "-> Press Here to Set New Monochromator Parameters <-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

