# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanWindowDialog5.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 519)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.autotab = QtWidgets.QWidget()
        self.autotab.setObjectName("autotab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.autotab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.autotab_line2 = QtWidgets.QFrame(self.autotab)
        self.autotab_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.autotab_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.autotab_line2.setObjectName("autotab_line2")
        self.gridLayout_2.addWidget(self.autotab_line2, 7, 0, 1, 2)
        self.autotab_data_label = QtWidgets.QLabel(self.autotab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.autotab_data_label.setFont(font)
        self.autotab_data_label.setObjectName("autotab_data_label")
        self.gridLayout_2.addWidget(self.autotab_data_label, 3, 0, 1, 2)
        self.autotab_line0 = QtWidgets.QFrame(self.autotab)
        self.autotab_line0.setFrameShape(QtWidgets.QFrame.HLine)
        self.autotab_line0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.autotab_line0.setObjectName("autotab_line0")
        self.gridLayout_2.addWidget(self.autotab_line0, 1, 0, 1, 2)
        self.autotab_runseries_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_runseries_button.setObjectName("autotab_runseries_button")
        self.gridLayout_2.addWidget(self.autotab_runseries_button, 9, 0, 1, 2)
        self.autotab_line1 = QtWidgets.QFrame(self.autotab)
        self.autotab_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.autotab_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.autotab_line1.setObjectName("autotab_line1")
        self.gridLayout_2.addWidget(self.autotab_line1, 4, 0, 1, 2)
        self.autotab_sequence_layout = QtWidgets.QVBoxLayout()
        self.autotab_sequence_layout.setObjectName("autotab_sequence_layout")
        self.autotab_sequencename_label = QtWidgets.QLabel(self.autotab)
        self.autotab_sequencename_label.setObjectName("autotab_sequencename_label")
        self.autotab_sequence_layout.addWidget(self.autotab_sequencename_label)
        self.autotab_sequencename_ledit = QtWidgets.QLineEdit(self.autotab)
        self.autotab_sequencename_ledit.setObjectName("autotab_sequencename_ledit")
        self.autotab_sequence_layout.addWidget(self.autotab_sequencename_ledit)
        self.autotab_savesequence_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_savesequence_button.setObjectName("autotab_savesequence_button")
        self.autotab_sequence_layout.addWidget(self.autotab_savesequence_button)
        self.autotab_savedsequences_label = QtWidgets.QLabel(self.autotab)
        self.autotab_savedsequences_label.setObjectName("autotab_savedsequences_label")
        self.autotab_sequence_layout.addWidget(self.autotab_savedsequences_label)
        self.autotab_savedsequences_list = QtWidgets.QListWidget(self.autotab)
        self.autotab_savedsequences_list.setObjectName("autotab_savedsequences_list")
        self.autotab_sequence_layout.addWidget(self.autotab_savedsequences_list)
        self.autotab_addsequencetoseries_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_addsequencetoseries_button.setObjectName("autotab_addsequencetoseries_button")
        self.autotab_sequence_layout.addWidget(self.autotab_addsequencetoseries_button)
        self.gridLayout_2.addLayout(self.autotab_sequence_layout, 2, 0, 1, 1)
        self.autotab_seriesconstruct_label = QtWidgets.QLabel(self.autotab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.autotab_seriesconstruct_label.setFont(font)
        self.autotab_seriesconstruct_label.setObjectName("autotab_seriesconstruct_label")
        self.gridLayout_2.addWidget(self.autotab_seriesconstruct_label, 0, 0, 1, 1)
        self.autotab_control_label = QtWidgets.QLabel(self.autotab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.autotab_control_label.setFont(font)
        self.autotab_control_label.setObjectName("autotab_control_label")
        self.gridLayout_2.addWidget(self.autotab_control_label, 6, 0, 1, 2)
        self.autotab_series_layout = QtWidgets.QVBoxLayout()
        self.autotab_series_layout.setObjectName("autotab_series_layout")
        self.autotab_series_label = QtWidgets.QLabel(self.autotab)
        self.autotab_series_label.setObjectName("autotab_series_label")
        self.autotab_series_layout.addWidget(self.autotab_series_label)
        self.autotab_series_list = QtWidgets.QListWidget(self.autotab)
        self.autotab_series_list.setObjectName("autotab_series_list")
        self.autotab_series_layout.addWidget(self.autotab_series_list)
        self.autotab_removesequence_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_removesequence_button.setObjectName("autotab_removesequence_button")
        self.autotab_series_layout.addWidget(self.autotab_removesequence_button)
        self.autotab_removeallsequences_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_removeallsequences_button.setObjectName("autotab_removeallsequences_button")
        self.autotab_series_layout.addWidget(self.autotab_removeallsequences_button)
        self.gridLayout_2.addLayout(self.autotab_series_layout, 2, 1, 1, 1)
        self.autotab_pauseseries_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_pauseseries_button.setObjectName("autotab_pauseseries_button")
        self.gridLayout_2.addWidget(self.autotab_pauseseries_button, 11, 0, 1, 2)
        self.autotab_abortseries_button = QtWidgets.QPushButton(self.autotab)
        self.autotab_abortseries_button.setObjectName("autotab_abortseries_button")
        self.gridLayout_2.addWidget(self.autotab_abortseries_button, 12, 0, 1, 2)
        self.autotab_data_layout = QtWidgets.QGridLayout()
        self.autotab_data_layout.setObjectName("autotab_data_layout")
        self.autotab_metadata_ndf_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_ndf_checkbox.setChecked(True)
        self.autotab_metadata_ndf_checkbox.setObjectName("autotab_metadata_ndf_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_ndf_checkbox, 6, 2, 1, 1)
        self.autotab_integrationtime_label = QtWidgets.QLabel(self.autotab)
        self.autotab_integrationtime_label.setObjectName("autotab_integrationtime_label")
        self.autotab_data_layout.addWidget(self.autotab_integrationtime_label, 4, 5, 1, 1)
        self.autotab_metadata_grating_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_grating_checkbox.setChecked(True)
        self.autotab_metadata_grating_checkbox.setObjectName("autotab_metadata_grating_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_grating_checkbox, 5, 2, 1, 1)
        self.autotab_metadata_cryo_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_cryo_checkbox.setChecked(True)
        self.autotab_metadata_cryo_checkbox.setObjectName("autotab_metadata_cryo_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_cryo_checkbox, 5, 0, 1, 2)
        self.autotab_metadata_powermeter_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_powermeter_checkbox.setChecked(True)
        self.autotab_metadata_powermeter_checkbox.setObjectName("autotab_metadata_powermeter_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_powermeter_checkbox, 6, 0, 1, 2)
        self.autotab_metadata_label = QtWidgets.QLabel(self.autotab)
        self.autotab_metadata_label.setObjectName("autotab_metadata_label")
        self.autotab_data_layout.addWidget(self.autotab_metadata_label, 3, 0, 2, 5)
        self.autotab_metadata_integrationtime_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_integrationtime_checkbox.setChecked(True)
        self.autotab_metadata_integrationtime_checkbox.setObjectName("autotab_metadata_integrationtime_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_integrationtime_checkbox, 5, 3, 1, 2)
        self.autotab_metadata_wavelength_checkbox = QtWidgets.QCheckBox(self.autotab)
        self.autotab_metadata_wavelength_checkbox.setChecked(True)
        self.autotab_metadata_wavelength_checkbox.setObjectName("autotab_metadata_wavelength_checkbox")
        self.autotab_data_layout.addWidget(self.autotab_metadata_wavelength_checkbox, 6, 3, 1, 2)
        self.autotab_integrationtime_ledit = QtWidgets.QLineEdit(self.autotab)
        self.autotab_integrationtime_ledit.setObjectName("autotab_integrationtime_ledit")
        self.autotab_data_layout.addWidget(self.autotab_integrationtime_ledit, 5, 5, 2, 1)
        self.autotab_storageformat_label = QtWidgets.QLabel(self.autotab)
        self.autotab_storageformat_label.setObjectName("autotab_storageformat_label")
        self.autotab_data_layout.addWidget(self.autotab_storageformat_label, 7, 5, 1, 1)
        self.autotab_storageformat_combobox = QtWidgets.QComboBox(self.autotab)
        self.autotab_storageformat_combobox.setObjectName("autotab_storageformat_combobox")
        self.autotab_storageformat_combobox.addItem("")
        self.autotab_storageformat_combobox.addItem("")
        self.autotab_storageformat_combobox.addItem("")
        self.autotab_storageformat_combobox.addItem("")
        self.autotab_data_layout.addWidget(self.autotab_storageformat_combobox, 8, 5, 1, 1)
        self.autotab_storagepath_label = QtWidgets.QLabel(self.autotab)
        self.autotab_storagepath_label.setObjectName("autotab_storagepath_label")
        self.autotab_data_layout.addWidget(self.autotab_storagepath_label, 7, 0, 1, 5)
        self.autotab_storagepath_ledit = QtWidgets.QLineEdit(self.autotab)
        self.autotab_storagepath_ledit.setObjectName("autotab_storagepath_ledit")
        self.autotab_data_layout.addWidget(self.autotab_storagepath_ledit, 8, 0, 1, 5)
        self.gridLayout_2.addLayout(self.autotab_data_layout, 5, 0, 1, 2)
        self.tabWidget.addTab(self.autotab, "")
        self.monochromator = QtWidgets.QWidget()
        self.monochromator.setObjectName("monochromator")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.monochromator)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.monochromator_sequencecontrol_grating_label = QtWidgets.QLabel(self.monochromator)
        self.monochromator_sequencecontrol_grating_label.setObjectName("monochromator_sequencecontrol_grating_label")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_grating_label, 18, 0, 1, 1)
        self.monochromator_sequencecontrol_step_ledit = QtWidgets.QLineEdit(self.monochromator)
        self.monochromator_sequencecontrol_step_ledit.setObjectName("monochromator_sequencecontrol_step_ledit")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_step_ledit, 17, 0, 1, 2)
        self.monochromator_manualcontrol_shutter_combobox = QtWidgets.QComboBox(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_shutter_combobox.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_shutter_combobox.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_shutter_combobox.setEditable(True)
        self.monochromator_manualcontrol_shutter_combobox.setObjectName("monochromator_manualcontrol_shutter_combobox")
        self.monochromator_manualcontrol_shutter_combobox.addItem("")
        self.monochromator_manualcontrol_shutter_combobox.addItem("")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_shutter_combobox, 9, 0, 1, 1)
        self.monochromator_sequencecontrol_grating_combobox = QtWidgets.QComboBox(self.monochromator)
        self.monochromator_sequencecontrol_grating_combobox.setObjectName("monochromator_sequencecontrol_grating_combobox")
        self.monochromator_sequencecontrol_grating_combobox.addItem("")
        self.monochromator_sequencecontrol_grating_combobox.addItem("")
        self.monochromator_sequencecontrol_grating_combobox.addItem("")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_grating_combobox, 19, 0, 1, 2)
        self.monochromator_manualcontrol_wavelength_label = QtWidgets.QLabel(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_wavelength_label.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_wavelength_label.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_wavelength_label.setObjectName("monochromator_manualcontrol_wavelength_label")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_wavelength_label, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.monochromator)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 2)
        self.monochromator_manualcontrol_grating_combobox = QtWidgets.QComboBox(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_grating_combobox.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_grating_combobox.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_grating_combobox.setEditable(True)
        self.monochromator_manualcontrol_grating_combobox.setObjectName("monochromator_manualcontrol_grating_combobox")
        self.monochromator_manualcontrol_grating_combobox.addItem("")
        self.monochromator_manualcontrol_grating_combobox.addItem("")
        self.monochromator_manualcontrol_grating_combobox.addItem("")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_grating_combobox, 7, 0, 1, 1)
        self.monochromator_manualcontrol_wavelength_ledit = QtWidgets.QLineEdit(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_wavelength_ledit.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_wavelength_ledit.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_wavelength_ledit.setObjectName("monochromator_manualcontrol_wavelength_ledit")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_wavelength_ledit, 3, 0, 1, 1)
        self.monochromator_sequencecontrol_step_label = QtWidgets.QLabel(self.monochromator)
        self.monochromator_sequencecontrol_step_label.setObjectName("monochromator_sequencecontrol_step_label")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_step_label, 16, 0, 1, 1)
        self.monochromator_sequencecontrol_label = QtWidgets.QLabel(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_sequencecontrol_label.sizePolicy().hasHeightForWidth())
        self.monochromator_sequencecontrol_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monochromator_sequencecontrol_label.setFont(font)
        self.monochromator_sequencecontrol_label.setObjectName("monochromator_sequencecontrol_label")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_label, 10, 0, 1, 2)
        self.monochromator_sequencecontrol_endwave_ledit = QtWidgets.QLineEdit(self.monochromator)
        self.monochromator_sequencecontrol_endwave_ledit.setObjectName("monochromator_sequencecontrol_endwave_ledit")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_endwave_ledit, 15, 0, 1, 2)
        self.monochromator_sequencecontrol_startwave_ledit = QtWidgets.QLineEdit(self.monochromator)
        self.monochromator_sequencecontrol_startwave_ledit.setObjectName("monochromator_sequencecontrol_startwave_ledit")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_startwave_ledit, 13, 0, 1, 2)
        self.monochromator_manualcontrol_abort = QtWidgets.QPushButton(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_abort.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_abort.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_abort.setObjectName("monochromator_manualcontrol_abort")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_abort, 7, 1, 3, 1)
        self.monochromator_manualcontrol_osf_label = QtWidgets.QLabel(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_osf_label.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_osf_label.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_osf_label.setObjectName("monochromator_manualcontrol_osf_label")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_osf_label, 4, 0, 1, 1)
        self.monochromator_manualcontrol_osf_combobox = QtWidgets.QComboBox(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_osf_combobox.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_osf_combobox.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_osf_combobox.setEditable(True)
        self.monochromator_manualcontrol_osf_combobox.setObjectName("monochromator_manualcontrol_osf_combobox")
        self.monochromator_manualcontrol_osf_combobox.addItem("")
        self.monochromator_manualcontrol_osf_combobox.addItem("")
        self.monochromator_manualcontrol_osf_combobox.addItem("")
        self.monochromator_manualcontrol_osf_combobox.addItem("")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_osf_combobox, 5, 0, 1, 1)
        self.monochromator_manualcontrol_grating_label = QtWidgets.QLabel(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_grating_label.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_grating_label.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_grating_label.setObjectName("monochromator_manualcontrol_grating_label")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_grating_label, 6, 0, 1, 1)
        self.monochromator_sequencecontrol_startwave_label = QtWidgets.QLabel(self.monochromator)
        self.monochromator_sequencecontrol_startwave_label.setObjectName("monochromator_sequencecontrol_startwave_label")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_startwave_label, 12, 0, 1, 1)
        self.monochromator_manualcontrol_label = QtWidgets.QLabel(self.monochromator)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monochromator_manualcontrol_label.setFont(font)
        self.monochromator_manualcontrol_label.setObjectName("monochromator_manualcontrol_label")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_label, 0, 0, 1, 1)
        self.monochromator_manualcontrol_setparameters_button = QtWidgets.QPushButton(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_setparameters_button.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_setparameters_button.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_setparameters_button.setObjectName("monochromator_manualcontrol_setparameters_button")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_setparameters_button, 3, 1, 3, 1)
        self.monochromator_sequencecontrol_endwave_label = QtWidgets.QLabel(self.monochromator)
        self.monochromator_sequencecontrol_endwave_label.setObjectName("monochromator_sequencecontrol_endwave_label")
        self.gridLayout_3.addWidget(self.monochromator_sequencecontrol_endwave_label, 14, 0, 1, 1)
        self.monochromator_manualcontrol_shutter_label = QtWidgets.QLabel(self.monochromator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monochromator_manualcontrol_shutter_label.sizePolicy().hasHeightForWidth())
        self.monochromator_manualcontrol_shutter_label.setSizePolicy(sizePolicy)
        self.monochromator_manualcontrol_shutter_label.setObjectName("monochromator_manualcontrol_shutter_label")
        self.gridLayout_3.addWidget(self.monochromator_manualcontrol_shutter_label, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.monochromator)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 11, 0, 1, 2)
        self.tabWidget.addTab(self.monochromator, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.autotab_data_label.setText(_translate("Dialog", "Data Configuration:"))
        self.autotab_runseries_button.setText(_translate("Dialog", "Run Series"))
        self.autotab_sequencename_label.setText(_translate("Dialog", "Sequence Name:"))
        self.autotab_savesequence_button.setText(_translate("Dialog", "Save New Sequence"))
        self.autotab_savedsequences_label.setText(_translate("Dialog", "Saved Sequences:"))
        self.autotab_addsequencetoseries_button.setText(_translate("Dialog", "Add Sequence To Series"))
        self.autotab_seriesconstruct_label.setText(_translate("Dialog", "Series Construction:"))
        self.autotab_control_label.setText(_translate("Dialog", "Control:"))
        self.autotab_series_label.setText(_translate("Dialog", "Series:"))
        self.autotab_removesequence_button.setText(_translate("Dialog", "Remove Sequence From Series"))
        self.autotab_removeallsequences_button.setText(_translate("Dialog", "Remove All Sequences From Series"))
        self.autotab_pauseseries_button.setText(_translate("Dialog", "Pause Series"))
        self.autotab_abortseries_button.setText(_translate("Dialog", "Abort Series"))
        self.autotab_metadata_ndf_checkbox.setText(_translate("Dialog", "NDF Wheel"))
        self.autotab_integrationtime_label.setText(_translate("Dialog", "Integration Time (s.):"))
        self.autotab_metadata_grating_checkbox.setText(_translate("Dialog", "Grating"))
        self.autotab_metadata_cryo_checkbox.setText(_translate("Dialog", "Cryo Temperature"))
        self.autotab_metadata_powermeter_checkbox.setText(_translate("Dialog", "Power Meter"))
        self.autotab_metadata_label.setText(_translate("Dialog", "Metadata to Include:"))
        self.autotab_metadata_integrationtime_checkbox.setText(_translate("Dialog", "Integration Time"))
        self.autotab_metadata_wavelength_checkbox.setText(_translate("Dialog", "Wavelength"))
        self.autotab_storageformat_label.setText(_translate("Dialog", "Storage Format:"))
        self.autotab_storageformat_combobox.setItemText(0, _translate("Dialog", ".csv"))
        self.autotab_storageformat_combobox.setItemText(1, _translate("Dialog", ".fits"))
        self.autotab_storageformat_combobox.setItemText(2, _translate("Dialog", ".json"))
        self.autotab_storageformat_combobox.setItemText(3, _translate("Dialog", ".parquet"))
        self.autotab_storagepath_label.setText(_translate("Dialog", "Storage Path:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autotab), _translate("Dialog", "Automation"))
        self.monochromator_sequencecontrol_grating_label.setText(_translate("Dialog", "Grating:"))
        self.monochromator_manualcontrol_shutter_combobox.setItemText(0, _translate("Dialog", "Open"))
        self.monochromator_manualcontrol_shutter_combobox.setItemText(1, _translate("Dialog", "Close"))
        self.monochromator_sequencecontrol_grating_combobox.setItemText(0, _translate("Dialog", "G1"))
        self.monochromator_sequencecontrol_grating_combobox.setItemText(1, _translate("Dialog", "G2"))
        self.monochromator_sequencecontrol_grating_combobox.setItemText(2, _translate("Dialog", "G3"))
        self.monochromator_manualcontrol_wavelength_label.setText(_translate("Dialog", "Wavelength (um.):"))
        self.monochromator_manualcontrol_grating_combobox.setItemText(0, _translate("Dialog", "G1"))
        self.monochromator_manualcontrol_grating_combobox.setItemText(1, _translate("Dialog", "G2"))
        self.monochromator_manualcontrol_grating_combobox.setItemText(2, _translate("Dialog", "G3"))
        self.monochromator_sequencecontrol_step_label.setText(_translate("Dialog", "Step Size (nm.):"))
        self.monochromator_sequencecontrol_label.setText(_translate("Dialog", "Sequence Control:"))
        self.monochromator_manualcontrol_abort.setText(_translate("Dialog", "Abort"))
        self.monochromator_manualcontrol_osf_label.setText(_translate("Dialog", "Filter:"))
        self.monochromator_manualcontrol_osf_combobox.setItemText(0, _translate("Dialog", "OSF1"))
        self.monochromator_manualcontrol_osf_combobox.setItemText(1, _translate("Dialog", "OSF2"))
        self.monochromator_manualcontrol_osf_combobox.setItemText(2, _translate("Dialog", "OSF3"))
        self.monochromator_manualcontrol_osf_combobox.setItemText(3, _translate("Dialog", "OSF4"))
        self.monochromator_manualcontrol_grating_label.setText(_translate("Dialog", "Grating:"))
        self.monochromator_sequencecontrol_startwave_label.setText(_translate("Dialog", "Start Wavelength (um.):"))
        self.monochromator_manualcontrol_label.setText(_translate("Dialog", "Manual Control:"))
        self.monochromator_manualcontrol_setparameters_button.setText(_translate("Dialog", "Set Parameters"))
        self.monochromator_sequencecontrol_endwave_label.setText(_translate("Dialog", "End Wavelength (um.):"))
        self.monochromator_manualcontrol_shutter_label.setText(_translate("Dialog", "Shutter:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monochromator), _translate("Dialog", "Monochromator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
