# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequenceWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(626, 428)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.sequence_lockin_sampletime_label = QtWidgets.QLabel(Form)
        self.sequence_lockin_sampletime_label.setObjectName("sequence_lockin_sampletime_label")
        self.gridLayout.addWidget(self.sequence_lockin_sampletime_label, 14, 0, 1, 1)
        self.sequence_monochromator_stepsize_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_stepsize_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_stepsize_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_stepsize_label.setObjectName("sequence_monochromator_stepsize_label")
        self.gridLayout.addWidget(self.sequence_monochromator_stepsize_label, 5, 0, 1, 1)
        self.sequence_lockin_samplefreq_label = QtWidgets.QLabel(Form)
        self.sequence_lockin_samplefreq_label.setObjectName("sequence_lockin_samplefreq_label")
        self.gridLayout.addWidget(self.sequence_lockin_samplefreq_label, 13, 0, 1, 1)
        self.sequence_lockin_sampletime_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_lockin_sampletime_ledit.setObjectName("sequence_lockin_sampletime_ledit")
        self.gridLayout.addWidget(self.sequence_lockin_sampletime_ledit, 14, 1, 1, 1)
        self.sequence_monochromator_osf2osf3_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf2osf3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf2osf3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf2osf3_label.setObjectName("sequence_monochromator_osf2osf3_label")
        self.gridLayout.addWidget(self.sequence_monochromator_osf2osf3_label, 10, 0, 1, 1)
        self.sequence_monochromator_osf1osf2_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_osf1osf2_ledit.setObjectName("sequence_monochromator_osf1osf2_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_osf1osf2_ledit, 9, 1, 1, 1)
        self.sequence_lockin_samplefreq_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_lockin_samplefreq_ledit.setObjectName("sequence_lockin_samplefreq_ledit")
        self.gridLayout.addWidget(self.sequence_lockin_samplefreq_ledit, 13, 1, 1, 1)
        self.sequence_lockin_timeconstant_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_lockin_timeconstant_ledit.setObjectName("sequence_lockin_timeconstant_ledit")
        self.gridLayout.addWidget(self.sequence_lockin_timeconstant_ledit, 15, 1, 1, 1)
        self.sequence_monochromator_startwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_startwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_startwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_startwave_label.setObjectName("sequence_monochromator_startwave_label")
        self.gridLayout.addWidget(self.sequence_monochromator_startwave_label, 3, 0, 1, 1)
        self.sequence_monochromator_g2g3_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g2g3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g2g3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g2g3_label.setObjectName("sequence_monochromator_g2g3_label")
        self.gridLayout.addWidget(self.sequence_monochromator_g2g3_label, 7, 0, 1, 1)
        self.sequence_monochromator_osf2osf3_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_osf2osf3_ledit.setObjectName("sequence_monochromator_osf2osf3_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_osf2osf3_ledit, 10, 1, 1, 1)
        self.sequence_monochromator_startwave_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_startwave_ledit.setObjectName("sequence_monochromator_startwave_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_startwave_ledit, 3, 1, 1, 1)
        self.sequence_monochromator_endwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_endwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_endwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_endwave_label.setObjectName("sequence_monochromator_endwave_label")
        self.gridLayout.addWidget(self.sequence_monochromator_endwave_label, 4, 0, 1, 1)
        self.sequence_monochromator_g2g3_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_g2g3_ledit.setObjectName("sequence_monochromator_g2g3_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_g2g3_ledit, 7, 1, 1, 1)
        self.sequence_lockin_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_lockin_label.sizePolicy().hasHeightForWidth())
        self.sequence_lockin_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_lockin_label.setFont(font)
        self.sequence_lockin_label.setObjectName("sequence_lockin_label")
        self.gridLayout.addWidget(self.sequence_lockin_label, 11, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.sequence_monochromator_osf1osf2_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf1osf2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf1osf2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf1osf2_label.setObjectName("sequence_monochromator_osf1osf2_label")
        self.gridLayout.addWidget(self.sequence_monochromator_osf1osf2_label, 9, 0, 1, 1)
        self.sequence_monochromator_noosfosf1_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_noosfosf1_ledit.setObjectName("sequence_monochromator_noosfosf1_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_noosfosf1_ledit, 8, 1, 1, 1)
        self.sequence_monochromator_noosfosf1_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_noosfosf1_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_noosfosf1_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_noosfosf1_label.setObjectName("sequence_monochromator_noosfosf1_label")
        self.gridLayout.addWidget(self.sequence_monochromator_noosfosf1_label, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 2)
        self.sequence_monochromator_stepsize_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_stepsize_ledit.setObjectName("sequence_monochromator_stepsize_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_stepsize_ledit, 5, 1, 1, 1)
        self.sequence_monochromator_g1g2_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_g1g2_ledit.setObjectName("sequence_monochromator_g1g2_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_g1g2_ledit, 6, 1, 1, 1)
        self.sequence_monochromator_g1g2_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_g1g2_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_g1g2_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_g1g2_label.setObjectName("sequence_monochromator_g1g2_label")
        self.gridLayout.addWidget(self.sequence_monochromator_g1g2_label, 6, 0, 1, 1)
        self.sequence_monochromator_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_monochromator_label.setFont(font)
        self.sequence_monochromator_label.setObjectName("sequence_monochromator_label")
        self.gridLayout.addWidget(self.sequence_monochromator_label, 0, 0, 1, 2)
        self.sequence_monochromator_endwave_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_monochromator_endwave_ledit.setObjectName("sequence_monochromator_endwave_ledit")
        self.gridLayout.addWidget(self.sequence_monochromator_endwave_ledit, 4, 1, 1, 1)
        self.sequence_lockin_timeconstant_label = QtWidgets.QLabel(Form)
        self.sequence_lockin_timeconstant_label.setObjectName("sequence_lockin_timeconstant_label")
        self.gridLayout.addWidget(self.sequence_lockin_timeconstant_label, 15, 0, 1, 1)
        self.sequence_lockin_sensitivity_label = QtWidgets.QLabel(Form)
        self.sequence_lockin_sensitivity_label.setObjectName("sequence_lockin_sensitivity_label")
        self.gridLayout.addWidget(self.sequence_lockin_sensitivity_label, 16, 0, 1, 1)
        self.sequence_lockin_sensitivity_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_lockin_sensitivity_ledit.setObjectName("sequence_lockin_sensitivity_ledit")
        self.gridLayout.addWidget(self.sequence_lockin_sensitivity_ledit, 16, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sequence_lockin_sampletime_label.setText(_translate("Form", "Sample Time (s.):"))
        self.sequence_monochromator_stepsize_label.setText(_translate("Form", "Step Size (nm.): "))
        self.sequence_lockin_samplefreq_label.setText(_translate("Form", "Sample Frequency (Hz.):"))
        self.sequence_monochromator_osf2osf3_label.setText(_translate("Form", "OSF2 to OSF3 Transition Wavelength (um.):"))
        self.sequence_monochromator_startwave_label.setText(_translate("Form", "Start Wavelength (um.):"))
        self.sequence_monochromator_g2g3_label.setText(_translate("Form", "G2 to G3 Transition Wavelength (um.):"))
        self.sequence_monochromator_endwave_label.setText(_translate("Form", "End Wavelength (um.): "))
        self.sequence_lockin_label.setText(_translate("Form", "Lock-In:"))
        self.sequence_monochromator_osf1osf2_label.setText(_translate("Form", "OSF1 to OSF2 Transition Wavelength (um.):"))
        self.sequence_monochromator_noosfosf1_label.setText(_translate("Form", "No OSF to OSF1 Transition Wavelength (um.):"))
        self.sequence_monochromator_g1g2_label.setText(_translate("Form", "G1 to G2 Transition Wavelength (um.):"))
        self.sequence_monochromator_label.setText(_translate("Form", "Monochromator:"))
        self.sequence_lockin_timeconstant_label.setText(_translate("Form", "Time Constant (s.):"))
        self.sequence_lockin_sensitivity_label.setText(_translate("Form", "Sensitivity String:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
