# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndfAutoWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1968, 1609)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.sequence_ndf_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndf_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndf_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_ndf_label.setFont(font)
        self.sequence_ndf_label.setObjectName("sequence_ndf_label")
        self.main_layout.addWidget(self.sequence_ndf_label, 0, 1, 1, 2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.main_layout.addWidget(self.line_2, 1, 1, 1, 2)
        self.sequence_ndftransitions_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndftransitions_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndftransitions_label.setSizePolicy(sizePolicy)
        self.sequence_ndftransitions_label.setObjectName("sequence_ndftransitions_label")
        self.main_layout.addWidget(self.sequence_ndftransitions_label, 2, 1, 1, 2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 4, 1, 1, 2)
        self.list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions.sizePolicy().hasHeightForWidth())
        self.list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions.setSizePolicy(sizePolicy)
        self.list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions.setObjectName("list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions")
        self.main_layout.addWidget(self.list_listXlist_NdfTransitionsXSavedSequences_listXPassiveListAll_NdfPositionTransitions, 3, 1, 1, 2)
        self.button_list_NdfTransitions_setter_AddNdfTransitionButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_list_NdfTransitions_setter_AddNdfTransitionButton.sizePolicy().hasHeightForWidth())
        self.button_list_NdfTransitions_setter_AddNdfTransitionButton.setSizePolicy(sizePolicy)
        self.button_list_NdfTransitions_setter_AddNdfTransitionButton.setObjectName("button_list_NdfTransitions_setter_AddNdfTransitionButton")
        self.main_layout.addWidget(self.button_list_NdfTransitions_setter_AddNdfTransitionButton, 7, 1, 1, 2)
        self.lineedit_list_NdfTransitions_ItemDisplay_wavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_NdfTransitions_ItemDisplay_wavelength.setObjectName("lineedit_list_NdfTransitions_ItemDisplay_wavelength")
        self.main_layout.addWidget(self.lineedit_list_NdfTransitions_ItemDisplay_wavelength, 6, 1, 1, 1)
        self.button_list_NdfTransitions_remover_RemoveNdfTransitionButton = QtWidgets.QPushButton(Form)
        self.button_list_NdfTransitions_remover_RemoveNdfTransitionButton.setObjectName("button_list_NdfTransitions_remover_RemoveNdfTransitionButton")
        self.main_layout.addWidget(self.button_list_NdfTransitions_remover_RemoveNdfTransitionButton, 8, 1, 1, 2)
        self.sequence_ndfwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndfwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndfwave_label.setSizePolicy(sizePolicy)
        self.sequence_ndfwave_label.setObjectName("sequence_ndfwave_label")
        self.main_layout.addWidget(self.sequence_ndfwave_label, 5, 1, 1, 1)
        self.sequence_ndfpos_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndfpos_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndfpos_label.setSizePolicy(sizePolicy)
        self.sequence_ndfpos_label.setObjectName("sequence_ndfpos_label")
        self.main_layout.addWidget(self.sequence_ndfpos_label, 5, 2, 1, 1)
        self.lineedit_list_NdfTransitions_ItemDisplay_position = QtWidgets.QLineEdit(Form)
        self.lineedit_list_NdfTransitions_ItemDisplay_position.setObjectName("lineedit_list_NdfTransitions_ItemDisplay_position")
        self.main_layout.addWidget(self.lineedit_list_NdfTransitions_ItemDisplay_position, 6, 2, 1, 1)
        self.button_list_NdfTransitions_RemoverOfAll_RemoveAllNdfTransitionsButton = QtWidgets.QPushButton(Form)
        self.button_list_NdfTransitions_RemoverOfAll_RemoveAllNdfTransitionsButton.setObjectName("button_list_NdfTransitions_RemoverOfAll_RemoveAllNdfTransitionsButton")
        self.main_layout.addWidget(self.button_list_NdfTransitions_RemoverOfAll_RemoveAllNdfTransitionsButton, 9, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "NDF Wheel"))
        self.sequence_ndf_label.setText(_translate("Form", "NDF Sequence Control:"))
        self.sequence_ndftransitions_label.setText(_translate("Form", "NDF Transitions in Sequence:"))
        self.button_list_NdfTransitions_setter_AddNdfTransitionButton.setText(_translate("Form", "Add NDF Transition to Sequence"))
        self.button_list_NdfTransitions_remover_RemoveNdfTransitionButton.setText(_translate("Form", "Remove NDF Transition From Sequence"))
        self.sequence_ndfwave_label.setText(_translate("Form", "Wavelength (um.):"))
        self.sequence_ndfpos_label.setText(_translate("Form", "NDF Position:"))
        self.button_list_NdfTransitions_RemoverOfAll_RemoveAllNdfTransitionsButton.setText(_translate("Form", "Remove All NDF Transitions From Sequence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

