# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndfAutoWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 969)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.sequence_ndf_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndf_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndf_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_ndf_label.setFont(font)
        self.sequence_ndf_label.setObjectName("sequence_ndf_label")
        self.main_layout.addWidget(self.sequence_ndf_label, 0, 1, 1, 2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.main_layout.addWidget(self.line_2, 1, 1, 1, 2)
        self.sequence_ndftransitions_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndftransitions_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndftransitions_label.setSizePolicy(sizePolicy)
        self.sequence_ndftransitions_label.setObjectName("sequence_ndftransitions_label")
        self.main_layout.addWidget(self.sequence_ndftransitions_label, 2, 1, 1, 2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 4, 1, 1, 2)
        self.sequence_ndftransitions_list = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndftransitions_list.sizePolicy().hasHeightForWidth())
        self.sequence_ndftransitions_list.setSizePolicy(sizePolicy)
        self.sequence_ndftransitions_list.setObjectName("sequence_ndftransitions_list")
        self.main_layout.addWidget(self.sequence_ndftransitions_list, 3, 1, 1, 2)
        self.sequence_ndfaddtransition_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndfaddtransition_button.sizePolicy().hasHeightForWidth())
        self.sequence_ndfaddtransition_button.setSizePolicy(sizePolicy)
        self.sequence_ndfaddtransition_button.setObjectName("sequence_ndfaddtransition_button")
        self.main_layout.addWidget(self.sequence_ndfaddtransition_button, 7, 1, 1, 2)
        self.sequence_ndfwave_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_ndfwave_ledit.setObjectName("sequence_ndfwave_ledit")
        self.main_layout.addWidget(self.sequence_ndfwave_ledit, 6, 1, 1, 1)
        self.sequence_ndfremovetransition_button = QtWidgets.QPushButton(Form)
        self.sequence_ndfremovetransition_button.setObjectName("sequence_ndfremovetransition_button")
        self.main_layout.addWidget(self.sequence_ndfremovetransition_button, 8, 1, 1, 2)
        self.sequence_ndfwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndfwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndfwave_label.setSizePolicy(sizePolicy)
        self.sequence_ndfwave_label.setObjectName("sequence_ndfwave_label")
        self.main_layout.addWidget(self.sequence_ndfwave_label, 5, 1, 1, 1)
        self.sequence_ndfpos_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_ndfpos_label.sizePolicy().hasHeightForWidth())
        self.sequence_ndfpos_label.setSizePolicy(sizePolicy)
        self.sequence_ndfpos_label.setObjectName("sequence_ndfpos_label")
        self.main_layout.addWidget(self.sequence_ndfpos_label, 5, 2, 1, 1)
        self.sequence_ndfpos_ledit = QtWidgets.QLineEdit(Form)
        self.sequence_ndfpos_ledit.setObjectName("sequence_ndfpos_ledit")
        self.main_layout.addWidget(self.sequence_ndfpos_ledit, 6, 2, 1, 1)
        self.sequence_ndf_removealltransitions_button = QtWidgets.QPushButton(Form)
        self.sequence_ndf_removealltransitions_button.setObjectName("sequence_ndf_removealltransitions_button")
        self.main_layout.addWidget(self.sequence_ndf_removealltransitions_button, 9, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "NDF Wheel"))
        self.sequence_ndf_label.setText(_translate("Form", "NDF Sequence Control:"))
        self.sequence_ndftransitions_label.setText(_translate("Form", "NDF Transitions in Sequence:"))
        self.sequence_ndfaddtransition_button.setText(_translate("Form", "Add NDF Transition to Sequence"))
        self.sequence_ndfremovetransition_button.setText(_translate("Form", "Remove NDF Transition From Sequence"))
        self.sequence_ndfwave_label.setText(_translate("Form", "Wavelength (um.):"))
        self.sequence_ndfpos_label.setText(_translate("Form", "NDF Position:"))
        self.sequence_ndf_removealltransitions_button.setText(_translate("Form", "Remove All NDF Transitions From Sequence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

