# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTDesigner/cs260AutoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 1129)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.main_layout.addWidget(self.label_2, 9, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_Cs260StartWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_Cs260StartWavelength.setObjectName("lineedit_list_SavedSequences_passive_Cs260StartWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_Cs260StartWavelength, 2, 1, 1, 1)
        self.sequence_monochromator_shutter_label = QtWidgets.QLabel(Form)
        self.sequence_monochromator_shutter_label.setObjectName("sequence_monochromator_shutter_label")
        self.main_layout.addWidget(self.sequence_monochromator_shutter_label, 5, 0, 1, 1)
        self.sequence_monochromator_stepsize_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_stepsize_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_stepsize_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_stepsize_label.setObjectName("sequence_monochromator_stepsize_label")
        self.main_layout.addWidget(self.sequence_monochromator_stepsize_label, 4, 0, 1, 1)
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating = QtWidgets.QComboBox(Form)
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.setObjectName("combobox_list_Cs260GratingTransitions_ItemDisplay_grating")
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.addItem("")
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.addItem("")
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.addItem("")
        self.main_layout.addWidget(self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating, 9, 1, 1, 1)
        self.sequence_monochromator_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sequence_monochromator_label.setFont(font)
        self.sequence_monochromator_label.setObjectName("sequence_monochromator_label")
        self.main_layout.addWidget(self.sequence_monochromator_label, 0, 0, 1, 1)
        self.sequence_monochromator_startwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_startwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_startwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_startwave_label.setObjectName("sequence_monochromator_startwave_label")
        self.main_layout.addWidget(self.sequence_monochromator_startwave_label, 2, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_Cs260EndWavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_Cs260EndWavelength.setObjectName("lineedit_list_SavedSequences_passive_Cs260EndWavelength")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_Cs260EndWavelength, 3, 1, 1, 1)
        self.combobox_list_SavedSequences_passive_Cs260Shutter = QtWidgets.QComboBox(Form)
        self.combobox_list_SavedSequences_passive_Cs260Shutter.setObjectName("combobox_list_SavedSequences_passive_Cs260Shutter")
        self.combobox_list_SavedSequences_passive_Cs260Shutter.addItem("")
        self.combobox_list_SavedSequences_passive_Cs260Shutter.addItem("")
        self.main_layout.addWidget(self.combobox_list_SavedSequences_passive_Cs260Shutter, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 1, 0, 1, 2)
        self.sequence_monochromator_endwave_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_endwave_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_endwave_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_endwave_label.setObjectName("sequence_monochromator_endwave_label")
        self.main_layout.addWidget(self.sequence_monochromator_endwave_label, 3, 0, 1, 1)
        self.lineedit_list_SavedSequences_passive_Cs260StepSize = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_passive_Cs260StepSize.setObjectName("lineedit_list_SavedSequences_passive_Cs260StepSize")
        self.main_layout.addWidget(self.lineedit_list_SavedSequences_passive_Cs260StepSize, 4, 1, 1, 1)
        self.button_list_Cs260OsfTransitions_setter_AddCs260OsfTransition = QtWidgets.QPushButton(Form)
        self.button_list_Cs260OsfTransitions_setter_AddCs260OsfTransition.setObjectName("button_list_Cs260OsfTransitions_setter_AddCs260OsfTransition")
        self.main_layout.addWidget(self.button_list_Cs260OsfTransitions_setter_AddCs260OsfTransition, 17, 0, 1, 2)
        self.list_listXlist_Cs260GratingTransitionsXSavedSequences_listXPassiveListAll_Cs260GratingTransitions = QtWidgets.QListWidget(Form)
        self.list_listXlist_Cs260GratingTransitionsXSavedSequences_listXPassiveListAll_Cs260GratingTransitions.setObjectName("list_listXlist_Cs260GratingTransitionsXSavedSequences_listXPassiveListAll_Cs260GratingTransitions")
        self.main_layout.addWidget(self.list_listXlist_Cs260GratingTransitionsXSavedSequences_listXPassiveListAll_Cs260GratingTransitions, 7, 0, 1, 2)
        self.sequence_monochromator_gratingtransition_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_gratingtransition_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_gratingtransition_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_gratingtransition_label.setObjectName("sequence_monochromator_gratingtransition_label")
        self.main_layout.addWidget(self.sequence_monochromator_gratingtransition_label, 6, 0, 1, 1)
        self.sequence_monochromator_osf2osf3_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_monochromator_osf2osf3_label.sizePolicy().hasHeightForWidth())
        self.sequence_monochromator_osf2osf3_label.setSizePolicy(sizePolicy)
        self.sequence_monochromator_osf2osf3_label.setObjectName("sequence_monochromator_osf2osf3_label")
        self.main_layout.addWidget(self.sequence_monochromator_osf2osf3_label, 13, 0, 1, 1)
        self.button_list_Cs260OsfTransitions_remover_RemoveCs260OsfTransition = QtWidgets.QPushButton(Form)
        self.button_list_Cs260OsfTransitions_remover_RemoveCs260OsfTransition.setObjectName("button_list_Cs260OsfTransitions_remover_RemoveCs260OsfTransition")
        self.main_layout.addWidget(self.button_list_Cs260OsfTransitions_remover_RemoveCs260OsfTransition, 18, 0, 1, 2)
        self.button_list_Cs260GratingTransitions_remover_RemoveCs260GratingTransition = QtWidgets.QPushButton(Form)
        self.button_list_Cs260GratingTransitions_remover_RemoveCs260GratingTransition.setObjectName("button_list_Cs260GratingTransitions_remover_RemoveCs260GratingTransition")
        self.main_layout.addWidget(self.button_list_Cs260GratingTransitions_remover_RemoveCs260GratingTransition, 11, 0, 1, 2)
        self.list_listXlist_Cs260OsfTransitionsXSavedSequences_listXPassiveListAll_Cs260OsfTransitions = QtWidgets.QListWidget(Form)
        self.list_listXlist_Cs260OsfTransitionsXSavedSequences_listXPassiveListAll_Cs260OsfTransitions.setObjectName("list_listXlist_Cs260OsfTransitionsXSavedSequences_listXPassiveListAll_Cs260OsfTransitions")
        self.main_layout.addWidget(self.list_listXlist_Cs260OsfTransitionsXSavedSequences_listXPassiveListAll_Cs260OsfTransitions, 14, 0, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 8, 0, 1, 1)
        self.lineedit_list_Cs260GratingTransitions_ItemDisplay_wavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_Cs260GratingTransitions_ItemDisplay_wavelength.setObjectName("lineedit_list_Cs260GratingTransitions_ItemDisplay_wavelength")
        self.main_layout.addWidget(self.lineedit_list_Cs260GratingTransitions_ItemDisplay_wavelength, 8, 1, 1, 1)
        self.button_list_Cs260GratingTransitions_RemoverOfAll_RemoveAllCs260Transitions = QtWidgets.QPushButton(Form)
        self.button_list_Cs260GratingTransitions_RemoverOfAll_RemoveAllCs260Transitions.setObjectName("button_list_Cs260GratingTransitions_RemoverOfAll_RemoveAllCs260Transitions")
        self.main_layout.addWidget(self.button_list_Cs260GratingTransitions_RemoverOfAll_RemoveAllCs260Transitions, 12, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.main_layout.addWidget(self.label_3, 15, 0, 1, 1)
        self.button_list_Cs260GratingTransitions_setter_AddCs260GratingTransition = QtWidgets.QPushButton(Form)
        self.button_list_Cs260GratingTransitions_setter_AddCs260GratingTransition.setObjectName("button_list_Cs260GratingTransitions_setter_AddCs260GratingTransition")
        self.main_layout.addWidget(self.button_list_Cs260GratingTransitions_setter_AddCs260GratingTransition, 10, 0, 1, 2)
        self.button_list_Cs260OsfTransitions_RemoverOfAll_RemoveAllCs260Transitions = QtWidgets.QPushButton(Form)
        self.button_list_Cs260OsfTransitions_RemoverOfAll_RemoveAllCs260Transitions.setObjectName("button_list_Cs260OsfTransitions_RemoverOfAll_RemoveAllCs260Transitions")
        self.main_layout.addWidget(self.button_list_Cs260OsfTransitions_RemoverOfAll_RemoveAllCs260Transitions, 19, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.main_layout.addWidget(self.label_4, 16, 0, 1, 1)
        self.lineedit_list_Cs260OsfTransitions_ItemDisplay_wavelength = QtWidgets.QLineEdit(Form)
        self.lineedit_list_Cs260OsfTransitions_ItemDisplay_wavelength.setObjectName("lineedit_list_Cs260OsfTransitions_ItemDisplay_wavelength")
        self.main_layout.addWidget(self.lineedit_list_Cs260OsfTransitions_ItemDisplay_wavelength, 15, 1, 1, 1)
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf = QtWidgets.QComboBox(Form)
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setObjectName("combobox_list_Cs260OsfTransitions_ItemDisplay_osf")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.addItem("")
        self.main_layout.addWidget(self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf, 16, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monochromator"))
        self.label_2.setText(_translate("Form", "Grating:"))
        self.sequence_monochromator_shutter_label.setText(_translate("Form", "Shutter"))
        self.sequence_monochromator_stepsize_label.setText(_translate("Form", "Step Size (um.): "))
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.setItemText(0, _translate("Form", "1"))
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.setItemText(1, _translate("Form", "2"))
        self.combobox_list_Cs260GratingTransitions_ItemDisplay_grating.setItemText(2, _translate("Form", "3"))
        self.sequence_monochromator_label.setText(_translate("Form", "Monochromator Sequence Control:"))
        self.sequence_monochromator_startwave_label.setText(_translate("Form", "Start Wavelength (um.):"))
        self.combobox_list_SavedSequences_passive_Cs260Shutter.setItemText(0, _translate("Form", "Open"))
        self.combobox_list_SavedSequences_passive_Cs260Shutter.setItemText(1, _translate("Form", "Closed"))
        self.sequence_monochromator_endwave_label.setText(_translate("Form", "End Wavelength (um.): "))
        self.button_list_Cs260OsfTransitions_setter_AddCs260OsfTransition.setText(_translate("Form", "Add Osf Transition"))
        self.sequence_monochromator_gratingtransition_label.setText(_translate("Form", "Grating Transitions:"))
        self.sequence_monochromator_osf2osf3_label.setText(_translate("Form", "Order Sort Filter Wheel Transitions:"))
        self.button_list_Cs260OsfTransitions_remover_RemoveCs260OsfTransition.setText(_translate("Form", "Remove Osf Transition"))
        self.button_list_Cs260GratingTransitions_remover_RemoveCs260GratingTransition.setText(_translate("Form", "Remove Grating Transition"))
        self.label.setText(_translate("Form", "Wavelength (um.):"))
        self.button_list_Cs260GratingTransitions_RemoverOfAll_RemoveAllCs260Transitions.setText(_translate("Form", "Remove All Grating Transitions"))
        self.label_3.setText(_translate("Form", "Wavelength (um.):"))
        self.button_list_Cs260GratingTransitions_setter_AddCs260GratingTransition.setText(_translate("Form", "Add Grating Transition"))
        self.button_list_Cs260OsfTransitions_RemoverOfAll_RemoveAllCs260Transitions.setText(_translate("Form", "Remove All Osf Transitions"))
        self.label_4.setText(_translate("Form", "Osf Wheel Position"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(0, _translate("Form", "1"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(1, _translate("Form", "2"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(2, _translate("Form", "3"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(3, _translate("Form", "4"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(4, _translate("Form", "5"))
        self.combobox_list_Cs260OsfTransitions_ItemDisplay_osf.setItemText(5, _translate("Form", "6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

