# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'top.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TopQt(object):
    def setupUi(self, Form):
        Form.setObjectName("SPHERExLabTools")
        Form.resize(1039, 757)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.top_horizontal_widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_horizontal_widget.sizePolicy().hasHeightForWidth())
        self.top_horizontal_widget.setSizePolicy(sizePolicy)
        self.top_horizontal_widget.setObjectName("top_horizontal_widget")
        self.top_horizontal_layout = QtWidgets.QHBoxLayout(self.top_horizontal_widget)
        self.top_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.top_horizontal_layout.setObjectName("top_horizontal_layout")
        self.top_horizontal_splitter = QtWidgets.QSplitter()
        self.top_horizontal_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.top_horizontal_splitter.setObjectName('top_horizontal_splitter')
        self.top_horizontal_layout.addWidget(self.top_horizontal_splitter)
        self.Tab_log_threads = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_log_threads.sizePolicy().hasHeightForWidth())
        self.Tab_log_threads.setSizePolicy(sizePolicy)
        self.Tab_log_threads.setObjectName("Tab_log_threads")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.log_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logBrowser = QtWidgets.QTextBrowser(self.log_tab)
        self.logBrowser.setObjectName("logBrowser")
        self.gridLayout_3.addWidget(self.logBrowser, 0, 0, 1, 1)
        self.Tab_log_threads.addTab(self.log_tab, "")
        self.threads_tab = QtWidgets.QWidget()
        self.threads_tab.setObjectName("threads_tab")
        self.Tab_log_threads.addTab(self.threads_tab, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter.setSizes([800, 200])

        self.retranslateUi(Form)
        self.Tab_log_threads.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("SPHERExLabTools", "SPHERExLabTools"))
        self.logBrowser.setHtml(_translate("SPHERExLabTools", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#00007f;\"># ---------------- SPHERExLabTools v0.8------------------- #</span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                                     .....                                     </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                                              ........                          </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                      /                              </span><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#ffff00;\">..</span><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                         </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                  /////                                       (                 </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">               ///                                               (              </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">            ///           #################                        ((           </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">          //            #### ############### ####                    ((         </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">         /             ###################### ### ###                 ((        </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">       /               ############################## ###              (((      </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">      /                 ### ### ##################### ## ##             (((     </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                         ###(##%&amp;######################*## ##,           (((    </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                         &amp;##&amp;&amp; #&amp;&amp;&amp;### //////##################           ((    </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">      #                  /&amp;&amp;(&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp; ////*############# ######                </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">   ###                  //%&amp;&amp;&amp;%&amp;&amp;&amp;&amp;&amp; &amp;&amp;&amp;&amp;&amp;&amp; ############ ########               </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">   ###                 ////&amp;&amp;&amp;&amp;&amp;&amp;&amp;/&amp;&amp;&amp;&amp;&amp;&amp;,&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;###### ####                </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">   ##                    .//&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp; &amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;   &amp;&amp;########              #  </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">   ##                       /&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;  &amp;&amp;&amp;########                   #  </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">   ##                       *&amp; &amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;                         #  </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">    #                     &amp;&amp;////&amp;&amp;%&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;&amp;//////                        #   </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">    ##                     &amp;///&amp;&amp;&amp;&amp;//&amp;&amp;&amp;&amp;&amp;////////////                     ##   </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">     #                    &amp;&amp;&amp;&amp;&amp;&amp;(&amp;////&amp;&amp;&amp;///////////////                  ##    </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">      #                     &amp;&amp;&amp;&amp;&amp; &amp;&amp;&amp;&amp;&amp;&amp; /////////////                  ###     </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">       #                         &amp;&amp;*        /////////                  ###      </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                                              //////                 ###        </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                                                 /                                      </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                           ##                                                   </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                            #######                  #                          </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,BitstreamVeraSansMono,CourierNew,Courier,monospace\'; font-size:6pt; color:#000000;\">                                      #####  </span></p>\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#00007f;\"># -------------------------------------------------------------------- #</span></p></body></html>"))
        self.Tab_log_threads.setTabText(self.Tab_log_threads.indexOf(self.log_tab), _translate("SPHERExLabTools", "Log"))
        self.Tab_log_threads.setTabText(self.Tab_log_threads.indexOf(self.threads_tab), _translate("SPHERExLabTools", "Threads"))


# - top ui wrapper - #
class TopUI(TopQt, QtCore.QObject):

    ui_log_signal = QtCore.pyqtSignal(object, name="UI Log Signal")

    def __init__(self, top_widget):
        super().__init__()
        self.setupUi(top_widget)
        self.ver_scrollbar = self.logBrowser.verticalScrollBar()
        self.hor_scrollbar = self.logBrowser.horizontalScrollBar()
        self.ui_log_signal.connect(self.log)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.logBrowser.setFont(font)

    def log(self, msg):
        """ This method allows logging of formatted log messaged created by the logging package to the log
        interface.

        :param msg: String message to write to the log window.
        """
        self.logBrowser.append(msg)
        scroll = self.ver_scrollbar.maximum() - self.ver_scrollbar.value() <= 10
        if scroll:
            self.ver_scrollbar.setValue(self.ver_scrollbar.maximum())
            self.hor_scrollbar.setValue(0)


