# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_with_Tabs.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Series = QtWidgets.QWidget()
        self.Series.setObjectName("Series")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Series)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_7.addWidget(self.progressBar)
        self.label_2 = QtWidgets.QLabel(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.progressBar_2 = QtWidgets.QProgressBar(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_7.addWidget(self.progressBar_2)
        self.add_new_sequence_button_2 = QtWidgets.QPushButton(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_new_sequence_button_2.sizePolicy().hasHeightForWidth())
        self.add_new_sequence_button_2.setSizePolicy(sizePolicy)
        self.add_new_sequence_button_2.setObjectName("add_new_sequence_button_2")
        self.verticalLayout_7.addWidget(self.add_new_sequence_button_2)
        self.remove_sequence_button_2 = QtWidgets.QPushButton(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_sequence_button_2.sizePolicy().hasHeightForWidth())
        self.remove_sequence_button_2.setSizePolicy(sizePolicy)
        self.remove_sequence_button_2.setObjectName("remove_sequence_button_2")
        self.verticalLayout_7.addWidget(self.remove_sequence_button_2)
        self.label_3 = QtWidgets.QLabel(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.listWidget_2 = QtWidgets.QListWidget(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_7.addWidget(self.listWidget_2)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalScrollBar.sizePolicy().hasHeightForWidth())
        self.verticalScrollBar.setSizePolicy(sizePolicy)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_3.addWidget(self.verticalScrollBar, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.Series)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.gridLayout_4.addWidget(self.verticalScrollBar_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 2)
        self.listWidget_5 = QtWidgets.QListWidget(self.Series)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_5.sizePolicy().hasHeightForWidth())
        self.listWidget_5.setSizePolicy(sizePolicy)
        self.listWidget_5.setObjectName("listWidget_5")
        self.gridLayout_4.addWidget(self.listWidget_5, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.tabWidget.addTab(self.Series, "")
        self.Single = QtWidgets.QWidget()
        self.Single.setObjectName("Single")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Single)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 1, 1, 1)
        self.grating_select_cbox = QtWidgets.QComboBox(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grating_select_cbox.sizePolicy().hasHeightForWidth())
        self.grating_select_cbox.setSizePolicy(sizePolicy)
        self.grating_select_cbox.setObjectName("grating_select_cbox")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.grating_select_cbox.addItem("")
        self.gridLayout_5.addWidget(self.grating_select_cbox, 1, 0, 1, 1)
        self.osf_select_cbox_2 = QtWidgets.QComboBox(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.osf_select_cbox_2.sizePolicy().hasHeightForWidth())
        self.osf_select_cbox_2.setSizePolicy(sizePolicy)
        self.osf_select_cbox_2.setObjectName("osf_select_cbox_2")
        self.osf_select_cbox_2.addItem("")
        self.osf_select_cbox_2.addItem("")
        self.gridLayout_5.addWidget(self.osf_select_cbox_2, 5, 0, 1, 1)
        self.sequence_measure_int_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_measure_int_label.sizePolicy().hasHeightForWidth())
        self.sequence_measure_int_label.setSizePolicy(sizePolicy)
        self.sequence_measure_int_label.setObjectName("sequence_measure_int_label")
        self.gridLayout_5.addWidget(self.sequence_measure_int_label, 12, 0, 1, 1)
        self.listWidget_6 = QtWidgets.QListWidget(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_6.sizePolicy().hasHeightForWidth())
        self.listWidget_6.setSizePolicy(sizePolicy)
        self.listWidget_6.setObjectName("listWidget_6")
        self.gridLayout_5.addWidget(self.listWidget_6, 1, 2, 13, 1)
        self.label_7 = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 2, 1, 2)
        self.remove_sequence_button_3 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_sequence_button_3.sizePolicy().hasHeightForWidth())
        self.remove_sequence_button_3.setSizePolicy(sizePolicy)
        self.remove_sequence_button_3.setObjectName("remove_sequence_button_3")
        self.gridLayout_5.addWidget(self.remove_sequence_button_3, 4, 1, 1, 1)
        self.sequence_wave_start_ledit = QtWidgets.QLineEdit(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_start_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_start_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_start_ledit.setPlaceholderText("")
        self.sequence_wave_start_ledit.setObjectName("sequence_wave_start_ledit")
        self.gridLayout_5.addWidget(self.sequence_wave_start_ledit, 7, 0, 1, 1)
        self.add_new_sequence_button_3 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_new_sequence_button_3.sizePolicy().hasHeightForWidth())
        self.add_new_sequence_button_3.setSizePolicy(sizePolicy)
        self.add_new_sequence_button_3.setObjectName("add_new_sequence_button_3")
        self.gridLayout_5.addWidget(self.add_new_sequence_button_3, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.sequence_measure_int_ledit = QtWidgets.QLineEdit(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_measure_int_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_measure_int_ledit.setSizePolicy(sizePolicy)
        self.sequence_measure_int_ledit.setPlaceholderText("")
        self.sequence_measure_int_ledit.setObjectName("sequence_measure_int_ledit")
        self.gridLayout_5.addWidget(self.sequence_measure_int_ledit, 13, 0, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_5.addWidget(self.listWidget_3, 6, 1, 8, 1)
        self.sequence_name_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_label.sizePolicy().hasHeightForWidth())
        self.sequence_name_label.setSizePolicy(sizePolicy)
        self.sequence_name_label.setObjectName("sequence_name_label")
        self.gridLayout_5.addWidget(self.sequence_name_label, 0, 1, 1, 1)
        self.sequence_wave_step_ledit = QtWidgets.QLineEdit(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_step_ledit.setObjectName("sequence_wave_step_ledit")
        self.gridLayout_5.addWidget(self.sequence_wave_step_ledit, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalScrollBar_3.sizePolicy().hasHeightForWidth())
        self.verticalScrollBar_3.setSizePolicy(sizePolicy)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.gridLayout_5.addWidget(self.verticalScrollBar_3, 1, 3, 13, 1)
        self.osf_select_label_2 = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.osf_select_label_2.sizePolicy().hasHeightForWidth())
        self.osf_select_label_2.setSizePolicy(sizePolicy)
        self.osf_select_label_2.setObjectName("osf_select_label_2")
        self.gridLayout_5.addWidget(self.osf_select_label_2, 4, 0, 1, 1)
        self.sequence_end_wave_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_end_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_end_wave_label.setSizePolicy(sizePolicy)
        self.sequence_end_wave_label.setObjectName("sequence_end_wave_label")
        self.gridLayout_5.addWidget(self.sequence_end_wave_label, 8, 0, 1, 1)
        self.osf_select_cbox = QtWidgets.QComboBox(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.osf_select_cbox.sizePolicy().hasHeightForWidth())
        self.osf_select_cbox.setSizePolicy(sizePolicy)
        self.osf_select_cbox.setObjectName("osf_select_cbox")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.osf_select_cbox.addItem("")
        self.gridLayout_5.addWidget(self.osf_select_cbox, 3, 0, 1, 1)
        self.sequence_start_wave_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_start_wave_label.sizePolicy().hasHeightForWidth())
        self.sequence_start_wave_label.setSizePolicy(sizePolicy)
        self.sequence_start_wave_label.setObjectName("sequence_start_wave_label")
        self.gridLayout_5.addWidget(self.sequence_start_wave_label, 6, 0, 1, 1)
        self.sequence_wave_end_ledit = QtWidgets.QLineEdit(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_end_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_wave_end_ledit.setSizePolicy(sizePolicy)
        self.sequence_wave_end_ledit.setPlaceholderText("")
        self.sequence_wave_end_ledit.setObjectName("sequence_wave_end_ledit")
        self.gridLayout_5.addWidget(self.sequence_wave_end_ledit, 9, 0, 1, 1)
        self.sequence_name_ledit = QtWidgets.QLineEdit(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_ledit.sizePolicy().hasHeightForWidth())
        self.sequence_name_ledit.setSizePolicy(sizePolicy)
        self.sequence_name_ledit.setPlaceholderText("")
        self.sequence_name_ledit.setObjectName("sequence_name_ledit")
        self.gridLayout_5.addWidget(self.sequence_name_ledit, 1, 1, 1, 1)
        self.sequence_wave_step_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_wave_step_label.sizePolicy().hasHeightForWidth())
        self.sequence_wave_step_label.setSizePolicy(sizePolicy)
        self.sequence_wave_step_label.setObjectName("sequence_wave_step_label")
        self.gridLayout_5.addWidget(self.sequence_wave_step_label, 10, 0, 1, 1)
        self.osf_select_label = QtWidgets.QLabel(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.osf_select_label.sizePolicy().hasHeightForWidth())
        self.osf_select_label.setSizePolicy(sizePolicy)
        self.osf_select_label.setObjectName("osf_select_label")
        self.gridLayout_5.addWidget(self.osf_select_label, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 14, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 14, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.Single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 14, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Single, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.gridLayout = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_10 = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 5, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 5, 2, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_8.addWidget(self.listWidget_4, 9, 1, 5, 2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_8.addWidget(self.checkBox_10, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 2, 1, 1, 2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_8.addWidget(self.checkBox_4, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_8.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.listWidget_8 = QtWidgets.QListWidget(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_8.sizePolicy().hasHeightForWidth())
        self.listWidget_8.setSizePolicy(sizePolicy)
        self.listWidget_8.setObjectName("listWidget_8")
        self.gridLayout_8.addWidget(self.listWidget_8, 1, 3, 13, 1)
        self.sequence_name_ledit_3 = QtWidgets.QLineEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_ledit_3.sizePolicy().hasHeightForWidth())
        self.sequence_name_ledit_3.setSizePolicy(sizePolicy)
        self.sequence_name_ledit_3.setPlaceholderText("")
        self.sequence_name_ledit_3.setObjectName("sequence_name_ledit_3")
        self.gridLayout_8.addWidget(self.sequence_name_ledit_3, 3, 1, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 4, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_8.addWidget(self.checkBox, 2, 0, 1, 1)
        self.sequence_name_ledit_2 = QtWidgets.QLineEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_ledit_2.sizePolicy().hasHeightForWidth())
        self.sequence_name_ledit_2.setSizePolicy(sizePolicy)
        self.sequence_name_ledit_2.setPlaceholderText("")
        self.sequence_name_ledit_2.setObjectName("sequence_name_ledit_2")
        self.gridLayout_8.addWidget(self.sequence_name_ledit_2, 1, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 4, 1, 1, 1)
        self.verticalScrollBar_5 = QtWidgets.QScrollBar(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalScrollBar_5.sizePolicy().hasHeightForWidth())
        self.verticalScrollBar_5.setSizePolicy(sizePolicy)
        self.verticalScrollBar_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_5.setObjectName("verticalScrollBar_5")
        self.gridLayout_8.addWidget(self.verticalScrollBar_5, 1, 4, 13, 1)
        self.label_16 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 8, 1, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_8.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 3, 1, 2)
        self.remove_sequence_button_4 = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_sequence_button_4.sizePolicy().hasHeightForWidth())
        self.remove_sequence_button_4.setSizePolicy(sizePolicy)
        self.remove_sequence_button_4.setObjectName("remove_sequence_button_4")
        self.gridLayout_8.addWidget(self.remove_sequence_button_4, 7, 1, 1, 2)
        self.add_new_sequence_button_4 = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_new_sequence_button_4.sizePolicy().hasHeightForWidth())
        self.add_new_sequence_button_4.setSizePolicy(sizePolicy)
        self.add_new_sequence_button_4.setObjectName("add_new_sequence_button_4")
        self.gridLayout_8.addWidget(self.add_new_sequence_button_4, 6, 1, 1, 2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_8.addWidget(self.checkBox_5, 6, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_8.addWidget(self.checkBox_6, 7, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_8.addWidget(self.checkBox_7, 8, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_8.addWidget(self.checkBox_8, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 10, 0, 1, 1)
        self.sequence_name_ledit_4 = QtWidgets.QLineEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_name_ledit_4.sizePolicy().hasHeightForWidth())
        self.sequence_name_ledit_4.setSizePolicy(sizePolicy)
        self.sequence_name_ledit_4.setPlaceholderText("")
        self.sequence_name_ledit_4.setObjectName("sequence_name_ledit_4")
        self.gridLayout_8.addWidget(self.sequence_name_ledit_4, 11, 0, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 0, 0, 1, 3)
        self.tabWidget.addTab(self.Settings, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.grating_select_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Current Sequence Progress:"))
        self.label_2.setText(_translate("MainWindow", "Scan Sequence Series Progress:"))
        self.add_new_sequence_button_2.setText(_translate("MainWindow", "Add New Sequence To Scan Series"))
        self.remove_sequence_button_2.setText(_translate("MainWindow", "Remove Sequence From Scan Series"))
        self.label_3.setText(_translate("MainWindow", "Scan Sequence Series Config Files:"))
        self.label_4.setText(_translate("MainWindow", "Saved Sequence Config Files:"))
        self.pushButton.setText(_translate("MainWindow", "Run Single Sequence"))
        self.pushButton_2.setText(_translate("MainWindow", "Run Series"))
        self.pushButton_3.setText(_translate("MainWindow", "Abort Scan"))
        self.label_5.setText(_translate("MainWindow", "Status Log:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Series), _translate("MainWindow", "Tab 1"))
        self.label_8.setText(_translate("MainWindow", "Scan Sequence Series"))
        self.grating_select_cbox.setItemText(0, _translate("MainWindow", "Grating 1 (G1)"))
        self.grating_select_cbox.setItemText(1, _translate("MainWindow", "Grating 2 (G2)"))
        self.grating_select_cbox.setItemText(2, _translate("MainWindow", "Grating 3 (G3)"))
        self.osf_select_cbox_2.setItemText(0, _translate("MainWindow", "Open"))
        self.osf_select_cbox_2.setItemText(1, _translate("MainWindow", "Closed"))
        self.sequence_measure_int_label.setText(_translate("MainWindow", "Sequence Measurement Interval (s):"))
        self.label_7.setText(_translate("MainWindow", "Status Log"))
        self.remove_sequence_button_3.setText(_translate("MainWindow", "Remove Sequence From Scan Series"))
        self.sequence_wave_start_ledit.setText(_translate("MainWindow", "0.75"))
        self.add_new_sequence_button_3.setText(_translate("MainWindow", "Add New Sequence To Scan Series"))
        self.pushButton_4.setText(_translate("MainWindow", "Save Sequence Config File"))
        self.sequence_measure_int_ledit.setText(_translate("MainWindow", "5.0"))
        self.sequence_name_label.setText(_translate("MainWindow", "Sequence Config File Name:"))
        self.sequence_wave_step_ledit.setText(_translate("MainWindow", "1.0"))
        self.sequence_wave_step_ledit.setPlaceholderText(_translate("MainWindow", "1.0"))
        self.label_6.setText(_translate("MainWindow", " Grating Selection:"))
        self.osf_select_label_2.setText(_translate("MainWindow", "Shutter"))
        self.sequence_end_wave_label.setText(_translate("MainWindow", "Sequence End Wavelength (um.):"))
        self.osf_select_cbox.setItemText(0, _translate("MainWindow", "OSF1"))
        self.osf_select_cbox.setItemText(1, _translate("MainWindow", "OSF2"))
        self.osf_select_cbox.setItemText(2, _translate("MainWindow", "OSF3"))
        self.osf_select_cbox.setItemText(3, _translate("MainWindow", "OSF4"))
        self.sequence_start_wave_label.setText(_translate("MainWindow", "Sequence Start Wavelength (um.):"))
        self.sequence_wave_end_ledit.setText(_translate("MainWindow", "5.0"))
        self.sequence_name_ledit.setText(_translate("MainWindow", "Seq1"))
        self.sequence_wave_step_label.setText(_translate("MainWindow", "Sequence Wavelength Step (nm.):"))
        self.osf_select_label.setText(_translate("MainWindow", "Filter Selection:"))
        self.pushButton_5.setText(_translate("MainWindow", "Run Single Sequence"))
        self.pushButton_7.setText(_translate("MainWindow", "Run Series"))
        self.pushButton_6.setText(_translate("MainWindow", "Abort Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Single), _translate("MainWindow", "Tab 2"))
        self.pushButton_10.setText(_translate("MainWindow", "Run Series"))
        self.pushButton_8.setText(_translate("MainWindow", "Run Single Sequence"))
        self.pushButton_9.setText(_translate("MainWindow", "Abort Scan"))
        self.label_11.setText(_translate("MainWindow", "Storage Path:"))
        self.label_14.setText(_translate("MainWindow", "Compression:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", ".zip"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", ".tgz"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", ".tar"))
        self.checkBox_10.setText(_translate("MainWindow", "Overwrite Without Warning"))
        self.label_12.setText(_translate("MainWindow", "Filename Suffix:"))
        self.checkBox_4.setText(_translate("MainWindow", "Filter_Wheel_2"))
        self.label_9.setText(_translate("MainWindow", "Metadata to Include:"))
        self.checkBox_3.setText(_translate("MainWindow", "Filter_Wheel_1"))
        self.sequence_name_ledit_3.setText(_translate("MainWindow", "_30042021_1701"))
        self.comboBox.setItemText(0, _translate("MainWindow", ".csv"))
        self.comboBox.setItemText(1, _translate("MainWindow", ".json"))
        self.comboBox.setItemText(2, _translate("MainWindow", ".parquet"))
        self.checkBox.setText(_translate("MainWindow", "Cryo_Temperature"))
        self.sequence_name_ledit_2.setText(_translate("MainWindow", "/data/big_data/"))
        self.label_13.setText(_translate("MainWindow", "Data Format:"))
        self.label_16.setText(_translate("MainWindow", "Scan Sequence Series"))
        self.checkBox_2.setText(_translate("MainWindow", "Power_Meter"))
        self.label_17.setText(_translate("MainWindow", "Status Log:"))
        self.remove_sequence_button_4.setText(_translate("MainWindow", "Remove Sequence From Scan Series"))
        self.add_new_sequence_button_4.setText(_translate("MainWindow", "Add New Sequence To Scan Series"))
        self.checkBox_5.setText(_translate("MainWindow", "Grating"))
        self.checkBox_6.setText(_translate("MainWindow", "Wavelength"))
        self.checkBox_7.setText(_translate("MainWindow", "Measurement_Interval"))
        self.checkBox_8.setText(_translate("MainWindow", "Alt1"))
        self.label_10.setText(_translate("MainWindow", "Search Keywords:"))
        self.sequence_name_ledit_4.setText(_translate("MainWindow", "Test, Development"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
