# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seriesconstructionWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 662)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 0, 1, 1)
        self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence = QtWidgets.QListWidget(Form)
        self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence.setObjectName("list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence")
        self.gridLayout_13.addWidget(self.list_listXlist_SavedSequencesXSeries_ItemSelectorListXpassive_Sequence, 4, 0, 1, 1)
        self.button_list_SavedSequences_setter_SaveNewSequenceButton = QtWidgets.QPushButton(Form)
        self.button_list_SavedSequences_setter_SaveNewSequenceButton.setObjectName("button_list_SavedSequences_setter_SaveNewSequenceButton")
        self.gridLayout_13.addWidget(self.button_list_SavedSequences_setter_SaveNewSequenceButton, 2, 0, 1, 1)
        self.lineedit_list_SavedSequences_ItemDisplay_SequenceName = QtWidgets.QLineEdit(Form)
        self.lineedit_list_SavedSequences_ItemDisplay_SequenceName.setObjectName("lineedit_list_SavedSequences_ItemDisplay_SequenceName")
        self.gridLayout_13.addWidget(self.lineedit_list_SavedSequences_ItemDisplay_SequenceName, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 3, 0, 1, 1)
        self.button_list_Series_setter_AddSequenceToSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_setter_AddSequenceToSeriesButton.setObjectName("button_list_Series_setter_AddSequenceToSeriesButton")
        self.gridLayout_13.addWidget(self.button_list_Series_setter_AddSequenceToSeriesButton, 5, 0, 1, 1)
        self.main_layout.addLayout(self.gridLayout_13, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.main_layout.addWidget(self.label_5, 3, 0, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton.setObjectName("button_list_Series_remover_RemoveSequenceFromSeriesButton")
        self.gridLayout_15.addWidget(self.button_list_Series_remover_RemoveSequenceFromSeriesButton, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.list_list_Series_ItemSelectorList_SeriesList = QtWidgets.QListWidget(Form)
        self.list_list_Series_ItemSelectorList_SeriesList.setObjectName("list_list_Series_ItemSelectorList_SeriesList")
        self.gridLayout_15.addWidget(self.list_list_Series_ItemSelectorList_SeriesList, 1, 0, 1, 1)
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton.setObjectName("button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton")
        self.gridLayout_15.addWidget(self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton, 3, 0, 1, 1)
        self.main_layout.addLayout(self.gridLayout_15, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.main_layout.addWidget(self.line_2, 4, 0, 1, 2)
        self.AbortSeriesButton = QtWidgets.QPushButton(Form)
        self.AbortSeriesButton.setObjectName("AbortSeriesButton")
        self.main_layout.addWidget(self.AbortSeriesButton, 10, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.main_layout.addWidget(self.line_3, 7, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.main_layout.addWidget(self.label_9, 6, 0, 1, 2)
        self.PauseSeriesButton = QtWidgets.QPushButton(Form)
        self.PauseSeriesButton.setObjectName("PauseSeriesButton")
        self.main_layout.addWidget(self.PauseSeriesButton, 9, 0, 1, 2)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 0, 1, 1, 2)
        self.checkbox_list_SavedSequences_passive_MeasureSr510 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MeasureSr510.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MeasureSr510.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MeasureSr510.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MeasureSr510.setObjectName("checkbox_list_SavedSequences_passive_MeasureSr510")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MeasureSr510, 1, 1, 2, 1)
        self.checkbox_list_SavedSequences_passive_MeasureSr830 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_list_SavedSequences_passive_MeasureSr830.sizePolicy().hasHeightForWidth())
        self.checkbox_list_SavedSequences_passive_MeasureSr830.setSizePolicy(sizePolicy)
        self.checkbox_list_SavedSequences_passive_MeasureSr830.setChecked(True)
        self.checkbox_list_SavedSequences_passive_MeasureSr830.setObjectName("checkbox_list_SavedSequences_passive_MeasureSr830")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MeasureSr830, 1, 2, 2, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 8, 1, 1, 1)
        self.ledit_list_SavedSequences_passive_MeasureSampleTime = QtWidgets.QLineEdit(Form)
        self.ledit_list_SavedSequences_passive_MeasureSampleTime.setObjectName("ledit_list_SavedSequences_passive_MeasureSampleTime")
        self.gridLayout_16.addWidget(self.ledit_list_SavedSequences_passive_MeasureSampleTime, 8, 2, 1, 1)
        self.ledit_list_SavedSequences_passive_MeasureStoragePath = QtWidgets.QLineEdit(Form)
        self.ledit_list_SavedSequences_passive_MeasureStoragePath.setObjectName("ledit_list_SavedSequences_passive_MeasureStoragePath")
        self.gridLayout_16.addWidget(self.ledit_list_SavedSequences_passive_MeasureStoragePath, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 5, 1, 1, 1)
        self.checkbox_list_SavedSequences_passive_MeasureS122vc = QtWidgets.QCheckBox(Form)
        self.checkbox_list_SavedSequences_passive_MeasureS122vc.setObjectName("checkbox_list_SavedSequences_passive_MeasureS122vc")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MeasureS122vc, 3, 2, 1, 1)
        self.checkbox_list_SavedSequences_passive_MeasureS122c = QtWidgets.QCheckBox(Form)
        self.checkbox_list_SavedSequences_passive_MeasureS122c.setObjectName("checkbox_list_SavedSequences_passive_MeasureS122c")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MeasureS122c, 3, 1, 1, 1)
        self.checkbox_list_SavedSequences_passive_MeasureS401c = QtWidgets.QCheckBox(Form)
        self.checkbox_list_SavedSequences_passive_MeasureS401c.setObjectName("checkbox_list_SavedSequences_passive_MeasureS401c")
        self.gridLayout_16.addWidget(self.checkbox_list_SavedSequences_passive_MeasureS401c, 4, 1, 1, 1)
        self.main_layout.addLayout(self.gridLayout_16, 5, 0, 1, 2)
        self.button_list_Series_getter_RunSeriesButton = QtWidgets.QPushButton(Form)
        self.button_list_Series_getter_RunSeriesButton.setObjectName("button_list_Series_getter_RunSeriesButton")
        self.main_layout.addWidget(self.button_list_Series_getter_RunSeriesButton, 8, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Series Construction"))
        self.label.setText(_translate("Form", "Series Construction:"))
        self.label_2.setText(_translate("Form", "Sequence Name:"))
        self.button_list_SavedSequences_setter_SaveNewSequenceButton.setText(_translate("Form", "Save New Sequence"))
        self.label_4.setText(_translate("Form", "Saved Sequences:"))
        self.button_list_Series_setter_AddSequenceToSeriesButton.setText(_translate("Form", "Add Sequence To Series"))
        self.label_5.setText(_translate("Form", "Data Configuration:"))
        self.button_list_Series_remover_RemoveSequenceFromSeriesButton.setText(_translate("Form", "Remove Sequence From Series"))
        self.label_3.setText(_translate("Form", "Series:"))
        self.button_list_Series_RemoverOfAll_RemoveAllSequencesFromSeriesButton.setText(_translate("Form", "Remove All Sequences From Series"))
        self.AbortSeriesButton.setText(_translate("Form", "Abort Series"))
        self.label_9.setText(_translate("Form", "Control:"))
        self.PauseSeriesButton.setText(_translate("Form", "Pause Series"))
        self.label_6.setText(_translate("Form", "Record Data From:"))
        self.checkbox_list_SavedSequences_passive_MeasureSr510.setText(_translate("Form", "Sr510"))
        self.checkbox_list_SavedSequences_passive_MeasureSr830.setText(_translate("Form", "Sr830"))
        self.label_8.setText(_translate("Form", "Sample Time:"))
        self.label_7.setText(_translate("Form", "Storage Path:"))
        self.checkbox_list_SavedSequences_passive_MeasureS122vc.setText(_translate("Form", "S122VC"))
        self.checkbox_list_SavedSequences_passive_MeasureS122c.setText(_translate("Form", "S122C"))
        self.checkbox_list_SavedSequences_passive_MeasureS401c.setText(_translate("Form", "S401C"))
        self.button_list_Series_getter_RunSeriesButton.setText(_translate("Form", "Run Series"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

